// packages/react/src/marquee/Marquee.tsx
import { marqueeClass, type MarqueeProps } from './variants';

export function Marquee({
  content,
  children,
  duration = 20,
  direction = 'left',
  pauseOnHover = true,
  gap = 40,
  className,
}: MarqueeProps) {
  const cls = marqueeClass({ direction, pauseOnHover, className });
  const trackStyle = { animationDuration: `${duration}s`, gap: `${gap}px` };
  const inner = children ?? content ?? null;
  return (
    <div className={cls}>
      <div className="cf-marquee__track" style={trackStyle}>
        <div className="cf-marquee__group">{inner}</div>
        <div className="cf-marquee__group" aria-hidden="true">{inner}</div>
      </div>
    </div>
  );
}

// packages/vue/src/marquee/Marquee.vue
<script setup lang="ts">
import { computed } from 'vue';
import { marqueeClass, type MarqueeProps } from './variants';

const props = withDefaults(defineProps<MarqueeProps>(), {
  duration: 20,
  direction: 'left',
  pauseOnHover: true,
  gap: 40,
});

const cls = computed(() =>
  marqueeClass({
    direction: props.direction,
    pauseOnHover: props.pauseOnHover,
    className: props.className,
  }),
);

const trackStyle = computed(() => ({
  animationDuration: `${props.duration}s`,
  gap: `${props.gap}px`,
}));
</script>

<template>
  <div :class="cls">
    <div class="cf-marquee__track" :style="trackStyle">
      <div class="cf-marquee__group">
        <slot>{{ content }}</slot>
      </div>
      <div class="cf-marquee__group" aria-hidden="true">
        <slot>{{ content }}</slot>
      </div>
    </div>
  </div>
</template>
