// packages/vue/src/descriptionlist/DescriptionList.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  descriptionListClass,
  type DescriptionListProps,
} from './variants';

const props = withDefaults(defineProps<DescriptionListProps>(), {
  items: () => [],
  layout: 'horizontal',
  size: 'md',
  columns: 1,
  bordered: false,
});

const cls = computed(() =>
  descriptionListClass({
    layout: props.layout,
    size: props.size,
    bordered: props.bordered,
  }),
);

const styles = computed(() => {
  const out: Record<string, string> = {};
  out['--cf-dl-cols'] = String(props.columns);
  if (props.termWidth != null) {
    const w = typeof props.termWidth === 'number' ? `${props.termWidth}px` : props.termWidth;
    out['--cf-dl-term-width'] = w;
  }
  return out;
});
</script>

<template>
  <div :class="cls" :style="styles">
    <div v-if="title" class="cf-dl__title">{{ title }}</div>
    <dl class="cf-dl__grid">
      <div
        v-for="(item, i) in items"
        :key="item.key ?? i"
        class="cf-dl__row"
        :style="item.span ? { gridColumn: `span ${item.span}` } : undefined"
      >
        <dt class="cf-dl__term">{{ item.term }}</dt>
        <dd class="cf-dl__description">
          <slot :name="item.key ?? `item-${i}`" :item="item">
            {{ item.description }}
          </slot>
        </dd>
      </div>
      <slot />
    </dl>
  </div>
</template>

// packages/react/src/descriptionlist/DescriptionList.tsx
import { type CSSProperties } from 'react';
import {
  descriptionListClass,
  type DescriptionListProps,
} from './variants';

export function DescriptionList(props: DescriptionListProps) {
  const {
    items = [],
    layout = 'horizontal',
    size = 'md',
    columns = 1,
    bordered = false,
    termWidth,
    title,
    className,
    children,
  } = props;

  const styles: CSSProperties = {
    ['--cf-dl-cols' as never]: String(columns),
    ...(termWidth != null
      ? {
          ['--cf-dl-term-width' as never]:
            typeof termWidth === 'number' ? `${termWidth}px` : termWidth,
        }
      : {}),
  };

  return (
    <div
      className={descriptionListClass({ layout, size, bordered, className })}
      style={styles}
    >
      {title ? <div className="cf-dl__title">{title}</div> : null}
      <dl className="cf-dl__grid">
        {items.map((item, i) => (
          <div
            key={item.key ?? i}
            className="cf-dl__row"
            style={item.span ? { gridColumn: `span ${item.span}` } : undefined}
          >
            <dt className="cf-dl__term">{item.term}</dt>
            <dd className="cf-dl__description">{item.description}</dd>
          </div>
        ))}
        {children}
      </dl>
    </div>
  );
}
