// packages/react/src/bulletchart/BulletChart.tsx
import type { BulletChartProps } from './variants';

export function BulletChart(props: BulletChartProps) {
  const {
    value,
    target,
    max,
    bands = [],
    height = 20,
    label,
    ariaLabel,
    className,
  } = props;

  const segs: { x: number; w: number; tone: string }[] = [];
  let prev = 0;
  for (const b of bands) {
    const x = (prev / max) * 100;
    const end = Math.min(b.upTo, max);
    const w = ((end - prev) / max) * 100;
    segs.push({ x, w, tone: b.tone ?? 'default' });
    prev = end;
  }

  const valuePct = Math.min(100, (value / max) * 100);
  const targetPct = target == null ? null : (target / max) * 100;

  return (
    <div
      className={['cf-bullet', className].filter(Boolean).join(' ')}
      role="img"
      aria-label={ariaLabel ?? label ?? '子弹图'}
    >
      {label ? <div className="cf-bullet__label">{label}</div> : null}
      <div className="cf-bullet__track" style={{ height: `${height}px` }}>
        {segs.map((s, i) => (
          <span
            key={i}
            className={`cf-bullet__band cf-bullet__band--${s.tone}`}
            style={{ left: `${s.x}%`, width: `${s.w}%` }}
          />
        ))}
        <span className="cf-bullet__value" style={{ width: `${valuePct}%` }} />
        {targetPct != null ? (
          <span
            className="cf-bullet__target"
            style={{ left: `${targetPct}%` }}
          />
        ) : null}
      </div>
    </div>
  );
}

// packages/vue/src/bulletchart/BulletChart.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { BulletChartProps } from './variants';

const props = withDefaults(defineProps<BulletChartProps>(), {
  width: 240,
  height: 20,
  bands: () => [],
});

const segs = computed(() => {
  const bands = props.bands ?? [];
  const out: { x: number; w: number; tone: string }[] = [];
  let prev = 0;
  for (const b of bands) {
    const x = (prev / props.max) * 100;
    const end = Math.min(b.upTo, props.max);
    const w = ((end - prev) / props.max) * 100;
    out.push({ x, w, tone: b.tone ?? 'default' });
    prev = end;
  }
  return out;
});

const valuePct = computed(() => Math.min(100, (props.value / props.max) * 100));
const targetPct = computed(() =>
  props.target == null ? null : (props.target / props.max) * 100,
);
</script>

<template>
  <div class="cf-bullet" role="img" :aria-label="ariaLabel ?? label ?? '子弹图'">
    <div v-if="label" class="cf-bullet__label">{{ label }}</div>
    <div class="cf-bullet__track" :style="{ height: `${height}px` }">
      <span
        v-for="(s, i) in segs"
        :key="i"
        :class="['cf-bullet__band', `cf-bullet__band--${s.tone}`]"
        :style="{ left: `${s.x}%`, width: `${s.w}%` }"
      />
      <span
        class="cf-bullet__value"
        :style="{ width: `${valuePct}%` }"
      />
      <span
        v-if="targetPct != null"
        class="cf-bullet__target"
        :style="{ left: `${targetPct}%` }"
      />
    </div>
  </div>
</template>
