// packages/vue/src/colorswatch/ColorSwatch.vue
<script setup lang="ts">
import { computed } from 'vue';
import { colorSwatchClass, type ColorSwatchProps } from './variants';

const props = withDefaults(defineProps<ColorSwatchProps>(), {
  size: 'md',
  shape: 'square',
  selected: false,
  disabled: false,
  add: false,
});

const emit = defineEmits<{
  (e: 'click', evt: MouseEvent): void;
}>();

const cls = computed(() => colorSwatchClass(props));
const style = computed(() =>
  props.color && !props.add ? { background: props.color } : undefined,
);
const ariaLabel = computed(() => props.label ?? props.color ?? (props.add ? '添加颜色' : '颜色'));
</script>

<template>
  <button
    type="button"
    :class="cls"
    :style="style"
    :aria-label="ariaLabel"
    :aria-pressed="selected || undefined"
    :disabled="disabled"
    @click="(e) => !disabled && emit('click', e)"
  >
    <svg
      v-if="add"
      class="cf-swatch__plus"
      viewBox="0 0 16 16"
      fill="none"
      aria-hidden="true"
    >
      <path
        d="M8 3v10M3 8h10"
        stroke="currentColor"
        stroke-width="1.6"
        stroke-linecap="round"
      />
    </svg>
  </button>
</template>

// packages/react/src/colorswatch/ColorSwatch.tsx
import { forwardRef } from 'react';
import {
  colorSwatchClass,
  colorSwatchDefaults,
  type ColorSwatchProps,
} from './variants';

export const ColorSwatch = forwardRef<HTMLButtonElement, ColorSwatchProps>(
  function ColorSwatch(props, ref) {
    const {
      color,
      size = colorSwatchDefaults.size,
      shape = colorSwatchDefaults.shape,
      selected,
      add,
      label,
      className,
      style,
      disabled,
      'aria-label': ariaLabelProp,
      ...rest
    } = props;

    const cls = colorSwatchClass({ size, shape, selected, add, className });
    const mergedStyle =
      color && !add ? { ...(style ?? {}), background: color } : style;
    const ariaLabel =
      ariaLabelProp ?? label ?? color ?? (add ? '添加颜色' : '颜色');

    return (
      <button
        ref={ref}
        type="button"
        className={cls}
        style={mergedStyle}
        aria-label={ariaLabel}
        aria-pressed={selected || undefined}
        disabled={disabled}
        {...rest}
      >
        {add ? (
          <svg
            className="cf-swatch__plus"
            viewBox="0 0 16 16"
            fill="none"
            aria-hidden="true"
          >
            <path
              d="M8 3v10M3 8h10"
              stroke="currentColor"
              strokeWidth={1.6}
              strokeLinecap="round"
            />
          </svg>
        ) : null}
      </button>
    );
  },
);
