// packages/vue/src/detachedpanel/DetachedPanel.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import type { DetachedPanelProps } from './variants';

const props = withDefaults(defineProps<DetachedPanelProps>(), {
  open: false,
  width: 360,
  height: 240,
  resizable: false,
  closable: true,
  to: 'body',
});

const emit = defineEmits<{
  (e: 'update:open', value: boolean): void;
  (e: 'move', x: number, y: number): void;
}>();

function defaultX() {
  return typeof window === 'undefined' ? 20 : Math.max(window.innerWidth - 400, 20);
}

const x = ref<number>(props.x ?? defaultX());
const y = ref<number>(props.y ?? 80);
const dragging = ref(false);
let dragOffsetX = 0;
let dragOffsetY = 0;

onMounted(() => {
  if (typeof props.x !== 'number') x.value = defaultX();
});

watch(
  () => [props.x, props.y],
  ([nx, ny]) => {
    if (typeof nx === 'number') x.value = nx;
    if (typeof ny === 'number') y.value = ny;
  },
);

const dimStyle = computed(() => {
  const s: Record<string, string | number> = {
    left: `${x.value}px`,
    top: `${y.value}px`,
    width:
      typeof props.width === 'number' ? `${props.width}px` : props.width,
    height:
      typeof props.height === 'number' ? `${props.height}px` : props.height,
  };
  if (props.zIndex != null) s.zIndex = props.zIndex;
  if (props.resizable) s.resize = 'both';
  return s;
});

const isContained = computed(() => {
  if (typeof props.to !== 'string') {
    return typeof document === 'undefined' ? true : props.to !== document.body;
  }
  const target = props.to.trim().toLowerCase();
  return target !== 'body' && target !== 'html';
});

function onHeaderPointerDown(e: PointerEvent) {
  dragging.value = true;
  dragOffsetX = e.clientX - x.value;
  dragOffsetY = e.clientY - y.value;
  (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
}

function onHeaderPointerMove(e: PointerEvent) {
  if (!dragging.value) return;
  const nx = Math.max(0, e.clientX - dragOffsetX);
  const ny = Math.max(0, e.clientY - dragOffsetY);
  x.value = nx;
  y.value = ny;
  emit('move', nx, ny);
}

function onHeaderPointerUp(e: PointerEvent) {
  if (!dragging.value) return;
  dragging.value = false;
  (e.currentTarget as HTMLElement).releasePointerCapture(e.pointerId);
}

function close() {
  emit('update:open', false);
}

onBeforeUnmount(() => {
  dragging.value = false;
});
</script>

<template>
  <Teleport v-if="open" :to="to">
    <Transition name="cf-detached" appear>
      <section
        class="cf-detached"
        :class="{ 'is-contained': isContained }"
        :style="dimStyle"
        role="dialog"
        :aria-label="title || 'panel'"
      >
        <header
          class="cf-detached__header"
          @pointerdown="onHeaderPointerDown"
          @pointermove="onHeaderPointerMove"
          @pointerup="onHeaderPointerUp"
          @pointercancel="onHeaderPointerUp"
        >
          <span class="cf-detached__title">
            <slot name="title">{{ title }}</slot>
          </span>
          <span class="cf-detached__actions">
            <slot name="actions" />
            <button
              v-if="closable"
              type="button"
              class="cf-detached__close"
              aria-label="关闭"
              @click="close"
            >×</button>
          </span>
        </header>
        <div class="cf-detached__body">
          <slot />
        </div>
      </section>
    </Transition>
  </Teleport>
</template>

// packages/react/src/detachedpanel/DetachedPanel.tsx
import {
  useEffect,
  useRef,
  useState,
  type CSSProperties,
  type PointerEvent as RPointerEvent,
} from 'react';
import { createPortal } from 'react-dom';
import type { DetachedPanelProps } from './variants';

export function DetachedPanel(props: DetachedPanelProps) {
  const {
    open,
    onOpenChange,
    title,
    x: xProp,
    y: yProp,
    width = 360,
    height = 240,
    resizable = false,
    closable = true,
    container,
    zIndex,
    actions,
    children,
    onMove,
    className,
  } = props;

  const [pos, setPos] = useState({
    x:
      xProp ??
      (typeof window !== 'undefined' ? Math.max(window.innerWidth - 400, 20) : 20),
    y: yProp ?? 80,
  });
  const dragRef = useRef<{
    active: boolean;
    offsetX: number;
    offsetY: number;
  }>({ active: false, offsetX: 0, offsetY: 0 });

  useEffect(() => {
    if (typeof xProp === 'number' || typeof yProp === 'number') {
      setPos((c) => ({
        x: typeof xProp === 'number' ? xProp : c.x,
        y: typeof yProp === 'number' ? yProp : c.y,
      }));
    }
  }, [xProp, yProp]);

  const onHeaderPointerDown = (e: RPointerEvent<HTMLElement>) => {
    dragRef.current = {
      active: true,
      offsetX: e.clientX - pos.x,
      offsetY: e.clientY - pos.y,
    };
    e.currentTarget.setPointerCapture(e.pointerId);
  };

  const onHeaderPointerMove = (e: RPointerEvent<HTMLElement>) => {
    if (!dragRef.current.active) return;
    const nx = Math.max(0, e.clientX - dragRef.current.offsetX);
    const ny = Math.max(0, e.clientY - dragRef.current.offsetY);
    setPos({ x: nx, y: ny });
    onMove?.(nx, ny);
  };

  const onHeaderPointerUp = (e: RPointerEvent<HTMLElement>) => {
    if (!dragRef.current.active) return;
    dragRef.current.active = false;
    e.currentTarget.releasePointerCapture(e.pointerId);
  };

  const target =
    typeof window === 'undefined' ? null : (container ?? document.body);
  if (!open || !target) return null;
  const isContained = target !== document.body;

  const style: CSSProperties = {
    left: `${pos.x}px`,
    top: `${pos.y}px`,
    width: typeof width === 'number' ? `${width}px` : width,
    height: typeof height === 'number' ? `${height}px` : height,
    zIndex,
    resize: resizable ? 'both' : undefined,
  };

  return createPortal(
    <section
      className={['cf-detached', isContained && 'is-contained', className]
        .filter(Boolean)
        .join(' ')}
      style={style}
      role="dialog"
      aria-label={typeof title === 'string' ? title : 'panel'}
    >
      <header
        className="cf-detached__header"
        onPointerDown={onHeaderPointerDown}
        onPointerMove={onHeaderPointerMove}
        onPointerUp={onHeaderPointerUp}
        onPointerCancel={onHeaderPointerUp}
      >
        <span className="cf-detached__title">{title}</span>
        <span className="cf-detached__actions">
          {actions}
          {closable ? (
            <button
              type="button"
              className="cf-detached__close"
              aria-label="关闭"
              onClick={() => onOpenChange(false)}
            >
              ×
            </button>
          ) : null}
        </span>
      </header>
      <div className="cf-detached__body">{children}</div>
    </section>,
    target,
  );
}
