// packages/vue/src/radio/Radio.vue
<script setup lang="ts">
import { computed, inject } from 'vue';
import { radioClass, radioGroupKey, type RadioProps, type RadioValue } from './variants';

const props = withDefaults(defineProps<RadioProps>(), {
  modelValue: null,
  size: 'md',
  disabled: false,
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: RadioValue): void;
  (e: 'change', value: RadioValue): void;
}>();

const group = inject(radioGroupKey, null);

const size = computed(() => group?.size ?? props.size);
const disabled = computed(() => group?.disabled || props.disabled);
const name = computed(() => group?.name ?? props.name);
const checked = computed(() => {
  const current = group ? group.value.current : props.modelValue;
  return current === props.value;
});

const cls = computed(() =>
  radioClass({
    size: size.value,
    disabled: disabled.value,
    checked: checked.value,
  }),
);

function onChange() {
  if (disabled.value) return;
  if (group) {
    group.select(props.value);
  } else {
    emit('update:modelValue', props.value);
    emit('change', props.value);
  }
}
</script>

<template>
  <label :class="cls">
    <input
      class="cf-radio__input"
      type="radio"
      :checked="checked"
      :disabled="disabled"
      :name="name"
      :id="id"
      @change="onChange"
    />
    <span class="cf-radio__dot" aria-hidden="true" />
    <span v-if="$slots.default" class="cf-radio__label"><slot /></span>
  </label>
</template>

// packages/react/src/radio/Radio.tsx
import { forwardRef, useContext, useState } from 'react';
import { RadioGroupContext } from './RadioGroup';
import { radioClass, type RadioProps } from './variants';

export const Radio = forwardRef<HTMLInputElement, RadioProps>(function Radio(
  props,
  ref,
) {
  const {
    value,
    checked,
    defaultChecked,
    size = 'md',
    disabled = false,
    name,
    id,
    onChange,
    children,
    className,
  } = props;

  const group = useContext(RadioGroupContext);

  const isControlled = checked !== undefined || group !== null;
  const [internal, setInternal] = useState<boolean>(!!defaultChecked);

  const groupChecked = group ? group.value === value : false;
  const current =
    group !== null
      ? groupChecked
      : isControlled
        ? !!checked
        : internal;

  const finalSize = group?.size ?? size;
  const finalDisabled = (group?.disabled ?? false) || disabled;
  const finalName = group?.name ?? name;

  function handleChange() {
    if (finalDisabled) return;
    if (group) {
      group.select(value);
    } else {
      if (!isControlled) setInternal(true);
      onChange?.(value);
    }
  }

  return (
    <label
      className={radioClass({
        size: finalSize,
        disabled: finalDisabled,
        checked: current,
        className,
      })}
    >
      <input
        ref={ref}
        type="radio"
        className="ck-radio__input"
        checked={current}
        disabled={finalDisabled}
        name={finalName}
        id={id}
        onChange={handleChange}
      />
      <span className="ck-radio__dot" aria-hidden="true" />
      {children ? <span className="ck-radio__label">{children}</span> : null}
    </label>
  );
});
