// packages/react/src/card/Card.tsx
import { forwardRef, type HTMLAttributes } from 'react';
import { cardClass, type CardProps } from './variants';

export const Card = forwardRef<HTMLDivElement, CardProps>(function Card(
  props,
  ref,
) {
  const {
    variant = 'outlined',
    interactive = false,
    className,
    children,
    ...rest
  } = props;

  return (
    <div
      ref={ref}
      className={cardClass({ variant, interactive, className })}
      tabIndex={interactive ? 0 : undefined}
      role={interactive ? 'button' : undefined}
      {...rest}
    >
      {children}
    </div>
  );
});

type SubProps = HTMLAttributes<HTMLDivElement>;

export const CardHeader = forwardRef<HTMLDivElement, SubProps>(function CardHeader(
  { className, ...rest },
  ref,
) {
  return (
    <div
      ref={ref}
      className={['ck-card__header', className].filter(Boolean).join(' ')}
      {...rest}
    />
  );
});

export const CardBody = forwardRef<HTMLDivElement, SubProps>(function CardBody(
  { className, ...rest },
  ref,
) {
  return (
    <div
      ref={ref}
      className={['ck-card__body', className].filter(Boolean).join(' ')}
      {...rest}
    />
  );
});

export const CardFooter = forwardRef<HTMLDivElement, SubProps>(function CardFooter(
  { className, ...rest },
  ref,
) {
  return (
    <div
      ref={ref}
      className={['ck-card__footer', className].filter(Boolean).join(' ')}
      {...rest}
    />
  );
});

// packages/vue/src/card/Card.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cardClass, type CardProps } from './variants';

const props = withDefaults(defineProps<CardProps>(), {
  variant: 'outlined',
  interactive: false,
  as: 'div',
});

defineEmits<{ (e: 'click', evt: MouseEvent): void }>();

const cls = computed(() =>
  cardClass({ variant: props.variant, interactive: props.interactive }),
);
</script>

<template>
  <component
    :is="as"
    :class="cls"
    :tabindex="interactive ? 0 : undefined"
    :role="interactive ? 'button' : undefined"
    @click="(e: MouseEvent) => $emit('click', e)"
  >
    <div v-if="$slots.header" class="ck-card__header">
      <slot name="header" />
    </div>
    <div v-if="$slots.default" class="ck-card__body">
      <slot />
    </div>
    <div v-if="$slots.footer" class="ck-card__footer">
      <slot name="footer" />
    </div>
  </component>
</template>
