// packages/vue/src/tour/Tour.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch, nextTick } from 'vue';
import {
  computeGeometry,
  tourClass,
  type TourGeometry,
  type TourProps,
} from './variants';

const props = withDefaults(defineProps<TourProps>(), {
  defaultValue: false,
  defaultCurrent: 0,
});

const emit = defineEmits<{
  'update:modelValue': [v: boolean];
  'update:current': [n: number];
  finish: [];
  close: [];
}>();

const isOpenControlled = computed(() => props.modelValue !== undefined);
const internalOpen = ref(props.defaultValue);
const open = computed(() =>
  isOpenControlled.value ? !!props.modelValue : internalOpen.value,
);

const isCurrentControlled = computed(() => props.current !== undefined);
const internalCurrent = ref(props.defaultCurrent);
const currentIndex = computed(() =>
  isCurrentControlled.value ? (props.current as number) : internalCurrent.value,
);

const currentStep = computed(() => props.steps[currentIndex.value]);

const geometry = ref<TourGeometry | null>(null);

function setOpen(v: boolean) {
  if (!isOpenControlled.value) internalOpen.value = v;
  emit('update:modelValue', v);
  if (!v) emit('close');
}

function setCurrent(n: number) {
  if (!isCurrentControlled.value) internalCurrent.value = n;
  emit('update:current', n);
}

function recompute() {
  if (typeof document === 'undefined') return;
  const step = currentStep.value;
  if (!step) {
    geometry.value = null;
    return;
  }
  const el = document.querySelector(step.target);
  if (!el) {
    geometry.value = null;
    return;
  }
  geometry.value = computeGeometry(el, step.placement ?? 'bottom');
}

function next() {
  if (currentIndex.value >= props.steps.length - 1) {
    emit('finish');
    setOpen(false);
    setCurrent(0);
  } else {
    setCurrent(currentIndex.value + 1);
  }
}

function prev() {
  if (currentIndex.value > 0) setCurrent(currentIndex.value - 1);
}

function close() {
  setOpen(false);
}

watch([open, currentIndex], () => nextTick(recompute), { immediate: false });

onMounted(() => {
  if (typeof window === 'undefined') return;
  recompute();
  window.addEventListener('scroll', recompute, true);
  window.addEventListener('resize', recompute);
});

onBeforeUnmount(() => {
  if (typeof window === 'undefined') return;
  window.removeEventListener('scroll', recompute, true);
  window.removeEventListener('resize', recompute);
});

const cls = computed(() => tourClass({ className: props.className }));
</script>

<template>
  <Teleport to="body">
    <div v-if="open && currentStep" :class="cls">
      <div class="cf-tour__backdrop" @click="close" />
      <div
        v-if="geometry"
        class="cf-tour__highlight"
        :style="geometry.highlightStyle"
      />
      <div
        v-if="geometry"
        class="cf-tour__popover"
        :style="geometry.popoverStyle"
        role="dialog"
        @click.stop
      >
        <h4 class="cf-tour__title">{{ currentStep.title }}</h4>
        <p v-if="currentStep.description" class="cf-tour__desc">{{ currentStep.description }}</p>
        <div class="cf-tour__footer">
          <span class="cf-tour__progress">{{ currentIndex + 1 }} / {{ steps.length }}</span>
          <div class="cf-tour__actions">
            <button
              v-if="currentIndex > 0"
              type="button"
              class="cf-tour__btn cf-tour__btn--ghost"
              @click="prev"
            >上一步</button>
            <button
              type="button"
              class="cf-tour__btn cf-tour__btn--ghost"
              @click="close"
            >跳过</button>
            <button
              type="button"
              class="cf-tour__btn cf-tour__btn--primary"
              @click="next"
            >{{ currentIndex < steps.length - 1 ? '下一步' : '完成' }}</button>
          </div>
        </div>
      </div>
    </div>
  </Teleport>
</template>

// packages/react/src/tour/Tour.tsx
import { useCallback, useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import {
  computeGeometry,
  tourClass,
  type TourGeometry,
  type TourProps,
} from './variants';

export function Tour({
  steps,
  open,
  defaultOpen = false,
  current,
  defaultCurrent = 0,
  className,
  onOpenChange,
  onCurrentChange,
  onFinish,
  onClose,
}: TourProps) {
  const isOpenControlled = open !== undefined;
  const [internalOpen, setInternalOpen] = useState(defaultOpen);
  const realOpen = isOpenControlled ? !!open : internalOpen;

  const isCurrentControlled = current !== undefined;
  const [internalCurrent, setInternalCurrent] = useState(defaultCurrent);
  const idx = isCurrentControlled ? (current as number) : internalCurrent;

  const step = steps[idx];

  const [geometry, setGeometry] = useState<TourGeometry | null>(null);

  const recompute = useCallback(() => {
    if (typeof document === 'undefined' || !step) {
      setGeometry(null);
      return;
    }
    const el = document.querySelector(step.target);
    if (!el) {
      setGeometry(null);
      return;
    }
    setGeometry(computeGeometry(el, step.placement ?? 'bottom'));
  }, [step]);

  useEffect(() => {
    if (!realOpen) return;
    recompute();
    const onChange = () => recompute();
    window.addEventListener('scroll', onChange, true);
    window.addEventListener('resize', onChange);
    return () => {
      window.removeEventListener('scroll', onChange, true);
      window.removeEventListener('resize', onChange);
    };
  }, [realOpen, recompute]);

  function setOpen(v: boolean) {
    if (!isOpenControlled) setInternalOpen(v);
    onOpenChange?.(v);
    if (!v) onClose?.();
  }

  function setCurrent(n: number) {
    if (!isCurrentControlled) setInternalCurrent(n);
    onCurrentChange?.(n);
  }

  function next() {
    if (idx >= steps.length - 1) {
      onFinish?.();
      setOpen(false);
      setCurrent(0);
    } else {
      setCurrent(idx + 1);
    }
  }
  function prev() {
    if (idx > 0) setCurrent(idx - 1);
  }

  if (!realOpen || !step) return null;
  if (typeof document === 'undefined') return null;

  const cls = tourClass({ className });

  return createPortal(
    <div className={cls}>
      <div className="cf-tour__backdrop" onClick={() => setOpen(false)} />
      {geometry && (
        <div className="cf-tour__highlight" style={geometry.highlightStyle as React.CSSProperties} />
      )}
      {geometry && (
        <div
          className="cf-tour__popover"
          style={geometry.popoverStyle as React.CSSProperties}
          role="dialog"
          onClick={(e) => e.stopPropagation()}
        >
          <h4 className="cf-tour__title">{step.title}</h4>
          {step.description && <p className="cf-tour__desc">{step.description}</p>}
          <div className="cf-tour__footer">
            <span className="cf-tour__progress">{idx + 1} / {steps.length}</span>
            <div className="cf-tour__actions">
              {idx > 0 && (
                <button type="button" className="cf-tour__btn cf-tour__btn--ghost" onClick={prev}>上一步</button>
              )}
              <button type="button" className="cf-tour__btn cf-tour__btn--ghost" onClick={() => setOpen(false)}>跳过</button>
              <button type="button" className="cf-tour__btn cf-tour__btn--primary" onClick={next}>
                {idx < steps.length - 1 ? '下一步' : '完成'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>,
    document.body,
  );
}
