// packages/react/src/kbd/Kbd.tsx
import { Fragment } from 'react';
import { kbdClass, type KbdProps } from './variants';

export function Kbd(props: KbdProps) {
  const { keys, separator = '+', size = 'md', className, children } = props;
  const cls = kbdClass({ size, className });
  if (keys?.length) {
    return (
      <span className={cls}>
        {keys.map((k, i) => (
          <Fragment key={i}>
            <kbd className="cf-kbd__key">{k}</kbd>
            {i < keys.length - 1 ? (
              <span className="cf-kbd__sep">{separator}</span>
            ) : null}
          </Fragment>
        ))}
      </span>
    );
  }
  return (
    <span className={cls}>
      <kbd className="cf-kbd__key">{children}</kbd>
    </span>
  );
}

// packages/vue/src/kbd/Kbd.vue
<script setup lang="ts">
import { computed } from 'vue';
import { kbdClass, type KbdProps } from './variants';

const props = withDefaults(defineProps<KbdProps>(), {
  keys: () => [] as string[],
  separator: '+',
  size: 'md',
});

const cls = computed(() => kbdClass({ size: props.size }));
</script>

<template>
  <span :class="cls">
    <template v-if="keys.length">
      <template v-for="(key, i) in keys" :key="i">
        <kbd class="cf-kbd__key">{{ key }}</kbd>
        <span v-if="i < keys.length - 1" class="cf-kbd__sep">{{ separator }}</span>
      </template>
    </template>
    <kbd v-else class="cf-kbd__key"><slot /></kbd>
  </span>
</template>
