// packages/react/src/virtualgrid/VirtualGrid.tsx
import { useEffect, useMemo, useRef, useState, type CSSProperties } from 'react';
import { computeGrid, type VirtualGridProps } from './variants';

export function VirtualGrid<T>(props: VirtualGridProps<T>) {
  const {
    items,
    itemHeight,
    minColumnWidth = 200,
    columns,
    gap = 8,
    overscan = 2,
    height,
    className,
    itemKey,
    renderItem,
  } = props;

  const scrollerRef = useRef<HTMLDivElement | null>(null);
  const [scrollTop, setScrollTop] = useState(0);
  const [containerWidth, setContainerWidth] = useState(800);
  const [viewportHeight, setViewportHeight] = useState(400);

  useEffect(() => {
    const el = scrollerRef.current;
    if (!el) return;
    setContainerWidth(el.clientWidth);
    setViewportHeight(el.clientHeight);
    const onScroll = () => setScrollTop(el.scrollTop);
    el.addEventListener('scroll', onScroll, { passive: true });
    let ro: ResizeObserver | null = null;
    if (typeof ResizeObserver !== 'undefined') {
      ro = new ResizeObserver(() => {
        setContainerWidth(el.clientWidth);
        setViewportHeight(el.clientHeight);
      });
      ro.observe(el);
    }
    return () => {
      el.removeEventListener('scroll', onScroll);
      ro?.disconnect();
    };
  }, []);

  const win = useMemo(
    () =>
      computeGrid({
        totalItems: items.length,
        containerWidth,
        itemHeight,
        scrollTop,
        viewportHeight,
        gap,
        overscan,
        columns,
        minColumnWidth,
      }),
    [items.length, containerWidth, itemHeight, scrollTop, viewportHeight, gap, overscan, columns, minColumnWidth],
  );

  const cells: { item: T; index: number; row: number; col: number; key: string | number }[] = [];
  for (let r = win.rowStart; r < win.rowEnd; r++) {
    for (let c = 0; c < win.cols; c++) {
      const idx = r * win.cols + c;
      if (idx >= items.length) break;
      const item = items[idx];
      cells.push({ item, index: idx, row: r, col: c, key: itemKey ? itemKey(item, idx) : idx });
    }
  }

  const rootStyle: CSSProperties = {
    height: typeof height === 'number' ? `${height}px` : (height ?? '100%'),
  };
  const innerStyle: CSSProperties = {
    height: `${win.totalRows * win.rowHeight - gap}px`,
    position: 'relative',
  };

  return (
    <div ref={scrollerRef} className={['cf-vgrid', className].filter(Boolean).join(' ')} style={rootStyle}>
      <div className="cf-vgrid__inner" style={innerStyle}>
        {cells.map((cell) => (
          <div
            key={cell.key}
            className="cf-vgrid__cell"
            style={{
              position: 'absolute',
              top: `${cell.row * win.rowHeight}px`,
              left: `${cell.col * (win.cellWidth + gap)}px`,
              width: `${win.cellWidth}px`,
              height: `${itemHeight}px`,
            }}
          >
            {renderItem(cell.item, cell.index)}
          </div>
        ))}
      </div>
    </div>
  );
}

// packages/vue/src/virtualgrid/VirtualGrid.vue
<script setup lang="ts" generic="T">
import { computed, onMounted, ref } from 'vue';
import { computeGrid, type VirtualGridProps } from './variants';

const props = withDefaults(defineProps<VirtualGridProps<T>>(), {
  gap: 8,
  overscan: 2,
  minColumnWidth: 200,
});

const scrollerRef = ref<HTMLDivElement | null>(null);
const scrollTop = ref(0);
const containerWidth = ref(800);
const viewportHeight = ref(400);

function onScroll() {
  if (!scrollerRef.value) return;
  scrollTop.value = scrollerRef.value.scrollTop;
}

function syncSize() {
  if (!scrollerRef.value) return;
  containerWidth.value = scrollerRef.value.clientWidth;
  viewportHeight.value = scrollerRef.value.clientHeight;
}

onMounted(() => {
  syncSize();
  scrollerRef.value?.addEventListener('scroll', onScroll, { passive: true });
  if (typeof ResizeObserver !== 'undefined' && scrollerRef.value) {
    new ResizeObserver(syncSize).observe(scrollerRef.value);
  }
});

const win = computed(() =>
  computeGrid({
    totalItems: props.items.length,
    containerWidth: containerWidth.value,
    itemHeight: props.itemHeight,
    scrollTop: scrollTop.value,
    viewportHeight: viewportHeight.value,
    gap: props.gap,
    overscan: props.overscan,
    columns: props.columns,
    minColumnWidth: props.minColumnWidth,
  }),
);

const visibleCells = computed(() => {
  const { rowStart, rowEnd, cols } = win.value;
  const out: Array<{ item: T; index: number; row: number; col: number; key: string | number }> = [];
  for (let r = rowStart; r < rowEnd; r++) {
    for (let c = 0; c < cols; c++) {
      const idx = r * cols + c;
      if (idx >= props.items.length) break;
      const item = props.items[idx];
      out.push({ item, index: idx, row: r, col: c, key: props.itemKey ? props.itemKey(item, idx) : idx });
    }
  }
  return out;
});

const innerStyle = computed(() => ({
  height: `${win.value.totalRows * win.value.rowHeight - props.gap}px`,
  position: 'relative' as const,
}));

const rootStyle = computed(() => ({
  height: typeof props.height === 'number' ? `${props.height}px` : (props.height ?? '100%'),
}));

function cellStyle(row: number, col: number) {
  const { cellWidth, rowHeight } = win.value;
  return {
    position: 'absolute' as const,
    top: `${row * rowHeight}px`,
    left: `${col * (cellWidth + props.gap)}px`,
    width: `${cellWidth}px`,
    height: `${props.itemHeight}px`,
  };
}
</script>

<template>
  <div ref="scrollerRef" :class="['cf-vgrid', className]" :style="rootStyle">
    <div class="cf-vgrid__inner" :style="innerStyle">
      <div
        v-for="cell in visibleCells"
        :key="cell.key"
        class="cf-vgrid__cell"
        :style="cellStyle(cell.row, cell.col)"
      >
        <slot :item="cell.item" :index="cell.index" />
      </div>
    </div>
  </div>
</template>
