// packages/vue/src/modal/Modal.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue';
import {
  trapFocus,
  lockBodyScroll,
  unlockBodyScroll,
  type FocusTrap,
} from './dom';
import {
  pushModal,
  topMostCloseFn,
  toneClass,
  TONE_ICON_PATH,
  type ModalProps,
  type ModalTone,
} from './variants';

const props = withDefaults(defineProps<ModalProps>(), {
  open: false,
  size: 'md',
  tone: 'default',
  closeOnOverlay: true,
  closeOnEsc: true,
  showClose: true,
  centered: true,
  footerAlign: 'end',
  draggable: false,
  resizable: false,
  okVariant: 'primary',
  to: 'body',
});

const emit = defineEmits<{
  (e: 'update:open', value: boolean): void;
  (e: 'close'): void;
  (e: 'ok'): void;
  (e: 'cancel'): void;
}>();

const dialogRef = ref<HTMLDivElement | null>(null);
let trap: FocusTrap | null = null;
let stackEntry: { zIndex: number; release: () => void } | null = null;

const computedZ = ref<number>(props.zIndex ?? 1000);

const dragOffset = ref({ x: 0, y: 0 });
const sizeOverride = ref<{ width?: number; height?: number }>({});
const okLoading = ref(false);

function close() {
  if (okLoading.value) return;
  emit('update:open', false);
  emit('close');
}

function onOverlayClick(e: MouseEvent) {
  if (!props.closeOnOverlay) return;
  if (okLoading.value) return;
  if (e.target === e.currentTarget) close();
}

function onKeyDown(e: KeyboardEvent) {
  if (e.key === 'Escape' && props.closeOnEsc) {
    if (topMostCloseFn() === close) {
      e.stopPropagation();
      close();
    }
  }
}

async function onOk() {
  if (props.onBeforeOk) {
    okLoading.value = true;
    try {
      const r = await props.onBeforeOk();
      if (r === false) return;
    } catch {
      return;
    } finally {
      okLoading.value = false;
    }
  }
  emit('ok');
  emit('update:open', false);
  emit('close');
}

function onCancel() {
  if (okLoading.value) return;
  emit('cancel');
  close();
}

watch(
  () => props.open,
  async (open) => {
    if (open) {
      lockBodyScroll();
      stackEntry = pushModal(close);
      computedZ.value = props.zIndex ?? stackEntry.zIndex;
      dragOffset.value = { x: 0, y: 0 };
      sizeOverride.value = {};
      okLoading.value = false;
      await nextTick();
      if (dialogRef.value) trap = trapFocus(dialogRef.value);
      if (typeof window !== 'undefined') window.addEventListener('keydown', onKeyDown, true);
    } else {
      trap?.release();
      trap = null;
      unlockBodyScroll();
      stackEntry?.release();
      stackEntry = null;
      if (typeof window !== 'undefined') window.removeEventListener('keydown', onKeyDown, true);
    }
  },
);

onBeforeUnmount(() => {
  if (props.open) {
    trap?.release();
    unlockBodyScroll();
    stackEntry?.release();
    if (typeof window !== 'undefined') window.removeEventListener('keydown', onKeyDown, true);
  }
});

/* 拖拽 header */
interface DragState { startX: number; startY: number; baseX: number; baseY: number; }
const drag = ref<DragState | null>(null);

function onDragPointerDown(e: PointerEvent) {
  if (!props.draggable) return;
  if ((e.target as HTMLElement).closest('button')) return;
  e.preventDefault();
  drag.value = { startX: e.clientX, startY: e.clientY, baseX: dragOffset.value.x, baseY: dragOffset.value.y };
  (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
}
function onDragPointerMove(e: PointerEvent) {
  if (!drag.value) return;
  dragOffset.value = {
    x: drag.value.baseX + (e.clientX - drag.value.startX),
    y: drag.value.baseY + (e.clientY - drag.value.startY),
  };
}
function onDragPointerEnd() {
  drag.value = null;
}

/* 缩放 */
interface ResizeState { startX: number; startY: number; w: number; h: number; }
const resize = ref<ResizeState | null>(null);

function onResizePointerDown(e: PointerEvent) {
  if (!props.resizable || !dialogRef.value) return;
  e.preventDefault();
  e.stopPropagation();
  const rect = dialogRef.value.getBoundingClientRect();
  resize.value = { startX: e.clientX, startY: e.clientY, w: rect.width, h: rect.height };
  (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
}
function onResizePointerMove(e: PointerEvent) {
  if (!resize.value) return;
  sizeOverride.value = {
    width: Math.max(280, resize.value.w + (e.clientX - resize.value.startX)),
    height: Math.max(160, resize.value.h + (e.clientY - resize.value.startY)),
  };
}
function onResizePointerEnd() {
  resize.value = null;
}

/* dialog 样式 */
const dialogStyle = computed(() => {
  const out: Record<string, string | undefined> = {};
  if (props.width != null) {
    out.width = typeof props.width === 'number' ? `${props.width}px` : props.width;
  }
  if (sizeOverride.value.width) out.width = `${sizeOverride.value.width}px`;
  if (props.minHeight != null) {
    out.minHeight = typeof props.minHeight === 'number' ? `${props.minHeight}px` : props.minHeight;
  }
  if (sizeOverride.value.height) out.height = `${sizeOverride.value.height}px`;
  if (dragOffset.value.x !== 0 || dragOffset.value.y !== 0) {
    out.transform = `translate(${dragOffset.value.x}px, ${dragOffset.value.y}px)`;
  }
  return out;
});

const overlayStyle = computed(() => ({
  zIndex: String(computedZ.value),
  alignItems: props.centered ? 'center' : 'flex-start',
  paddingTop: props.centered ? undefined : '80px',
}));

function toneIconPath(t: ModalTone): string {
  return t === 'default' ? '' : (TONE_ICON_PATH as Record<string, string>)[t];
}

defineExpose({ close, ok: onOk });
</script>

<template>
  <Teleport :to="to">
    <Transition name="cf-modal" appear>
      <div
        v-if="open"
        :class="['cf-modal__overlay', toneClass(tone)]"
        :style="overlayStyle"
        role="presentation"
        @click="onOverlayClick"
      >
        <div
          ref="dialogRef"
          :class="['cf-modal__dialog', `cf-modal__dialog--${size}`, draggable && 'is-draggable', resizable && 'is-resizable']"
          :style="dialogStyle"
          role="dialog"
          aria-modal="true"
          :aria-labelledby="title ? 'cf-modal-title' : undefined"
          :aria-describedby="description ? 'cf-modal-desc' : undefined"
          tabindex="-1"
        >
          <div
            v-if="title || $slots.header || tone !== 'default'"
            class="cf-modal__header"
            @pointerdown="onDragPointerDown"
            @pointermove="onDragPointerMove"
            @pointerup="onDragPointerEnd"
            @pointercancel="onDragPointerEnd"
          >
            <span v-if="tone !== 'default'" class="cf-modal__tone-icon" aria-hidden="true">
              <svg viewBox="0 0 24 24" width="20" height="20"><path :d="toneIconPath(tone)" fill="currentColor" /></svg>
            </span>
            <div class="cf-modal__title-block">
              <h2 v-if="title || !$slots.header" id="cf-modal-title" class="cf-modal__title">
                <slot name="header">{{ title }}</slot>
              </h2>
              <p v-if="description" id="cf-modal-desc" class="cf-modal__desc">{{ description }}</p>
            </div>
          </div>
          <button
            v-if="showClose"
            type="button"
            class="cf-modal__close"
            aria-label="关闭"
            :disabled="okLoading"
            @click="close"
          >
            <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round">
              <path d="M4 4l8 8M12 4l-8 8" />
            </svg>
          </button>

          <div class="cf-modal__body">
            <slot />
          </div>

          <div
            v-if="$slots.footer || okText || cancelText"
            class="cf-modal__footer"
            :data-align="footerAlign"
          >
            <slot name="footer" :ok="onOk" :cancel="onCancel" :loading="okLoading">
              <button
                v-if="cancelText"
                type="button"
                class="cf-modal__footer-btn cf-modal__footer-btn--secondary"
                :disabled="okLoading"
                @click="onCancel"
              >
                {{ cancelText }}
              </button>
              <button
                v-if="okText"
                type="button"
                :class="['cf-modal__footer-btn', `cf-modal__footer-btn--${tone === 'error' ? 'danger' : okVariant}`, okLoading && 'is-loading']"
                :disabled="okLoading"
                @click="onOk"
              >
                <span v-if="okLoading" class="cf-modal__footer-spinner" />
                {{ okText }}
              </button>
            </slot>
          </div>

          <span
            v-if="resizable"
            class="cf-modal__resize-handle"
            @pointerdown="onResizePointerDown"
            @pointermove="onResizePointerMove"
            @pointerup="onResizePointerEnd"
            @pointercancel="onResizePointerEnd"
          />
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

// packages/react/src/modal/Modal.tsx
import {
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type KeyboardEvent,
  type MouseEvent,
  type PointerEvent as ReactPointerEvent,
  type ReactNode,
} from 'react';
import { createPortal } from 'react-dom';
import {
  lockBodyScroll,
  trapFocus,
  unlockBodyScroll,
  type FocusTrap,
} from './dom';
import {
  pushModal,
  topMostCloseFn,
  toneClass,
  TONE_ICON_PATH,
  type FooterAlign,
  type ModalProps as BaseModalProps,
  type ModalTone,
} from './variants';

const ANIMATION_MS = 180;

export interface ModalProps extends BaseModalProps {
  /** React-style controlled callback. */
  onOpenChange: (open: boolean) => void;
  header?: ReactNode;
  footer?: ReactNode | ((ctx: { ok: () => void; cancel: () => void; loading: boolean }) => ReactNode);
  children?: ReactNode;
  /** Where to portal. Defaults to document.body. */
  container?: HTMLElement;
  onOk?: () => void;
  onCancel?: () => void;
}

export function Modal(props: ModalProps) {
  const {
    open,
    onOpenChange,
    title,
    description,
    size = 'md',
    tone = 'default',
    closeOnOverlay = true,
    closeOnEsc = true,
    showClose = true,
    centered = true,
    width,
    minHeight,
    footerAlign = 'end',
    draggable = false,
    resizable = false,
    okText,
    cancelText,
    okVariant = 'primary',
    onBeforeOk,
    container,
    header,
    footer,
    children,
    onOk,
    onCancel,
    zIndex,
  } = props;

  const [mounted, setMounted] = useState(open);
  const [state, setState] = useState<'open' | 'closed'>(open ? 'open' : 'closed');
  const dialogRef = useRef<HTMLDivElement | null>(null);
  const trapRef = useRef<FocusTrap | null>(null);
  const stackEntryRef = useRef<{ zIndex: number; release: () => void } | null>(null);
  const [computedZ, setComputedZ] = useState<number>(zIndex ?? 1000);

  const [dragOffset, setDragOffset] = useState({ x: 0, y: 0 });
  const [sizeOverride, setSizeOverride] = useState<{ width?: number; height?: number }>({});
  const [okLoading, setOkLoading] = useState(false);

  function close() {
    if (okLoading) return;
    onOpenChange(false);
  }

  // mount / unmount with animation
  useLayoutEffect(() => {
    if (open) {
      setMounted(true);
      const id = requestAnimationFrame(() => setState('open'));
      return () => cancelAnimationFrame(id);
    }
    if (mounted) {
      setState('closed');
      const t = setTimeout(() => setMounted(false), ANIMATION_MS);
      return () => clearTimeout(t);
    }
    return undefined;
  }, [open, mounted]);

  // stack push / pop
  useEffect(() => {
    if (!mounted || state !== 'open') return;
    setDragOffset({ x: 0, y: 0 });
    setSizeOverride({});
    setOkLoading(false);

    stackEntryRef.current = pushModal(close);
    setComputedZ(zIndex ?? stackEntryRef.current.zIndex);

    return () => {
      stackEntryRef.current?.release();
      stackEntryRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mounted, state]);

  // focus trap + scroll lock + ESC
  useEffect(() => {
    if (!mounted || state !== 'open') return;
    lockBodyScroll();
    if (dialogRef.current) trapRef.current = trapFocus(dialogRef.current);

    const handler = (e: globalThis.KeyboardEvent) => {
      if (e.key === 'Escape' && closeOnEsc && topMostCloseFn() === close) {
        e.stopPropagation();
        if (!okLoading) onOpenChange(false);
      }
    };
    if (typeof window !== 'undefined') window.addEventListener('keydown', handler, true);

    return () => {
      trapRef.current?.release();
      trapRef.current = null;
      unlockBodyScroll();
      if (typeof window !== 'undefined') window.removeEventListener('keydown', handler, true);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mounted, state, closeOnEsc, okLoading]);

  async function doOk() {
    if (onBeforeOk) {
      setOkLoading(true);
      try {
        const r = await onBeforeOk();
        if (r === false) return;
      } catch {
        return;
      } finally {
        setOkLoading(false);
      }
    }
    onOk?.();
    onOpenChange(false);
  }
  function doCancel() {
    if (okLoading) return;
    onCancel?.();
    onOpenChange(false);
  }

  // Drag header
  const dragRef = useRef<{ startX: number; startY: number; baseX: number; baseY: number } | null>(null);
  const onDragPointerDown = (e: ReactPointerEvent) => {
    if (!draggable) return;
    if ((e.target as HTMLElement).closest('button')) return;
    e.preventDefault();
    dragRef.current = { startX: e.clientX, startY: e.clientY, baseX: dragOffset.x, baseY: dragOffset.y };
    (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
  };
  const onDragPointerMove = (e: ReactPointerEvent) => {
    if (!dragRef.current) return;
    setDragOffset({
      x: dragRef.current.baseX + (e.clientX - dragRef.current.startX),
      y: dragRef.current.baseY + (e.clientY - dragRef.current.startY),
    });
  };
  const onDragPointerEnd = () => {
    dragRef.current = null;
  };

  // Resize
  const resizeRef = useRef<{ startX: number; startY: number; w: number; h: number } | null>(null);
  const onResizePointerDown = (e: ReactPointerEvent) => {
    if (!resizable || !dialogRef.current) return;
    e.preventDefault();
    e.stopPropagation();
    const rect = dialogRef.current.getBoundingClientRect();
    resizeRef.current = { startX: e.clientX, startY: e.clientY, w: rect.width, h: rect.height };
    (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
  };
  const onResizePointerMove = (e: ReactPointerEvent) => {
    if (!resizeRef.current) return;
    setSizeOverride({
      width: Math.max(280, resizeRef.current.w + (e.clientX - resizeRef.current.startX)),
      height: Math.max(160, resizeRef.current.h + (e.clientY - resizeRef.current.startY)),
    });
  };
  const onResizePointerEnd = () => {
    resizeRef.current = null;
  };

  const dialogStyle = useMemo<CSSProperties>(() => {
    const out: CSSProperties = {};
    if (width != null) out.width = typeof width === 'number' ? `${width}px` : width;
    if (sizeOverride.width) out.width = `${sizeOverride.width}px`;
    if (minHeight != null) out.minHeight = typeof minHeight === 'number' ? `${minHeight}px` : minHeight;
    if (sizeOverride.height) out.height = `${sizeOverride.height}px`;
    if (dragOffset.x !== 0 || dragOffset.y !== 0) {
      out.transform = `translate(${dragOffset.x}px, ${dragOffset.y}px)`;
    }
    return out;
  }, [width, minHeight, sizeOverride, dragOffset]);

  const overlayStyle = useMemo<CSSProperties>(
    () => ({
      zIndex: computedZ,
      alignItems: centered ? 'center' : 'flex-start',
      paddingTop: centered ? undefined : '80px',
    }),
    [computedZ, centered],
  );

  function onOverlayClick(e: MouseEvent<HTMLDivElement>) {
    if (!closeOnOverlay || okLoading) return;
    if (e.target === e.currentTarget) close();
  }
  function onKeyDownLocal(e: KeyboardEvent<HTMLDivElement>) {
    // 让全局监听处理 ESC（避免重复）
    if (e.key === 'Escape') e.stopPropagation();
  }

  if (!mounted) return null;
  if (typeof document === 'undefined') return null;

  const okBtnVariant = tone === 'error' ? 'danger' : okVariant;
  const showHeader = title || header || tone !== 'default';

  const node = (
    <div
      data-cf-modal=""
      data-state={state}
      className={['cf-modal__overlay', toneClass(tone)].filter(Boolean).join(' ')}
      style={overlayStyle}
      role="presentation"
      onClick={onOverlayClick}
      onKeyDown={onKeyDownLocal}
    >
      <div
        ref={dialogRef}
        className={[
          'cf-modal__dialog',
          `cf-modal__dialog--${size}`,
          draggable ? 'is-draggable' : '',
          resizable ? 'is-resizable' : '',
        ]
          .filter(Boolean)
          .join(' ')}
        style={dialogStyle}
        role="dialog"
        aria-modal="true"
        aria-labelledby={title ? 'cf-modal-title' : undefined}
        aria-describedby={description ? 'cf-modal-desc' : undefined}
        tabIndex={-1}
      >
        {showHeader && (
          <div
            className="cf-modal__header"
            onPointerDown={onDragPointerDown}
            onPointerMove={onDragPointerMove}
            onPointerUp={onDragPointerEnd}
            onPointerCancel={onDragPointerEnd}
          >
            {tone !== 'default' && (
              <span className="cf-modal__tone-icon" aria-hidden>
                <svg viewBox="0 0 24 24" width={20} height={20}>
                  <path
                    d={(TONE_ICON_PATH as Record<string, string>)[tone]}
                    fill="currentColor"
                  />
                </svg>
              </span>
            )}
            <div className="cf-modal__title-block">
              {(title || !header) && (
                <h2 id="cf-modal-title" className="cf-modal__title">
                  {header ?? title}
                </h2>
              )}
              {description && (
                <p id="cf-modal-desc" className="cf-modal__desc">
                  {description}
                </p>
              )}
            </div>
          </div>
        )}
        {showClose && (
          <button
            type="button"
            className="cf-modal__close"
            aria-label="Close"
            disabled={okLoading}
            onClick={close}
          >
            <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round">
              <path d="M4 4l8 8M12 4l-8 8" />
            </svg>
          </button>
        )}

        <div className="cf-modal__body">{children}</div>

        {(footer || okText || cancelText) && (
          <div className="cf-modal__footer" data-align={footerAlign}>
            {typeof footer === 'function' ? (
              footer({ ok: doOk, cancel: doCancel, loading: okLoading })
            ) : footer ? (
              footer
            ) : (
              <>
                {cancelText && (
                  <button
                    type="button"
                    className="cf-modal__footer-btn cf-modal__footer-btn--secondary"
                    disabled={okLoading}
                    onClick={doCancel}
                  >
                    {cancelText}
                  </button>
                )}
                {okText && (
                  <button
                    type="button"
                    className={[
                      'cf-modal__footer-btn',
                      `cf-modal__footer-btn--${okBtnVariant}`,
                      okLoading ? 'is-loading' : '',
                    ]
                      .filter(Boolean)
                      .join(' ')}
                    disabled={okLoading}
                    onClick={doOk}
                  >
                    {okLoading && <span className="cf-modal__footer-spinner" />}
                    {okText}
                  </button>
                )}
              </>
            )}
          </div>
        )}

        {resizable && (
          <span
            className="cf-modal__resize-handle"
            onPointerDown={onResizePointerDown}
            onPointerMove={onResizePointerMove}
            onPointerUp={onResizePointerEnd}
            onPointerCancel={onResizePointerEnd}
          />
        )}
      </div>
    </div>
  );

  return createPortal(node, container ?? document.body);
}
