// packages/react/src/button/Button.tsx
import { forwardRef } from 'react';
import { buttonClass, buttonDefaults, type ButtonProps } from './variants';

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button(
  props,
  ref,
) {
  const {
    variant = buttonDefaults.variant,
    size = buttonDefaults.size,
    shape = buttonDefaults.shape,
    tone = buttonDefaults.tone,
    loading = false,
    block = false,
    disabled,
    leading,
    trailing,
    className,
    type = 'button',
    children,
    onClick,
    ...rest
  } = props;

  const isInactive = disabled || loading;
  const cls = buttonClass({ variant, size, shape, tone, loading, block, className });

  return (
    <button
      ref={ref}
      type={type}
      className={cls}
      disabled={isInactive}
      aria-busy={loading || undefined}
      onClick={(e) => {
        if (isInactive) return;
        onClick?.(e);
      }}
      {...rest}
    >
      {loading ? (
        <span className="ck-btn__spinner" aria-hidden />
      ) : leading ? (
        <span className="ck-btn__leading">{leading}</span>
      ) : null}
      <span className="ck-btn__label">{children}</span>
      {trailing ? <span className="ck-btn__trailing">{trailing}</span> : null}
    </button>
  );
});

// packages/vue/src/button/Button.vue
<script setup lang="ts">
import { computed } from 'vue';
import { buttonClass, type ButtonProps } from './variants';

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'solid',
  size: 'md',
  shape: 'default',
  tone: 'primary',
  disabled: false,
  loading: false,
  block: false,
  type: 'button',
});

defineEmits<{ (e: 'click', evt: MouseEvent): void }>();

const cls = computed(() => buttonClass(props));
const ariaDisabled = computed(() => props.disabled || props.loading);
</script>

<template>
  <button
    :class="cls"
    :type="type"
    :disabled="ariaDisabled"
    :aria-busy="loading || undefined"
    @click="(e) => !ariaDisabled && $emit('click', e)"
  >
    <span v-if="loading" class="ck-btn__spinner" aria-hidden="true" />
    <span v-else-if="$slots.leading" class="ck-btn__leading">
      <slot name="leading" />
    </span>
    <span class="ck-btn__label"><slot /></span>
    <span v-if="$slots.trailing" class="ck-btn__trailing">
      <slot name="trailing" />
    </span>
  </button>
</template>
