// packages/react/src/bottomsheet/BottomSheet.tsx
import {
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type MouseEvent,
} from 'react';
import { createPortal } from 'react-dom';
import { useDrag } from '../hooks/useDrag';
import {
  lockBodyScroll,
  trapFocus,
  unlockBodyScroll,
  type FocusTrap,
} from '../modal/dom';
import { nearestSnapIndex, resolveSnap, type BottomSheetProps } from './variants';

const ANIMATION_MS = 220;

export function BottomSheet(props: BottomSheetProps) {
  const {
    open,
    onOpenChange,
    snapPoints = ['40%', '90%'],
    initialSnap = 0,
    showGrabber = true,
    maskClosable = true,
    closeOnEsc = true,
    mask = true,
    dismissible = true,
    container,
    zIndex,
    title,
    onSnapChange,
    children,
  } = props;

  const [mounted, setMounted] = useState(open);
  const [state, setState] = useState<'open' | 'closed'>(open ? 'open' : 'closed');
  const panelRef = useRef<HTMLDivElement | null>(null);
  const contentRef = useRef<HTMLDivElement | null>(null);
  const grabberRef = useRef<HTMLDivElement | null>(null);
  const trapRef = useRef<FocusTrap | null>(null);
  const [snapIndex, setSnapIndex] = useState(initialSnap);
  const [dragHeight, setDragHeight] = useState<number | null>(null);
  const [windowH, setWindowH] = useState(0);

  function close() {
    onOpenChange(false);
  }

  useLayoutEffect(() => {
    if (open) {
      setMounted(true);
      setSnapIndex(initialSnap);
      if (typeof window !== 'undefined') setWindowH(window.innerHeight);
      const id = requestAnimationFrame(() => setState('open'));
      return () => cancelAnimationFrame(id);
    }
    if (mounted) {
      setState('closed');
      const t = setTimeout(() => setMounted(false), ANIMATION_MS);
      return () => clearTimeout(t);
    }
    return undefined;
  }, [open, mounted, initialSnap]);

  useEffect(() => {
    if (!mounted || state !== 'open') return;
    if (mask) lockBodyScroll();
    if (panelRef.current) trapRef.current = trapFocus(panelRef.current);
    const handler = (e: globalThis.KeyboardEvent) => {
      if (e.key === 'Escape' && closeOnEsc) {
        e.stopPropagation();
        close();
      }
    };
    if (typeof window !== 'undefined') window.addEventListener('keydown', handler, true);
    return () => {
      trapRef.current?.release();
      trapRef.current = null;
      if (mask) unlockBodyScroll();
      if (typeof window !== 'undefined') window.removeEventListener('keydown', handler, true);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mounted, state, closeOnEsc, mask]);

  const snapHeights = useMemo(() => {
    const wh = windowH || 800;
    const ch = contentRef.current?.scrollHeight ?? 400;
    return snapPoints.map((s) => resolveSnap(s, wh, ch));
  }, [snapPoints, windowH, mounted]);

  const targetHeight = useMemo(() => {
    if (snapHeights.length === 0) return 200;
    return snapHeights[Math.max(0, Math.min(snapIndex, snapHeights.length - 1))];
  }, [snapHeights, snapIndex]);

  const currentHeight = dragHeight ?? targetHeight;

  useDrag(grabberRef, {
    axis: 'y',
    onMove(s) {
      setDragHeight(Math.max(0, targetHeight - s.dy));
    },
    onEnd(s) {
      if (snapHeights.length === 0) {
        setDragHeight(null);
        return;
      }
      const released = (dragHeight ?? targetHeight) - 0; // current actually
      const smallest = snapHeights[0];
      const fastDown = s.vy > 0.5;
      if (dismissible && (released < smallest * 0.5 || fastDown)) {
        setDragHeight(null);
        close();
        return;
      }
      const idx = nearestSnapIndex(snapHeights, released);
      setDragHeight(null);
      if (idx !== snapIndex) {
        setSnapIndex(idx);
        onSnapChange?.(idx);
      }
    },
  });

  function onOverlayClick(e: MouseEvent<HTMLDivElement>) {
    if (!maskClosable) return;
    if (e.target === e.currentTarget) close();
  }

  if (!mounted) return null;
  if (typeof document === 'undefined') return null;

  const overlayStyle: CSSProperties = {
    zIndex: zIndex ?? undefined,
    pointerEvents: mask ? undefined : 'none',
    background: mask ? undefined : 'transparent',
  };
  const panelStyle: CSSProperties = {
    height: `${currentHeight}px`,
    transition: dragHeight !== null ? 'none' : undefined,
  };

  const node = (
    <div
      className={['cf-sheet__overlay', !mask ? 'cf-sheet__overlay--no-mask' : '']
        .filter(Boolean)
        .join(' ')}
      data-state={state}
      style={overlayStyle}
      role="presentation"
      onClick={onOverlayClick}
    >
      <div
        ref={panelRef}
        className="cf-sheet__panel"
        style={panelStyle}
        role="dialog"
        aria-modal="true"
        tabIndex={-1}
      >
        {showGrabber && (
          <div ref={grabberRef} className="cf-sheet__grabber" aria-hidden>
            <span className="cf-sheet__grabber-bar" />
          </div>
        )}
        {title && (
          <div className="cf-sheet__header">
            <h2 className="cf-sheet__title">{title}</h2>
          </div>
        )}
        <div ref={contentRef} className="cf-sheet__content">
          {children}
        </div>
      </div>
    </div>
  );

  return createPortal(node, container ?? document.body);
}

// packages/vue/src/bottomsheet/BottomSheet.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { useDrag } from '../composables/useDrag';
import {
  lockBodyScroll,
  trapFocus,
  unlockBodyScroll,
  type FocusTrap,
} from '../modal/dom';
import {
  nearestSnapIndex,
  resolveSnap,
  type BottomSheetProps,
} from './variants';

const props = withDefaults(defineProps<BottomSheetProps>(), {
  open: false,
  snapPoints: () => ['40%', '90%'],
  initialSnap: 0,
  showGrabber: true,
  maskClosable: true,
  closeOnEsc: true,
  mask: true,
  dismissible: true,
  to: 'body',
});

const emit = defineEmits<{
  (e: 'update:open', v: boolean): void;
  (e: 'close'): void;
  (e: 'snap-change', index: number): void;
}>();

const canRender = ref(false);
const panelRef = ref<HTMLDivElement | null>(null);
const grabberRef = ref<HTMLDivElement | null>(null);
const contentRef = ref<HTMLDivElement | null>(null);
const snapIndex = ref(props.initialSnap);
const dragHeight = ref<number | null>(null);   // override height during drag
const windowH = ref(0);

let trap: FocusTrap | null = null;

function close() {
  emit('update:open', false);
  emit('close');
}

function onKeyDown(e: KeyboardEvent) {
  if (e.key === 'Escape' && props.closeOnEsc) {
    e.stopPropagation();
    close();
  }
}

onMounted(() => {
  canRender.value = true;
  if (typeof window !== 'undefined') windowH.value = window.innerHeight;
});

watch(
  [() => props.open, canRender],
  async ([open, ready]) => {
    if (open && ready) {
      windowH.value = window.innerHeight;
      snapIndex.value = props.initialSnap;
      dragHeight.value = null;
      if (props.mask) lockBodyScroll();
      await nextTick();
      if (panelRef.value) trap = trapFocus(panelRef.value);
      window.addEventListener('keydown', onKeyDown, true);
    } else if (!open) {
      trap?.release();
      trap = null;
      if (props.mask) unlockBodyScroll();
      if (typeof window !== 'undefined') window.removeEventListener('keydown', onKeyDown, true);
    }
  },
);

onBeforeUnmount(() => {
  if (props.open) {
    trap?.release();
    if (props.mask) unlockBodyScroll();
    if (typeof window !== 'undefined') window.removeEventListener('keydown', onKeyDown, true);
  }
});

/* snap math */
const snapHeights = computed(() => {
  const wh = windowH.value || 800;
  const ch = contentRef.value?.scrollHeight ?? 400;
  return props.snapPoints.map((s) => resolveSnap(s, wh, ch));
});

const targetHeight = computed(() => {
  const heights = snapHeights.value;
  if (heights.length === 0) return 200;
  return heights[Math.max(0, Math.min(snapIndex.value, heights.length - 1))];
});

const currentHeight = computed(() => dragHeight.value ?? targetHeight.value);

const panelStyle = computed(() => ({
  height: `${currentHeight.value}px`,
  transition: dragHeight.value !== null ? 'none' : undefined,
}));

/* drag grabber for snap navigation + dismiss */
useDrag(grabberRef, {
  axis: 'y',
  onMove(s) {
    const base = targetHeight.value;
    dragHeight.value = Math.max(0, base - s.dy);
  },
  onEnd(s) {
    const heights = snapHeights.value;
    if (heights.length === 0) {
      dragHeight.value = null;
      return;
    }
    const released = currentHeight.value;
    const smallest = heights[0];
    const fastDown = s.vy > 0.5;
    // close: dragged below 1/3 of smallest snap, or fast downward fling
    if (props.dismissible && (released < smallest * 0.5 || fastDown)) {
      dragHeight.value = null;
      close();
      return;
    }
    const idx = nearestSnapIndex(heights, released);
    dragHeight.value = null;
    if (idx !== snapIndex.value) {
      snapIndex.value = idx;
      emit('snap-change', idx);
    }
  },
});

function onOverlayClick(e: MouseEvent) {
  if (!props.maskClosable) return;
  if (e.target === e.currentTarget) close();
}

defineExpose({ close, snapTo(i: number) { snapIndex.value = i; } });
</script>

<template>
  <Teleport v-if="canRender" :to="to">
    <Transition name="cf-sheet" appear>
      <div
        v-if="open"
        class="cf-sheet__overlay"
        :class="!mask && 'cf-sheet__overlay--no-mask'"
        :style="{ zIndex: zIndex ?? 'var(--z-bottomsheet)' }"
        role="presentation"
        @click="onOverlayClick"
      >
        <div
          ref="panelRef"
          class="cf-sheet__panel"
          :style="panelStyle"
          role="dialog"
          aria-modal="true"
          tabindex="-1"
        >
          <div
            v-if="showGrabber"
            ref="grabberRef"
            class="cf-sheet__grabber"
            aria-hidden="true"
          >
            <span class="cf-sheet__grabber-bar" />
          </div>
          <div v-if="title" class="cf-sheet__header">
            <h2 class="cf-sheet__title">{{ title }}</h2>
          </div>
          <div ref="contentRef" class="cf-sheet__content">
            <slot />
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>
