// packages/vue/src/filterpanel/FilterPanel.vue
<script setup lang="ts">
import type { FilterPanelProps, SavedView } from './variants';

const props = withDefaults(defineProps<FilterPanelProps>(), {
  title: '筛选',
  showFooter: true,
  applying: false,
});

const emit = defineEmits<{
  (e: 'view-change', id: string, view: SavedView): void;
  (e: 'apply'): void;
  (e: 'reset'): void;
}>();

function onViewClick(view: SavedView) {
  if (view.id === props.activeViewId) return;
  emit('view-change', view.id, view);
}
</script>

<template>
  <aside class="cf-filterpanel" role="complementary" :aria-label="title">
    <header class="cf-filterpanel__head">
      <h3 class="cf-filterpanel__title">{{ title }}</h3>
      <span v-if="activeFilters" class="cf-filterpanel__badge">{{ activeFilters }}</span>
    </header>
    <div v-if="savedViews && savedViews.length" class="cf-filterpanel__views" role="tablist" aria-label="已保存视图">
      <button
        v-for="view in savedViews"
        :key="view.id"
        type="button"
        role="tab"
        class="cf-filterpanel__view"
        :class="view.id === activeViewId && 'is-active'"
        :aria-selected="view.id === activeViewId"
        @click="onViewClick(view)"
      >
        {{ view.label }}
        <span v-if="view.count != null" class="cf-filterpanel__view-count">{{ view.count }}</span>
      </button>
    </div>
    <div class="cf-filterpanel__body">
      <slot />
    </div>
    <footer v-if="showFooter" class="cf-filterpanel__foot">
      <button type="button" class="cf-filterpanel__btn cf-filterpanel__btn--secondary" @click="emit('reset')">清空</button>
      <button
        type="button"
        class="cf-filterpanel__btn cf-filterpanel__btn--primary"
        :disabled="applying"
        @click="emit('apply')"
      >{{ applying ? '应用中...' : '应用' }}</button>
    </footer>
  </aside>
</template>

// packages/react/src/filterpanel/FilterPanel.tsx
import type { FilterPanelProps, SavedView } from './variants';

export function FilterPanel(props: FilterPanelProps) {
  const {
    title = '筛选',
    savedViews,
    activeViewId,
    activeFilters,
    showFooter = true,
    applying = false,
    onViewChange,
    onApply,
    onReset,
    children,
  } = props;

  function onViewClick(view: SavedView) {
    if (view.id === activeViewId) return;
    onViewChange?.(view.id, view);
  }

  return (
    <aside className="cf-filterpanel" role="complementary" aria-label={title}>
      <header className="cf-filterpanel__head">
        <h3 className="cf-filterpanel__title">{title}</h3>
        {!!activeFilters && <span className="cf-filterpanel__badge">{activeFilters}</span>}
      </header>
      {savedViews && savedViews.length > 0 && (
        <div className="cf-filterpanel__views" role="tablist" aria-label="已保存视图">
          {savedViews.map((view) => (
            <button
              key={view.id}
              type="button"
              role="tab"
              className={['cf-filterpanel__view', view.id === activeViewId ? 'is-active' : ''].filter(Boolean).join(' ')}
              aria-selected={view.id === activeViewId}
              onClick={() => onViewClick(view)}
            >
              {view.label}
              {view.count != null && <span className="cf-filterpanel__view-count">{view.count}</span>}
            </button>
          ))}
        </div>
      )}
      <div className="cf-filterpanel__body">{children}</div>
      {showFooter && (
        <footer className="cf-filterpanel__foot">
          <button
            type="button"
            className="cf-filterpanel__btn cf-filterpanel__btn--secondary"
            onClick={() => onReset?.()}
          >
            清空
          </button>
          <button
            type="button"
            className="cf-filterpanel__btn cf-filterpanel__btn--primary"
            disabled={applying}
            onClick={() => onApply?.()}
          >
            {applying ? '应用中...' : '应用'}
          </button>
        </footer>
      )}
    </aside>
  );
}
