// packages/react/src/variableinput/VariableAwareInput.tsx
import { Fragment, useMemo, useRef } from 'react';
import {
  parseTokens,
  type VariableAwareInputProps,
} from './variants';

export function VariableAwareInput(props: VariableAwareInputProps) {
  const {
    value,
    onChange,
    variables,
    size = 'md',
    variant = 'outline',
    placeholder = '',
    disabled = false,
    error = false,
    className,
  } = props;

  const knownSet = useMemo(
    () => new Set((variables ?? []).map((item) => item.trim()).filter(Boolean)),
    [variables],
  );
  const tokens = useMemo(() => parseTokens(value, knownSet), [value, knownSet]);

  const inputRef = useRef<HTMLInputElement | null>(null);
  const overlayRef = useRef<HTMLDivElement | null>(null);

  const cls = [
    'cf-vinput',
    `cf-vinput--${size}`,
    `cf-vinput--${variant}`,
    disabled && 'is-disabled',
    error && 'is-error',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const onScroll = () => {
    if (overlayRef.current && inputRef.current) {
      overlayRef.current.scrollLeft = inputRef.current.scrollLeft;
    }
  };

  return (
    <div className={cls}>
      <div ref={overlayRef} className="cf-vinput__overlay" aria-hidden="true">
        {!value && placeholder ? (
          <span className="cf-vinput__placeholder">{placeholder}</span>
        ) : (
          tokens.map((tok, i) =>
            tok.type === 'text' ? (
              <span key={i} className="cf-vinput__plain">
                {tok.text}
              </span>
            ) : (
              <span
                key={i}
                className={[
                  'cf-vinput__var',
                  !tok.valid && 'is-invalid',
                ]
                  .filter(Boolean)
                  .join(' ')}
              >
                {tok.raw}
              </span>
            ),
          )
        )}
      </div>
      <input
        ref={inputRef}
        type="text"
        className="cf-vinput__input"
        value={value}
        disabled={disabled}
        spellCheck={false}
        autoComplete="off"
        onChange={(e) => onChange(e.target.value)}
        onScroll={onScroll}
      />
    </div>
  );
}

// packages/vue/src/variableinput/VariableAwareInput.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import {
  parseTokens,
  type VariableAwareInputProps,
} from './variants';

const props = withDefaults(defineProps<VariableAwareInputProps>(), {
  modelValue: '',
  size: 'md',
  variant: 'outline',
  placeholder: '',
  disabled: false,
  error: false,
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void;
}>();

const knownSet = computed(() => new Set((props.variables ?? []).map((item) => item.trim()).filter(Boolean)));
const tokens = computed(() => parseTokens(props.modelValue, knownSet.value));

const inputRef = ref<HTMLInputElement | null>(null);
const overlayRef = ref<HTMLDivElement | null>(null);

const cls = computed(() => [
  'cf-vinput',
  `cf-vinput--${props.size}`,
  `cf-vinput--${props.variant}`,
  props.disabled && 'is-disabled',
  props.error && 'is-error',
]);

function onInput(e: Event) {
  emit('update:modelValue', (e.target as HTMLInputElement).value);
}

function onScroll() {
  if (!overlayRef.value || !inputRef.value) return;
  overlayRef.value.scrollLeft = inputRef.value.scrollLeft;
}
</script>

<template>
  <div :class="cls">
    <div ref="overlayRef" class="cf-vinput__overlay" aria-hidden="true">
      <template v-if="!modelValue && placeholder">
        <span class="cf-vinput__placeholder">{{ placeholder }}</span>
      </template>
      <template v-else>
        <template v-for="(tok, i) in tokens" :key="i">
          <span v-if="tok.type === 'text'" class="cf-vinput__plain">{{
            tok.text
          }}</span>
          <span
            v-else
            class="cf-vinput__var"
            :class="{ 'is-invalid': !tok.valid }"
          >{{ tok.raw }}</span>
        </template>
      </template>
    </div>
    <input
      ref="inputRef"
      type="text"
      class="cf-vinput__input"
      :value="modelValue"
      :disabled="disabled"
      spellcheck="false"
      autocomplete="off"
      @input="onInput"
      @scroll="onScroll"
    />
  </div>
</template>
