// packages/vue/src/liquidfill/LiquidFill.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import type { LiquidFillProps } from './variants';

const props = withDefaults(defineProps<LiquidFillProps>(), {
  width: 240,
  height: 240,
  amplitude: 6,
  wavelength: 0.6,
  speed: 0.4,
  waves: 2,
  shape: 'circle',
});

const phase = ref(0);
let rafId: number | null = null;
let last = 0;
let reduced = false;

function tick(t: number) {
  if (!last) last = t;
  const dt = (t - last) / 1000;
  last = t;
  if (!reduced && props.speed > 0) {
    phase.value = (phase.value + props.speed * dt) % 1;
  }
  rafId = requestAnimationFrame(tick);
}

onMounted(() => {
  if (typeof window !== 'undefined' && window.matchMedia) {
    reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  }
  rafId = requestAnimationFrame(tick);
});

onBeforeUnmount(() => {
  if (rafId !== null) cancelAnimationFrame(rafId);
  rafId = null;
});

const uid = Math.random().toString(36).slice(2, 9);
const clipId = `cflq-${uid}`;

function buildWavePath(p: number, layer: number, value: number, w: number, h: number) {
  const amp = props.amplitude * (1 - layer * 0.25);
  const wl = w * props.wavelength;
  const yLevel = h * (1 - Math.max(0, Math.min(1, value)));
  const step = 4;
  const offset = (p + layer * 0.33) * wl * 2;
  let d = `M ${-amp} ${h}`;
  d += ` L ${-amp} ${yLevel}`;
  for (let x = -amp; x <= w + amp; x += step) {
    const phase = ((x + offset) / wl) * Math.PI * 2;
    const y = yLevel + Math.sin(phase) * amp;
    d += ` L ${x.toFixed(2)} ${y.toFixed(2)}`;
  }
  d += ` L ${w + amp} ${h} Z`;
  return d;
}

const layout = computed(() => {
  const w = props.width;
  const h = props.height;
  const cx = w / 2;
  const cy = h / 2;
  const value = Math.max(0, Math.min(1, props.value));
  const layers = Array.from({ length: Math.max(1, Math.min(3, props.waves)) }, (_, i) => ({
    d: buildWavePath(phase.value, i, value, w, h),
    opacity: 0.85 - i * 0.22,
  }));
  return {
    cx,
    cy,
    radius: Math.min(w, h) / 2 - 4,
    value,
    layers,
    label: props.label ?? `${Math.round(value * 100)}%`,
  };
});
</script>

<template>
  <svg
    class="cf-chart cf-liquidfill"
    :viewBox="`0 0 ${width} ${height}`"
    :width="width"
    :height="height"
    role="img"
    :aria-label="ariaLabel ?? `液体填充 ${Math.round(layout.value * 100)}%`"
  >
    <defs>
      <clipPath :id="clipId">
        <circle
          v-if="shape === 'circle'"
          :cx="layout.cx"
          :cy="layout.cy"
          :r="layout.radius"
        />
        <rect v-else x="2" y="2" :width="width - 4" :height="height - 4" rx="8" />
      </clipPath>
    </defs>
    <circle
      v-if="shape === 'circle'"
      class="cf-liquidfill__rim"
      :cx="layout.cx"
      :cy="layout.cy"
      :r="layout.radius"
    />
    <rect
      v-else
      class="cf-liquidfill__rim"
      x="2"
      y="2"
      :width="width - 4"
      :height="height - 4"
      rx="8"
    />
    <g :clip-path="`url(#${clipId})`">
      <rect
        class="cf-liquidfill__bg"
        x="0"
        y="0"
        :width="width"
        :height="height"
      />
      <path
        v-for="(wave, i) in layout.layers"
        :key="i"
        class="cf-liquidfill__wave"
        :class="`cf-liquidfill__wave--${i}`"
        :d="wave.d"
        :style="{ opacity: wave.opacity }"
      />
    </g>
    <text
      :x="layout.cx"
      :y="layout.cy + 6"
      text-anchor="middle"
      class="cf-liquidfill__label"
    >{{ layout.label }}</text>
  </svg>
</template>

// packages/react/src/liquidfill/LiquidFill.tsx
import { useEffect, useId, useMemo, useRef, useState } from 'react';
import type { LiquidFillProps } from './variants';

export function LiquidFill(props: LiquidFillProps) {
  const {
    value,
    width = 240,
    height = 240,
    amplitude = 6,
    wavelength = 0.6,
    speed = 0.4,
    waves = 2,
    shape = 'circle',
    label,
    ariaLabel,
    className,
  } = props;

  const [phase, setPhase] = useState(0);
  const lastRef = useRef(0);
  const rafRef = useRef<number | null>(null);
  const reducedRef = useRef(false);
  const speedRef = useRef(speed);
  speedRef.current = speed;

  useEffect(() => {
    if (typeof window !== 'undefined' && window.matchMedia) {
      reducedRef.current = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    }
    const tick = (t: number) => {
      if (!lastRef.current) lastRef.current = t;
      const dt = (t - lastRef.current) / 1000;
      lastRef.current = t;
      if (!reducedRef.current && speedRef.current > 0) {
        setPhase((p) => (p + speedRef.current * dt) % 1);
      }
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => {
      if (rafRef.current !== null) cancelAnimationFrame(rafRef.current);
      lastRef.current = 0;
    };
  }, []);

  const uid = useId().replace(/:/g, '');
  const clipId = `cflq-${uid}`;

  const clamped = Math.max(0, Math.min(1, value));
  const cx = width / 2;
  const cy = height / 2;
  const radius = Math.min(width, height) / 2 - 4;

  const layers = useMemo(() => {
    const out: { d: string; opacity: number }[] = [];
    const n = Math.max(1, Math.min(3, waves));
    const wl = width * wavelength;
    const yLevel = height * (1 - clamped);
    const step = 4;
    for (let layer = 0; layer < n; layer++) {
      const amp = amplitude * (1 - layer * 0.25);
      const offset = (phase + layer * 0.33) * wl * 2;
      let d = `M ${-amp} ${height}`;
      d += ` L ${-amp} ${yLevel}`;
      for (let x = -amp; x <= width + amp; x += step) {
        const ph = ((x + offset) / wl) * Math.PI * 2;
        const y = yLevel + Math.sin(ph) * amp;
        d += ` L ${x.toFixed(2)} ${y.toFixed(2)}`;
      }
      d += ` L ${width + amp} ${height} Z`;
      out.push({ d, opacity: 0.85 - layer * 0.22 });
    }
    return out;
  }, [phase, waves, amplitude, wavelength, clamped, width, height]);

  const text = label ?? `${Math.round(clamped * 100)}%`;

  return (
    <svg
      className={['cf-chart cf-liquidfill', className].filter(Boolean).join(' ')}
      viewBox={`0 0 ${width} ${height}`}
      width={width}
      height={height}
      role="img"
      aria-label={ariaLabel ?? `液体填充 ${Math.round(clamped * 100)}%`}
    >
      <defs>
        <clipPath id={clipId}>
          {shape === 'circle' ? (
            <circle cx={cx} cy={cy} r={radius} />
          ) : (
            <rect x={2} y={2} width={width - 4} height={height - 4} rx={8} />
          )}
        </clipPath>
      </defs>
      {shape === 'circle' ? (
        <circle className="cf-liquidfill__rim" cx={cx} cy={cy} r={radius} />
      ) : (
        <rect className="cf-liquidfill__rim" x={2} y={2} width={width - 4} height={height - 4} rx={8} />
      )}
      <g clipPath={`url(#${clipId})`}>
        <rect className="cf-liquidfill__bg" x={0} y={0} width={width} height={height} />
        {layers.map((wave, i) => (
          <path
            key={i}
            className={`cf-liquidfill__wave cf-liquidfill__wave--${i}`}
            d={wave.d}
            style={{ opacity: wave.opacity }}
          />
        ))}
      </g>
      <text x={cx} y={cy + 6} textAnchor="middle" className="cf-liquidfill__label">
        {text}
      </text>
    </svg>
  );
}
