// packages/react/src/ansitext/AnsiText.tsx
import { useMemo } from 'react';
import { parseAnsi, spanClass, type AnsiTextProps } from './variants';

export function AnsiText(props: AnsiTextProps) {
  const {
    text,
    size = 'md',
    wrap = true,
    preserveWhitespace = true,
    className,
  } = props;

  const spans = useMemo(() => parseAnsi(text), [text]);

  const cls = [
    'cf-ansi',
    `cf-ansi--${size}`,
    wrap && 'is-wrap',
    preserveWhitespace && 'is-pre',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <pre className={cls}>
      {spans.map((span, i) => (
        <span key={i} className={spanClass(span)}>
          {span.text}
        </span>
      ))}
    </pre>
  );
}

// packages/vue/src/ansitext/AnsiText.vue
<script setup lang="ts">
import { computed } from 'vue';
import { parseAnsi, spanClass, type AnsiTextProps } from './variants';

const props = withDefaults(defineProps<AnsiTextProps>(), {
  size: 'md',
  wrap: true,
  preserveWhitespace: true,
});

const spans = computed(() => parseAnsi(props.text));

const cls = computed(() => [
  'cf-ansi',
  `cf-ansi--${props.size}`,
  props.wrap && 'is-wrap',
  props.preserveWhitespace && 'is-pre',
]);
</script>

<template>
  <pre :class="cls"><span
    v-for="(span, i) in spans"
    :key="i"
    :class="spanClass(span)"
  >{{ span.text }}</span></pre>
</template>
