// packages/vue/src/regexbuilder/RegexBuilder.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  ALL_FLAGS,
  compileAndMatch,
  highlightMatches,
  type RegexBuilderProps,
  type RegexFlag,
} from './variants';

const props = withDefaults(defineProps<RegexBuilderProps>(), {
  pattern: '',
  flags: 'g',
  testText: '',
  size: 'md',
  patternPlaceholder: '正则表达式',
  testPlaceholder: '在此粘贴待测试文本…',
});

const emit = defineEmits<{
  (e: 'update:pattern', value: string): void;
  (e: 'update:flags', value: string): void;
  (e: 'update:testText', value: string): void;
}>();

const result = computed(() =>
  compileAndMatch(props.pattern, props.flags, props.testText),
);

const highlighted = computed(() =>
  highlightMatches(props.testText, result.value.matches).parts,
);

const cls = computed(() => [
  'cf-regex',
  `cf-regex--${props.size}`,
  !result.value.ok && 'is-error',
]);

function toggleFlag(flag: RegexFlag) {
  const cur = props.flags;
  const next = cur.includes(flag)
    ? cur.replace(flag, '')
    : cur + flag;
  emit('update:flags', next);
}
</script>

<template>
  <div :class="cls">
    <div class="cf-regex__pattern">
      <span class="cf-regex__delim">/</span>
      <input
        type="text"
        class="cf-regex__pattern-input"
        :value="pattern"
        :placeholder="patternPlaceholder"
        spellcheck="false"
        autocomplete="off"
        @input="(e) => emit('update:pattern', (e.target as HTMLInputElement).value)"
      />
      <span class="cf-regex__delim">/</span>
      <span class="cf-regex__flags-text">{{ flags }}</span>
    </div>
    <div class="cf-regex__flags" role="group" aria-label="正则标志">
      <button
        v-for="f in ALL_FLAGS"
        :key="f.flag"
        type="button"
        class="cf-regex__flag"
        :title="f.desc"
        :aria-pressed="flags.includes(f.flag)"
        @click="toggleFlag(f.flag)"
      >
        {{ f.label }}
      </button>
    </div>
    <div v-if="!result.ok" class="cf-regex__error">
      <strong>正则编译错误：</strong>{{ result.error }}
    </div>
    <textarea
      class="cf-regex__test"
      :value="testText"
      :placeholder="testPlaceholder"
      rows="6"
      spellcheck="false"
      @input="(e) => emit('update:testText', (e.target as HTMLTextAreaElement).value)"
    />
    <div class="cf-regex__output">
      <div class="cf-regex__output-head">
        匹配 <strong>{{ result.matches.length }}</strong> 处
      </div>
      <div class="cf-regex__output-body">
        <template v-for="(p, i) in highlighted" :key="i">
          <span v-if="p.match" class="cf-regex__hit">{{ p.text }}</span>
          <span v-else>{{ p.text }}</span>
        </template>
      </div>
    </div>
  </div>
</template>

// packages/react/src/regexbuilder/RegexBuilder.tsx
import { Fragment, useMemo } from 'react';
import {
  ALL_FLAGS,
  compileAndMatch,
  highlightMatches,
  type RegexBuilderProps,
  type RegexFlag,
} from './variants';

export function RegexBuilder(props: RegexBuilderProps) {
  const {
    pattern,
    onPatternChange,
    flags,
    onFlagsChange,
    testText,
    onTestTextChange,
    size = 'md',
    patternPlaceholder = '正则表达式',
    testPlaceholder = '在此粘贴待测试文本…',
    className,
  } = props;

  const result = useMemo(
    () => compileAndMatch(pattern, flags, testText),
    [pattern, flags, testText],
  );
  const highlighted = useMemo(
    () => highlightMatches(testText, result.matches),
    [testText, result.matches],
  );

  const cls = [
    'cf-regex',
    `cf-regex--${size}`,
    !result.ok && 'is-error',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const toggleFlag = (flag: RegexFlag) => {
    const next = flags.includes(flag) ? flags.replace(flag, '') : flags + flag;
    onFlagsChange(next);
  };

  return (
    <div className={cls}>
      <div className="cf-regex__pattern">
        <span className="cf-regex__delim">/</span>
        <input
          type="text"
          className="cf-regex__pattern-input"
          value={pattern}
          placeholder={patternPlaceholder}
          spellCheck={false}
          autoComplete="off"
          onChange={(e) => onPatternChange(e.target.value)}
        />
        <span className="cf-regex__delim">/</span>
        <span className="cf-regex__flags-text">{flags}</span>
      </div>
      <div className="cf-regex__flags" role="group" aria-label="正则标志">
        {ALL_FLAGS.map((f) => (
          <button
            key={f.flag}
            type="button"
            className="cf-regex__flag"
            title={f.desc}
            aria-pressed={flags.includes(f.flag)}
            onClick={() => toggleFlag(f.flag)}
          >
            {f.label}
          </button>
        ))}
      </div>
      {!result.ok ? (
        <div className="cf-regex__error">
          <strong>正则编译错误：</strong>
          {result.error}
        </div>
      ) : null}
      <textarea
        className="cf-regex__test"
        value={testText}
        placeholder={testPlaceholder}
        rows={6}
        spellCheck={false}
        onChange={(e) => onTestTextChange(e.target.value)}
      />
      <div className="cf-regex__output">
        <div className="cf-regex__output-head">
          匹配 <strong>{result.matches.length}</strong> 处
        </div>
        <div className="cf-regex__output-body">
          {highlighted.map((p, i) =>
            p.match ? (
              <span key={i} className="cf-regex__hit">
                {p.text}
              </span>
            ) : (
              <Fragment key={i}>{p.text}</Fragment>
            ),
          )}
        </div>
      </div>
    </div>
  );
}
