// packages/vue/src/streamingtext/StreamingText.vue
<script setup lang="ts">
import { computed } from 'vue';
import { renderInlineMarkdown, type StreamingTextProps } from './variants';

const props = withDefaults(defineProps<StreamingTextProps>(), {
  done: false,
  format: 'text',
  cursor: 'blink',
});

const rendered = computed(() =>
  props.format === 'markdown' ? renderInlineMarkdown(props.text) : null,
);

const cursorClass = computed(() => {
  if (props.done || props.cursor === 'none') return '';
  return props.cursor === 'block' ? 'cf-streaming__cursor cf-streaming__cursor--block' : 'cf-streaming__cursor';
});
</script>

<template>
  <span :class="['cf-streaming', className]" aria-live="polite" aria-atomic="false">
    <span v-if="format === 'markdown'" class="cf-streaming__body" v-html="rendered" />
    <span v-else class="cf-streaming__body">{{ text }}</span>
    <span v-if="!done && cursor !== 'none'" :class="cursorClass" aria-hidden="true" />
  </span>
</template>

// packages/react/src/streamingtext/StreamingText.tsx
import { useMemo } from 'react';
import { renderInlineMarkdown, type StreamingTextProps } from './variants';

export function StreamingText(props: StreamingTextProps) {
  const { text, done = false, format = 'text', cursor = 'blink', className } = props;

  const html = useMemo(
    () => (format === 'markdown' ? renderInlineMarkdown(text) : null),
    [format, text],
  );

  const cursorClass =
    done || cursor === 'none'
      ? ''
      : cursor === 'block'
        ? 'cf-streaming__cursor cf-streaming__cursor--block'
        : 'cf-streaming__cursor';

  return (
    <span className={['cf-streaming', className].filter(Boolean).join(' ')} aria-live="polite" aria-atomic="false">
      {format === 'markdown' ? (
        <span className="cf-streaming__body" dangerouslySetInnerHTML={{ __html: html ?? '' }} />
      ) : (
        <span className="cf-streaming__body">{text}</span>
      )}
      {!done && cursor !== 'none' && <span className={cursorClass} aria-hidden />}
    </span>
  );
}
