// packages/vue/src/mention/Mention.vue
<script setup lang="ts">
import { computed, nextTick, ref } from 'vue';
import {
  applyMention,
  filterOptions,
  findTrigger,
  mentionClass,
  type MentionOption,
  type MentionProps,
  type TriggerMatch,
} from './variants';

const props = withDefaults(defineProps<MentionProps>(), {
  defaultValue: '',
  trigger: '@',
  placeholder: '输入 @ 触发提及',
  size: 'md',
  rows: 4,
  disabled: false,
  readonly: false,
});

const emit = defineEmits<{
  'update:modelValue': [value: string];
  select: [option: MentionOption];
}>();

const isControlled = computed(() => props.modelValue !== undefined);
const internal = ref(props.defaultValue);
const text = computed(() => (isControlled.value ? props.modelValue ?? '' : internal.value));

const ta = ref<HTMLTextAreaElement | null>(null);
const match = ref<TriggerMatch | null>(null);
const active = ref(0);

const matches = computed<MentionOption[]>(() =>
  match.value ? filterOptions(props.options, match.value.query) : [],
);
const open = computed(() => match.value !== null && matches.value.length > 0);

const cls = computed(() =>
  mentionClass({
    size: props.size,
    disabled: props.disabled,
    readonly: props.readonly,
    className: props.className,
  }),
);

function setText(next: string) {
  if (!isControlled.value) internal.value = next;
  emit('update:modelValue', next);
}

function recompute() {
  if (!ta.value) return;
  const caret = ta.value.selectionStart ?? 0;
  match.value = findTrigger(text.value, caret, props.trigger);
  active.value = 0;
}

function onInput(e: Event) {
  setText((e.target as HTMLTextAreaElement).value);
  nextTick(recompute);
}

function onKeyDown(e: KeyboardEvent) {
  if (!open.value) return;
  if (e.key === 'ArrowDown') {
    e.preventDefault();
    active.value = (active.value + 1) % matches.value.length;
  } else if (e.key === 'ArrowUp') {
    e.preventDefault();
    active.value = (active.value - 1 + matches.value.length) % matches.value.length;
  } else if (e.key === 'Enter' || e.key === 'Tab') {
    e.preventDefault();
    pick(matches.value[active.value]);
  } else if (e.key === 'Escape') {
    match.value = null;
  }
}

function pick(opt: MentionOption) {
  if (!opt || opt.disabled || !match.value || !ta.value) return;
  const caret = ta.value.selectionStart ?? 0;
  const { text: nextText, caret: nextCaret } = applyMention(
    text.value,
    match.value,
    caret,
    props.trigger,
    opt,
  );
  setText(nextText);
  emit('select', opt);
  match.value = null;
  nextTick(() => {
    if (!ta.value) return;
    ta.value.focus();
    ta.value.setSelectionRange(nextCaret, nextCaret);
  });
}
</script>

<template>
  <div :class="cls">
    <textarea
      ref="ta"
      class="cf-mention__input"
      :value="text"
      :rows="rows"
      :placeholder="placeholder"
      :disabled="disabled"
      :readonly="readonly"
      @input="onInput"
      @keydown="onKeyDown"
      @click="recompute"
      @keyup="recompute"
    />
    <div v-if="open" class="cf-mention__menu" role="listbox">
      <button
        v-for="(opt, i) in matches"
        :key="opt.value"
        type="button"
        :class="['cf-mention__item', i === active && 'is-active', opt.disabled && 'is-disabled']"
        :disabled="opt.disabled"
        @mousedown.prevent="pick(opt)"
        @mouseenter="active = i"
      >
        <span class="cf-mention__label">{{ opt.label ?? opt.value }}</span>
        <span v-if="opt.description" class="cf-mention__desc">{{ opt.description }}</span>
      </button>
    </div>
  </div>
</template>

// packages/react/src/mention/Mention.tsx
import {
  useEffect,
  useRef,
  useState,
  type ChangeEvent,
  type KeyboardEvent,
} from 'react';
import {
  applyMention,
  filterOptions,
  findTrigger,
  mentionClass,
  type MentionOption,
  type MentionProps,
  type TriggerMatch,
} from './variants';

export function Mention(props: MentionProps) {
  const {
    value,
    defaultValue = '',
    options,
    trigger = '@',
    placeholder = '输入 @ 触发提及',
    size = 'md',
    rows = 4,
    disabled = false,
    readonly = false,
    className,
    onChange,
    onSelect,
  } = props;

  const isControlled = value !== undefined;
  const [internal, setInternal] = useState(defaultValue);
  const text = isControlled ? (value as string) : internal;

  const ta = useRef<HTMLTextAreaElement | null>(null);
  const [match, setMatch] = useState<TriggerMatch | null>(null);
  const [active, setActive] = useState(0);
  const [pendingCaret, setPendingCaret] = useState<number | null>(null);

  const matches = match ? filterOptions(options, match.query) : [];
  const open = match !== null && matches.length > 0;

  useEffect(() => {
    if (pendingCaret == null || !ta.current) return;
    ta.current.focus();
    ta.current.setSelectionRange(pendingCaret, pendingCaret);
    setPendingCaret(null);
  }, [pendingCaret]);

  function setText(next: string) {
    if (!isControlled) setInternal(next);
    onChange?.(next);
  }

  function recompute() {
    if (!ta.current) return;
    const caret = ta.current.selectionStart ?? 0;
    setMatch(findTrigger(text, caret, trigger));
    setActive(0);
  }

  function onInput(e: ChangeEvent<HTMLTextAreaElement>) {
    setText(e.target.value);
    queueMicrotask(() => {
      if (!ta.current) return;
      const caret = ta.current.selectionStart ?? 0;
      setMatch(findTrigger(e.target.value, caret, trigger));
      setActive(0);
    });
  }

  function onKeyDown(e: KeyboardEvent<HTMLTextAreaElement>) {
    if (!open) return;
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setActive((a) => (a + 1) % matches.length);
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setActive((a) => (a - 1 + matches.length) % matches.length);
    } else if (e.key === 'Enter' || e.key === 'Tab') {
      e.preventDefault();
      pick(matches[active]);
    } else if (e.key === 'Escape') {
      setMatch(null);
    }
  }

  function pick(opt: MentionOption | undefined) {
    if (!opt || opt.disabled || !match || !ta.current) return;
    const caret = ta.current.selectionStart ?? 0;
    const { text: nextText, caret: nextCaret } = applyMention(text, match, caret, trigger, opt);
    setText(nextText);
    onSelect?.(opt);
    setMatch(null);
    setPendingCaret(nextCaret);
  }

  const cls = mentionClass({ size, disabled, readonly, className });

  return (
    <div className={cls}>
      <textarea
        ref={ta}
        className="cf-mention__input"
        value={text}
        rows={rows}
        placeholder={placeholder}
        disabled={disabled}
        readOnly={readonly}
        onChange={onInput}
        onKeyDown={onKeyDown}
        onClick={recompute}
        onKeyUp={recompute}
      />
      {open ? (
        <div className="cf-mention__menu" role="listbox">
          {matches.map((opt, i) => {
            const itemCls = [
              'cf-mention__item',
              i === active && 'is-active',
              opt.disabled && 'is-disabled',
            ]
              .filter(Boolean)
              .join(' ');
            return (
              <button
                key={opt.value}
                type="button"
                className={itemCls}
                disabled={opt.disabled}
                onMouseDown={(e) => {
                  e.preventDefault();
                  pick(opt);
                }}
                onMouseEnter={() => setActive(i)}
              >
                <span className="cf-mention__label">{opt.label ?? opt.value}</span>
                {opt.description ? (
                  <span className="cf-mention__desc">{opt.description}</span>
                ) : null}
              </button>
            );
          })}
        </div>
      ) : null}
    </div>
  );
}
