// packages/react/src/stat/Stat.tsx
import { statClass, trendDirection, type StatProps } from './variants';

export function Stat(props: StatProps) {
  const {
    label,
    value,
    hint,
    prefix,
    suffix,
    variant = 'default',
    size = 'md',
    trend,
    loading = false,
    leading,
    trailing,
    footer,
    className,
  } = props;

  const dir = trendDirection(trend);

  return (
    <div className={statClass({ variant, size, loading, className })}>
      <div className="cf-stat__head">
        {leading}
        <span className="cf-stat__label">{label}</span>
        {trailing ? <span className="cf-stat__trailing">{trailing}</span> : null}
      </div>

      <div className="cf-stat__value">
        {prefix ? <span className="cf-stat__prefix">{prefix}</span> : null}
        <span className="cf-stat__number">{value}</span>
        {suffix ? <span className="cf-stat__suffix">{suffix}</span> : null}
      </div>

      {trend || hint || footer ? (
        <div className="cf-stat__foot">
          {trend ? (
            <span className={`cf-stat__trend cf-stat__trend--${dir}`}>
              {dir === 'up' ? (
                <svg viewBox="0 0 12 12" fill="currentColor" aria-hidden="true" className="cf-stat__trend-icon">
                  <path d="M2 8l4-4 4 4H2z" />
                </svg>
              ) : dir === 'down' ? (
                <svg viewBox="0 0 12 12" fill="currentColor" aria-hidden="true" className="cf-stat__trend-icon">
                  <path d="M2 4l4 4 4-4H2z" />
                </svg>
              ) : (
                <svg viewBox="0 0 12 12" fill="currentColor" aria-hidden="true" className="cf-stat__trend-icon">
                  <rect x="2" y="5" width="8" height="2" />
                </svg>
              )}
              <span className="cf-stat__trend-delta">{trend.delta}</span>
              {trend.label ? <span className="cf-stat__trend-label">{trend.label}</span> : null}
            </span>
          ) : null}
          {hint ? <span className="cf-stat__hint">{hint}</span> : null}
          {footer}
        </div>
      ) : null}
    </div>
  );
}

// packages/vue/src/stat/Stat.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  statClass,
  trendDirection,
  type StatProps,
} from './variants';

const props = withDefaults(defineProps<StatProps>(), {
  variant: 'default',
  size: 'md',
  loading: false,
});

const cls = computed(() =>
  statClass({
    variant: props.variant,
    size: props.size,
    loading: props.loading,
  }),
);

const dir = computed(() => trendDirection(props.trend));
</script>

<template>
  <div :class="cls">
    <div class="cf-stat__head">
      <slot name="leading" />
      <span class="cf-stat__label">{{ label }}</span>
      <span v-if="$slots.trailing" class="cf-stat__trailing">
        <slot name="trailing" />
      </span>
    </div>

    <div class="cf-stat__value">
      <span v-if="prefix" class="cf-stat__prefix">{{ prefix }}</span>
      <span class="cf-stat__number">
        <slot name="value">{{ value }}</slot>
      </span>
      <span v-if="suffix" class="cf-stat__suffix">{{ suffix }}</span>
    </div>

    <div v-if="trend || hint || $slots.footer" class="cf-stat__foot">
      <span
        v-if="trend"
        class="cf-stat__trend"
        :class="`cf-stat__trend--${dir}`"
      >
        <svg
          v-if="dir === 'up'"
          viewBox="0 0 12 12"
          fill="currentColor"
          aria-hidden="true"
          class="cf-stat__trend-icon"
        ><path d="M2 8l4-4 4 4H2z"/></svg>
        <svg
          v-else-if="dir === 'down'"
          viewBox="0 0 12 12"
          fill="currentColor"
          aria-hidden="true"
          class="cf-stat__trend-icon"
        ><path d="M2 4l4 4 4-4H2z"/></svg>
        <svg
          v-else
          viewBox="0 0 12 12"
          fill="currentColor"
          aria-hidden="true"
          class="cf-stat__trend-icon"
        ><rect x="2" y="5" width="8" height="2"/></svg>
        <span class="cf-stat__trend-delta">{{ trend.delta }}</span>
        <span v-if="trend.label" class="cf-stat__trend-label">{{ trend.label }}</span>
      </span>
      <span v-if="hint" class="cf-stat__hint">{{ hint }}</span>
      <slot name="footer" />
    </div>
  </div>
</template>
