// packages/vue/src/signaturepad/SignaturePad.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import type { SignaturePoint } from './variants';

const props = withDefaults(
  defineProps<{
    width?: number | string;
    height?: number | string;
    strokeWidth?: number;
    strokeColor?: string;
    background?: string;
    disabled?: boolean;
  }>(),
  {
    width: '100%',
    height: 180,
    strokeWidth: 2,
    background: 'transparent',
  },
);

const emit = defineEmits<{
  (e: 'change', empty: boolean): void;
  (e: 'start'): void;
  (e: 'end'): void;
}>();

const canvas = ref<HTMLCanvasElement | null>(null);
let ctx: CanvasRenderingContext2D | null = null;
let dpr = 1;
let drawing = false;
let pointerId = -1;
let stroke: SignaturePoint[] = [];
let lastEmpty = true;

function getStrokeColor(): string {
  if (props.strokeColor) return props.strokeColor;
  if (canvas.value) {
    return getComputedStyle(canvas.value).getPropertyValue('color') || '#fff';
  }
  return '#fff';
}

function resize() {
  const el = canvas.value;
  if (!el) return;
  dpr = window.devicePixelRatio || 1;
  const rect = el.getBoundingClientRect();
  el.width = Math.max(1, Math.round(rect.width * dpr));
  el.height = Math.max(1, Math.round(rect.height * dpr));
  if (ctx) ctx.setTransform(1, 0, 0, 1, 0, 0);
  ctx = el.getContext('2d');
  if (!ctx) return;
  ctx.scale(dpr, dpr);
  ctx.lineCap = 'round';
  ctx.lineJoin = 'round';
}

function pointFromEvent(ev: PointerEvent): SignaturePoint {
  const rect = canvas.value!.getBoundingClientRect();
  return { x: ev.clientX - rect.left, y: ev.clientY - rect.top };
}

function onDown(ev: PointerEvent) {
  if (props.disabled || !canvas.value || !ctx) return;
  if (ev.button !== undefined && ev.button !== 0) return;
  drawing = true;
  pointerId = ev.pointerId;
  try {
    canvas.value.setPointerCapture(ev.pointerId);
  } catch {}
  stroke = [pointFromEvent(ev)];
  ctx.strokeStyle = getStrokeColor();
  ctx.lineWidth = props.strokeWidth;
  ctx.beginPath();
  ctx.moveTo(stroke[0].x, stroke[0].y);
  emit('start');
}

function onMove(ev: PointerEvent) {
  if (!drawing || ev.pointerId !== pointerId || !ctx) return;
  const p = pointFromEvent(ev);
  const last = stroke[stroke.length - 1];
  const mid = { x: (last.x + p.x) / 2, y: (last.y + p.y) / 2 };
  ctx.quadraticCurveTo(last.x, last.y, mid.x, mid.y);
  ctx.stroke();
  ctx.beginPath();
  ctx.moveTo(mid.x, mid.y);
  stroke.push(p);
}

function onUp(ev: PointerEvent) {
  if (!drawing || ev.pointerId !== pointerId || !ctx) return;
  drawing = false;
  if (stroke.length > 0) {
    const last = stroke[stroke.length - 1];
    ctx.lineTo(last.x, last.y);
    ctx.stroke();
  } else if (stroke.length === 1) {
    const p = stroke[0];
    ctx.beginPath();
    ctx.arc(p.x, p.y, props.strokeWidth / 2, 0, Math.PI * 2);
    ctx.fillStyle = getStrokeColor();
    ctx.fill();
  }
  stroke = [];
  try {
    canvas.value?.releasePointerCapture(ev.pointerId);
  } catch {}
  lastEmpty = false;
  emit('end');
  emit('change', false);
}

function clear() {
  if (!ctx || !canvas.value) return;
  ctx.save();
  ctx.setTransform(1, 0, 0, 1, 0, 0);
  ctx.clearRect(0, 0, canvas.value.width, canvas.value.height);
  ctx.restore();
  lastEmpty = true;
  emit('change', true);
}

function toDataURL(type = 'image/png', quality?: number): string {
  if (!canvas.value) return '';
  return canvas.value.toDataURL(type, quality);
}

function toBlob(type = 'image/png', quality?: number): Promise<Blob | null> {
  return new Promise((resolve) => {
    if (!canvas.value) return resolve(null);
    canvas.value.toBlob(resolve, type, quality);
  });
}

function isEmpty(): boolean {
  return lastEmpty;
}

defineExpose({ clear, toDataURL, toBlob, isEmpty });

onMounted(() => {
  resize();
  window.addEventListener('resize', resize);
});
onBeforeUnmount(() => {
  window.removeEventListener('resize', resize);
});

watch(() => [props.width, props.height], resize, { flush: 'post' });

const style = computed(() => ({
  width: typeof props.width === 'number' ? `${props.width}px` : props.width,
  height: typeof props.height === 'number' ? `${props.height}px` : props.height,
  background: props.background,
}));

const rootClass = computed(() => [
  'cf-signpad',
  props.disabled && 'is-disabled',
]);
</script>

<template>
  <div :class="rootClass" :style="style">
    <canvas
      ref="canvas"
      class="cf-signpad__canvas"
      @pointerdown="onDown"
      @pointermove="onMove"
      @pointerup="onUp"
      @pointercancel="onUp"
    />
  </div>
</template>

// packages/react/src/signaturepad/SignaturePad.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useRef,
  type CSSProperties,
} from 'react';

export interface SignaturePoint {
  x: number;
  y: number;
}

export interface SignaturePadHandle {
  clear: () => void;
  toDataURL: (type?: string, quality?: number) => string;
  toBlob: (type?: string, quality?: number) => Promise<Blob | null>;
  isEmpty: () => boolean;
}

export interface SignaturePadProps {
  width?: number | string;
  height?: number | string;
  strokeWidth?: number;
  strokeColor?: string;
  background?: string;
  disabled?: boolean;
  className?: string;
  onChange?: (empty: boolean) => void;
  onStart?: () => void;
  onEnd?: () => void;
}

export const SignaturePad = forwardRef<SignaturePadHandle, SignaturePadProps>(function SignaturePad(
  {
    width = '100%',
    height = 180,
    strokeWidth = 2,
    strokeColor,
    background = 'transparent',
    disabled,
    className,
    onChange,
    onStart,
    onEnd,
  },
  ref,
) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const ctxRef = useRef<CanvasRenderingContext2D | null>(null);
  const drawingRef = useRef(false);
  const pointerIdRef = useRef(-1);
  const strokeRef = useRef<SignaturePoint[]>([]);
  const emptyRef = useRef(true);

  const getStroke = useCallback((): string => {
    if (strokeColor) return strokeColor;
    if (canvasRef.current) {
      return getComputedStyle(canvasRef.current).getPropertyValue('color') || '#fff';
    }
    return '#fff';
  }, [strokeColor]);

  const resize = useCallback(() => {
    const el = canvasRef.current;
    if (!el) return;
    const dpr = window.devicePixelRatio || 1;
    const rect = el.getBoundingClientRect();
    el.width = Math.max(1, Math.round(rect.width * dpr));
    el.height = Math.max(1, Math.round(rect.height * dpr));
    const ctx = el.getContext('2d');
    if (!ctx) return;
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.scale(dpr, dpr);
    ctx.lineCap = 'round';
    ctx.lineJoin = 'round';
    ctxRef.current = ctx;
  }, []);

  useEffect(() => {
    resize();
    window.addEventListener('resize', resize);
    return () => window.removeEventListener('resize', resize);
  }, [resize]);

  useImperativeHandle(
    ref,
    (): SignaturePadHandle => ({
      clear: () => {
        const ctx = ctxRef.current;
        const el = canvasRef.current;
        if (!ctx || !el) return;
        ctx.save();
        ctx.setTransform(1, 0, 0, 1, 0, 0);
        ctx.clearRect(0, 0, el.width, el.height);
        ctx.restore();
        emptyRef.current = true;
        onChange?.(true);
      },
      toDataURL: (type = 'image/png', quality?: number) =>
        canvasRef.current?.toDataURL(type, quality) ?? '',
      toBlob: (type = 'image/png', quality?: number) =>
        new Promise((resolve) => {
          const el = canvasRef.current;
          if (!el) return resolve(null);
          el.toBlob(resolve, type, quality);
        }),
      isEmpty: () => emptyRef.current,
    }),
    [onChange],
  );

  function pointFromEvent(ev: PointerEvent | React.PointerEvent): SignaturePoint {
    const rect = canvasRef.current!.getBoundingClientRect();
    return { x: ev.clientX - rect.left, y: ev.clientY - rect.top };
  }

  function onDown(ev: React.PointerEvent<HTMLCanvasElement>) {
    if (disabled || !ctxRef.current || !canvasRef.current) return;
    if (ev.button !== undefined && ev.button !== 0) return;
    drawingRef.current = true;
    pointerIdRef.current = ev.pointerId;
    try {
      canvasRef.current.setPointerCapture(ev.pointerId);
    } catch {}
    const p = pointFromEvent(ev);
    strokeRef.current = [p];
    const ctx = ctxRef.current;
    ctx.strokeStyle = getStroke();
    ctx.lineWidth = strokeWidth;
    ctx.beginPath();
    ctx.moveTo(p.x, p.y);
    onStart?.();
  }

  function onMove(ev: React.PointerEvent<HTMLCanvasElement>) {
    if (!drawingRef.current || ev.pointerId !== pointerIdRef.current || !ctxRef.current) return;
    const p = pointFromEvent(ev);
    const stroke = strokeRef.current;
    const last = stroke[stroke.length - 1];
    const mid = { x: (last.x + p.x) / 2, y: (last.y + p.y) / 2 };
    const ctx = ctxRef.current;
    ctx.quadraticCurveTo(last.x, last.y, mid.x, mid.y);
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(mid.x, mid.y);
    stroke.push(p);
  }

  function onUp(ev: React.PointerEvent<HTMLCanvasElement>) {
    if (!drawingRef.current || ev.pointerId !== pointerIdRef.current || !ctxRef.current) return;
    drawingRef.current = false;
    const ctx = ctxRef.current;
    const stroke = strokeRef.current;
    if (stroke.length > 1) {
      const last = stroke[stroke.length - 1];
      ctx.lineTo(last.x, last.y);
      ctx.stroke();
    } else if (stroke.length === 1) {
      const p = stroke[0];
      ctx.beginPath();
      ctx.arc(p.x, p.y, strokeWidth / 2, 0, Math.PI * 2);
      ctx.fillStyle = getStroke();
      ctx.fill();
    }
    strokeRef.current = [];
    try {
      canvasRef.current?.releasePointerCapture(ev.pointerId);
    } catch {}
    emptyRef.current = false;
    onEnd?.();
    onChange?.(false);
  }

  const style: CSSProperties = {
    width: typeof width === 'number' ? `${width}px` : width,
    height: typeof height === 'number' ? `${height}px` : height,
    background,
  };

  return (
    <div
      className={['cf-signpad', disabled && 'is-disabled', className].filter(Boolean).join(' ')}
      style={style}
    >
      <canvas
        ref={canvasRef}
        className="cf-signpad__canvas"
        onPointerDown={onDown}
        onPointerMove={onMove}
        onPointerUp={onUp}
        onPointerCancel={onUp}
      />
    </div>
  );
});
