// packages/vue/src/popover/Popover.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue';
import {
  computePopoverPosition,
  type PopoverPlacement,
  type PopoverProps,
} from './variants';

const props = withDefaults(defineProps<PopoverProps>(), {
  open: undefined,
  placement: 'bottom',
  trigger: 'click',
  offset: 8,
  closeOnOutside: true,
  closeOnEsc: true,
  disabled: false,
});

const emit = defineEmits<{
  (e: 'update:open', value: boolean): void;
}>();

const triggerRef = ref<HTMLSpanElement | null>(null);
const panelRef = ref<HTMLDivElement | null>(null);

const controlled = computed(() => props.open !== undefined);
const inner = ref(false);
const visible = computed({
  get: () => (controlled.value ? !!props.open : inner.value),
  set: (v) => {
    if (!controlled.value) inner.value = v;
    emit('update:open', v);
  },
});

const pos = ref({ top: 0, left: 0, placement: props.placement as PopoverPlacement });

let hoverOpenTimer: ReturnType<typeof setTimeout> | null = null;
let hoverCloseTimer: ReturnType<typeof setTimeout> | null = null;

function clearHoverTimers() {
  if (hoverOpenTimer) clearTimeout(hoverOpenTimer);
  if (hoverCloseTimer) clearTimeout(hoverCloseTimer);
  hoverOpenTimer = null;
  hoverCloseTimer = null;
}

async function reposition() {
  if (!triggerRef.value || !panelRef.value) return;
  const tRect = triggerRef.value.getBoundingClientRect();
  const pw = panelRef.value.offsetWidth;
  const ph = panelRef.value.offsetHeight;
  pos.value = computePopoverPosition(tRect, pw, ph, props.placement, props.offset);
}

async function open() {
  if (props.disabled) return;
  visible.value = true;
  await nextTick();
  reposition();
}

function close() {
  visible.value = false;
}

function toggle() {
  if (visible.value) close();
  else open();
}

function onTriggerClick() {
  if (props.trigger !== 'click') return;
  toggle();
}

function onTriggerEnter() {
  if (props.trigger !== 'hover') return;
  clearHoverTimers();
  hoverOpenTimer = setTimeout(open, 100);
}
function onTriggerLeave() {
  if (props.trigger !== 'hover') return;
  clearHoverTimers();
  hoverCloseTimer = setTimeout(close, 120);
}
function onPanelEnter() {
  if (props.trigger !== 'hover') return;
  clearHoverTimers();
}
function onPanelLeave() {
  if (props.trigger !== 'hover') return;
  clearHoverTimers();
  hoverCloseTimer = setTimeout(close, 120);
}

function onDocumentClick(e: MouseEvent) {
  if (!visible.value) return;
  if (!props.closeOnOutside) return;
  if (props.trigger === 'manual') return;
  const t = e.target as Node | null;
  if (!t) return;
  if (triggerRef.value?.contains(t)) return;
  if (panelRef.value?.contains(t)) return;
  close();
}

function onKeyDown(e: KeyboardEvent) {
  if (!visible.value) return;
  if (e.key === 'Escape' && props.closeOnEsc) {
    close();
  }
}

watch(visible, async (v) => {
  if (v) {
    await nextTick();
    reposition();
    document.addEventListener('mousedown', onDocumentClick, true);
    document.addEventListener('keydown', onKeyDown);
    window.addEventListener('resize', reposition);
    window.addEventListener('scroll', reposition, true);
  } else {
    document.removeEventListener('mousedown', onDocumentClick, true);
    document.removeEventListener('keydown', onKeyDown);
    window.removeEventListener('resize', reposition);
    window.removeEventListener('scroll', reposition, true);
  }
});

onBeforeUnmount(() => {
  clearHoverTimers();
  document.removeEventListener('mousedown', onDocumentClick, true);
  document.removeEventListener('keydown', onKeyDown);
  window.removeEventListener('resize', reposition);
  window.removeEventListener('scroll', reposition, true);
});

const panelStyle = computed(() => ({
  top: `${pos.value.top}px`,
  left: `${pos.value.left}px`,
  width: typeof props.width === 'number' ? `${props.width}px` : props.width,
}));

const panelClass = computed(
  () => `cf-popover cf-popover--${pos.value.placement}`,
);
</script>

<template>
  <span
    ref="triggerRef"
    class="cf-popover-trigger"
    @click="onTriggerClick"
    @mouseenter="onTriggerEnter"
    @mouseleave="onTriggerLeave"
  >
    <slot />
  </span>
  <Teleport to="body">
    <Transition name="cf-popover-fade">
      <div
        v-if="visible"
        ref="panelRef"
        :class="panelClass"
        role="dialog"
        :style="panelStyle"
        @mouseenter="onPanelEnter"
        @mouseleave="onPanelLeave"
      >
        <slot name="content" />
        <span class="cf-popover__arrow" />
      </div>
    </Transition>
  </Teleport>
</template>

// packages/react/src/popover/Popover.tsx
import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type CSSProperties,
} from 'react';
import { createPortal } from 'react-dom';
import {
  computePopoverPosition,
  type PopoverPlacement,
  type PopoverProps,
} from './variants';

const ANIMATION_MS = 140;

export function Popover(props: PopoverProps) {
  const {
    open,
    defaultOpen = false,
    onOpenChange,
    placement = 'bottom',
    trigger = 'click',
    offset = 8,
    closeOnOutside = true,
    closeOnEsc = true,
    width,
    disabled = false,
    content,
    children,
  } = props;

  const controlled = open !== undefined;
  const [inner, setInner] = useState(defaultOpen);
  const visible = controlled ? !!open : inner;

  const setVisible = useCallback(
    (v: boolean) => {
      if (!controlled) setInner(v);
      onOpenChange?.(v);
    },
    [controlled, onOpenChange],
  );

  const triggerRef = useRef<HTMLSpanElement | null>(null);
  const panelRef = useRef<HTMLDivElement | null>(null);
  const hoverOpenTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const hoverCloseTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const [mounted, setMounted] = useState(visible);
  const [state, setState] = useState<'open' | 'closed'>(visible ? 'open' : 'closed');
  const [pos, setPos] = useState<{
    top: number;
    left: number;
    placement: PopoverPlacement;
  }>({ top: 0, left: 0, placement });

  const clearHoverTimers = useCallback(() => {
    if (hoverOpenTimer.current) clearTimeout(hoverOpenTimer.current);
    if (hoverCloseTimer.current) clearTimeout(hoverCloseTimer.current);
    hoverOpenTimer.current = null;
    hoverCloseTimer.current = null;
  }, []);

  useLayoutEffect(() => {
    if (visible) {
      setMounted(true);
      const id = requestAnimationFrame(() => setState('open'));
      return () => cancelAnimationFrame(id);
    }
    if (mounted) {
      setState('closed');
      const t = setTimeout(() => setMounted(false), ANIMATION_MS);
      return () => clearTimeout(t);
    }
    return undefined;
  }, [visible, mounted]);

  const reposition = useCallback(() => {
    if (!triggerRef.current || !panelRef.current) return;
    const tRect = triggerRef.current.getBoundingClientRect();
    const pw = panelRef.current.offsetWidth;
    const ph = panelRef.current.offsetHeight;
    setPos(computePopoverPosition(tRect, pw, ph, placement, offset));
  }, [placement, offset]);

  useLayoutEffect(() => {
    if (!mounted || state !== 'open') return;
    reposition();
  }, [mounted, state, reposition]);

  useEffect(() => {
    if (!mounted || state !== 'open') return;
    function onDocClick(e: MouseEvent) {
      if (!closeOnOutside) return;
      if (trigger === 'manual') return;
      const t = e.target as Node | null;
      if (!t) return;
      if (triggerRef.current?.contains(t)) return;
      if (panelRef.current?.contains(t)) return;
      setVisible(false);
    }
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape' && closeOnEsc) setVisible(false);
    }
    document.addEventListener('mousedown', onDocClick, true);
    document.addEventListener('keydown', onKey);
    window.addEventListener('resize', reposition);
    window.addEventListener('scroll', reposition, true);
    return () => {
      document.removeEventListener('mousedown', onDocClick, true);
      document.removeEventListener('keydown', onKey);
      window.removeEventListener('resize', reposition);
      window.removeEventListener('scroll', reposition, true);
    };
  }, [mounted, state, closeOnOutside, closeOnEsc, trigger, reposition, setVisible]);

  useEffect(() => () => clearHoverTimers(), [clearHoverTimers]);

  function onTriggerClick() {
    if (disabled) return;
    if (trigger !== 'click') return;
    setVisible(!visible);
  }

  function onTriggerEnter() {
    if (disabled) return;
    if (trigger !== 'hover') return;
    clearHoverTimers();
    hoverOpenTimer.current = setTimeout(() => setVisible(true), 100);
  }
  function onTriggerLeave() {
    if (trigger !== 'hover') return;
    clearHoverTimers();
    hoverCloseTimer.current = setTimeout(() => setVisible(false), 120);
  }
  function onPanelEnter() {
    if (trigger !== 'hover') return;
    clearHoverTimers();
  }
  function onPanelLeave() {
    if (trigger !== 'hover') return;
    clearHoverTimers();
    hoverCloseTimer.current = setTimeout(() => setVisible(false), 120);
  }

  const panelStyle: CSSProperties = {
    top: pos.top,
    left: pos.left,
    width: typeof width === 'number' ? `${width}px` : width,
  };

  return (
    <>
      <span
        ref={triggerRef}
        className="cf-popover-trigger"
        onClick={onTriggerClick}
        onMouseEnter={onTriggerEnter}
        onMouseLeave={onTriggerLeave}
      >
        {children}
      </span>
      {mounted && typeof document !== 'undefined'
        ? createPortal(
            <div
              ref={panelRef}
              className={`cf-popover cf-popover--${pos.placement}`}
              data-state={state}
              role="dialog"
              style={panelStyle}
              onMouseEnter={onPanelEnter}
              onMouseLeave={onPanelLeave}
            >
              {content}
              <span className="cf-popover__arrow" />
            </div>,
            document.body,
          )
        : null}
    </>
  );
}
