// packages/vue/src/splitbutton/SplitButton.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue';
import {
  splitButtonClass,
  type SplitButtonItem,
  type SplitButtonProps,
} from './variants';

const props = withDefaults(defineProps<SplitButtonProps>(), {
  variant: 'primary',
  size: 'md',
  disabled: false,
  loading: false,
});

const emit = defineEmits<{
  (e: 'click', evt: MouseEvent): void;
  (e: 'select', value: string, item: SplitButtonItem): void;
}>();

const open = ref(false);
const rootRef = ref<HTMLDivElement | null>(null);

const cls = computed(() => splitButtonClass(props));
const inactive = computed(() => props.disabled || props.loading);

function toggleMenu() {
  if (inactive.value) return;
  open.value = !open.value;
  if (open.value) document.addEventListener('mousedown', onDocClick);
  else document.removeEventListener('mousedown', onDocClick);
}

function closeMenu() {
  open.value = false;
  document.removeEventListener('mousedown', onDocClick);
}

function onDocClick(e: MouseEvent) {
  if (!rootRef.value) return;
  if (!rootRef.value.contains(e.target as Node)) closeMenu();
}

function pick(item: SplitButtonItem) {
  if (item.disabled) return;
  emit('select', item.value, item);
  closeMenu();
}

function onMainClick(e: MouseEvent) {
  if (inactive.value) return;
  emit('click', e);
}

onBeforeUnmount(() => document.removeEventListener('mousedown', onDocClick));
</script>

<template>
  <div ref="rootRef" :class="cls">
    <button
      type="button"
      class="cf-splitbtn__main"
      :disabled="inactive"
      :aria-busy="loading || undefined"
      @click="onMainClick"
    >
      <slot />
    </button>
    <span class="cf-splitbtn__div" aria-hidden="true" />
    <button
      type="button"
      class="cf-splitbtn__more"
      :disabled="inactive"
      :aria-haspopup="'menu'"
      :aria-expanded="open"
      aria-label="更多操作"
      @click="toggleMenu"
    >
      <svg
        class="cf-splitbtn__caret"
        viewBox="0 0 16 16"
        aria-hidden="true"
      >
        <path
          d="M4 6l4 4 4-4"
          stroke="currentColor"
          stroke-width="1.6"
          fill="none"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </button>
    <ul v-if="open" class="cf-splitbtn__menu" role="menu">
      <li
        v-for="item in items"
        :key="item.value"
        class="cf-splitbtn__option"
        :class="{
          'is-disabled': item.disabled,
          'is-danger': item.danger,
        }"
        role="menuitem"
        :aria-disabled="item.disabled || undefined"
        @mousedown.prevent="pick(item)"
      >
        {{ item.label }}
      </li>
    </ul>
  </div>
</template>

// packages/react/src/splitbutton/SplitButton.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useRef,
  useState,
  type MouseEvent as RMouseEvent,
} from 'react';
import {
  splitButtonClass,
  splitButtonDefaults,
  type SplitButtonItem,
  type SplitButtonProps,
} from './variants';

export const SplitButton = forwardRef<HTMLDivElement, SplitButtonProps>(
  function SplitButton(props, ref) {
    const {
      variant = splitButtonDefaults.variant,
      size = splitButtonDefaults.size,
      items,
      disabled,
      loading,
      onClick,
      onSelect,
      children,
      className,
      ...rest
    } = props;

    const inactive = disabled || loading;
    const [open, setOpen] = useState(false);
    const rootRef = useRef<HTMLDivElement | null>(null);

    const cls = splitButtonClass({
      variant,
      size,
      disabled,
      loading,
      className,
    });

    const closeMenu = useCallback(() => setOpen(false), []);

    useEffect(() => {
      if (!open) return;
      const onDoc = (e: globalThis.MouseEvent) => {
        if (!rootRef.current) return;
        if (!rootRef.current.contains(e.target as Node)) closeMenu();
      };
      document.addEventListener('mousedown', onDoc);
      return () => document.removeEventListener('mousedown', onDoc);
    }, [open, closeMenu]);

    const handleMain = (e: RMouseEvent<HTMLButtonElement>) => {
      if (inactive) return;
      onClick?.(e);
    };

    const handleToggle = () => {
      if (inactive) return;
      setOpen((v) => !v);
    };

    const pick = (item: SplitButtonItem) => {
      if (item.disabled) return;
      onSelect?.(item.value, item);
      setOpen(false);
    };

    return (
      <div
        ref={(node) => {
          rootRef.current = node;
          if (typeof ref === 'function') ref(node);
          else if (ref) ref.current = node;
        }}
        className={cls}
        {...rest}
      >
        <button
          type="button"
          className="cf-splitbtn__main"
          disabled={inactive}
          aria-busy={loading || undefined}
          onClick={handleMain}
        >
          {children}
        </button>
        <span className="cf-splitbtn__div" aria-hidden="true" />
        <button
          type="button"
          className="cf-splitbtn__more"
          disabled={inactive}
          aria-haspopup="menu"
          aria-expanded={open}
          aria-label="更多操作"
          onClick={handleToggle}
        >
          <svg
            className="cf-splitbtn__caret"
            viewBox="0 0 16 16"
            aria-hidden="true"
          >
            <path
              d="M4 6l4 4 4-4"
              stroke="currentColor"
              strokeWidth={1.6}
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        </button>
        {open ? (
          <ul className="cf-splitbtn__menu" role="menu">
            {items.map((item) => (
              <li
                key={item.value}
                role="menuitem"
                aria-disabled={item.disabled || undefined}
                className={[
                  'cf-splitbtn__option',
                  item.disabled && 'is-disabled',
                  item.danger && 'is-danger',
                ]
                  .filter(Boolean)
                  .join(' ')}
                onMouseDown={(e) => {
                  e.preventDefault();
                  pick(item);
                }}
              >
                {item.label}
              </li>
            ))}
          </ul>
        ) : null}
      </div>
    );
  },
);
