// packages/react/src/skeleton/Skeleton.tsx
import type { CSSProperties } from 'react';
import { type SkeletonProps, skeletonClass } from './variants';

function dim(v: string | number | undefined): string | undefined {
  if (v == null) return undefined;
  return typeof v === 'number' ? `${v}px` : v;
}

export function Skeleton(props: SkeletonProps) {
  const { shape = 'rect', width, height, lines = 1, static: isStatic = false } = props;
  const cls = skeletonClass({ shape, isStatic });
  const baseStyle: CSSProperties = {};
  const w = dim(width);
  const h = dim(height);
  if (w) baseStyle.width = w;
  if (h) baseStyle.height = h;

  if (shape === 'text' && lines > 1) {
    return (
      <span className="ck-skeleton-stack">
        {Array.from({ length: lines }).map((_, i) => (
          <span
            key={i}
            className={cls}
            style={i === lines - 1 ? { ...baseStyle, width: '60%' } : baseStyle}
          />
        ))}
      </span>
    );
  }
  return <span className={cls} style={baseStyle} />;
}

// packages/vue/src/skeleton/Skeleton.vue
<script setup lang="ts">
import { computed } from 'vue';
import { type SkeletonProps, skeletonClass } from './variants';

const props = withDefaults(defineProps<SkeletonProps>(), {
  shape: 'rect',
  lines: 1,
  static: false,
});

function dim(v: string | number | undefined): string | undefined {
  if (v == null) return undefined;
  return typeof v === 'number' ? `${v}px` : v;
}

const rootClass = computed(() =>
  skeletonClass({ shape: props.shape!, isStatic: props.static! })
);

const style = computed(() => {
  const w = dim(props.width);
  const h = dim(props.height);
  const out: Record<string, string> = {};
  if (w) out.width = w;
  if (h) out.height = h;
  return out;
});
</script>

<template>
  <span v-if="shape === 'text' && lines > 1" class="cf-skeleton-stack">
    <span
      v-for="i in lines"
      :key="i"
      :class="rootClass"
      :style="i === lines ? { ...style, width: '60%' } : style"
    />
  </span>
  <span v-else :class="rootClass" :style="style" />
</template>
