// packages/react/src/floatbutton/FloatButton.tsx
import { floatButtonClass, floatButtonStyle, type FloatButtonProps } from './variants';

export function FloatButton({
  children,
  shape = 'circle',
  variant = 'default',
  tooltip,
  badge,
  bottom,
  right,
  top,
  left,
  ariaLabel,
  className,
  onClick,
}: FloatButtonProps) {
  const cls = floatButtonClass({ shape, variant, className });
  const style = floatButtonStyle({ bottom, right, top, left });
  return (
    <button
      type="button"
      className={cls}
      style={style}
      aria-label={ariaLabel ?? tooltip}
      title={tooltip}
      onClick={onClick}
    >
      <span className="cf-floatbtn__icon">{children}</span>
      {badge != null && badge !== '' && (
        <span className="cf-floatbtn__badge">{badge}</span>
      )}
    </button>
  );
}

// packages/vue/src/floatbutton/FloatButton.vue
<script setup lang="ts">
import { computed } from 'vue';
import { floatButtonClass, floatButtonStyle, type FloatButtonProps } from './variants';

const props = withDefaults(defineProps<FloatButtonProps>(), {
  shape: 'circle',
  variant: 'default',
});

const emit = defineEmits<{ click: [evt: MouseEvent] }>();

const cls = computed(() =>
  floatButtonClass({
    shape: props.shape,
    variant: props.variant,
    className: props.className,
  }),
);

const style = computed(() =>
  floatButtonStyle({
    bottom: props.bottom,
    right: props.right,
    top: props.top,
    left: props.left,
  }),
);
</script>

<template>
  <button
    type="button"
    :class="cls"
    :style="style"
    :aria-label="ariaLabel ?? tooltip"
    :title="tooltip"
    @click="emit('click', $event)"
  >
    <span class="cf-floatbtn__icon">
      <slot />
    </span>
    <span v-if="badge != null && badge !== ''" class="cf-floatbtn__badge">{{ badge }}</span>
  </button>
</template>
