// packages/vue/src/codeeditor/CodeEditor.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import {
  buildLineNumbers,
  lineCount,
  type CodeEditorProps,
} from './variants';

const props = withDefaults(defineProps<CodeEditorProps>(), {
  modelValue: '',
  language: 'plaintext',
  size: 'md',
  showLineNumbers: true,
  readOnly: false,
  placeholder: '',
  rows: 12,
  wrap: false,
  tabSize: 2,
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void;
}>();

const textareaRef = ref<HTMLTextAreaElement | null>(null);
const gutterRef = ref<HTMLDivElement | null>(null);

const lines = computed(() => buildLineNumbers(lineCount(props.modelValue)));

const cls = computed(() => [
  'cf-codeeditor',
  `cf-codeeditor--${props.size}`,
  props.showLineNumbers && 'cf-codeeditor--gutter',
  props.readOnly && 'is-readonly',
  props.wrap && 'is-wrap',
]);

function onInput(e: Event) {
  emit('update:modelValue', (e.target as HTMLTextAreaElement).value);
}

function onScroll() {
  if (gutterRef.value && textareaRef.value) {
    gutterRef.value.scrollTop = textareaRef.value.scrollTop;
  }
}

function onKeyDown(e: KeyboardEvent) {
  if (e.key === 'Tab' && props.tabSize > 0 && !props.readOnly) {
    e.preventDefault();
    const ta = e.target as HTMLTextAreaElement;
    const start = ta.selectionStart;
    const end = ta.selectionEnd;
    const indent = ' '.repeat(props.tabSize);
    const next = ta.value.slice(0, start) + indent + ta.value.slice(end);
    emit('update:modelValue', next);
    requestAnimationFrame(() => {
      ta.selectionStart = ta.selectionEnd = start + indent.length;
    });
  }
}
</script>

<template>
  <div :class="cls">
    <div v-if="showLineNumbers" ref="gutterRef" class="cf-codeeditor__gutter">
      <span v-for="n in lines" :key="n">{{ n }}</span>
    </div>
    <textarea
      ref="textareaRef"
      class="cf-codeeditor__input"
      :value="modelValue"
      :placeholder="placeholder"
      :readonly="readOnly"
      :rows="rows"
      :spellcheck="false"
      :data-language="language"
      autocomplete="off"
      autocorrect="off"
      autocapitalize="off"
      @input="onInput"
      @scroll="onScroll"
      @keydown="onKeyDown"
    />
  </div>
</template>

// packages/react/src/codeeditor/CodeEditor.tsx
import { useMemo, useRef, type KeyboardEvent } from 'react';
import {
  buildLineNumbers,
  lineCount,
  type CodeEditorProps,
} from './variants';

export function CodeEditor(props: CodeEditorProps) {
  const {
    value,
    onChange,
    language = 'plaintext',
    size = 'md',
    showLineNumbers = true,
    readOnly = false,
    placeholder = '',
    rows = 12,
    wrap = false,
    tabSize = 2,
    className,
  } = props;

  const textareaRef = useRef<HTMLTextAreaElement | null>(null);
  const gutterRef = useRef<HTMLDivElement | null>(null);

  const lines = useMemo(() => buildLineNumbers(lineCount(value)), [value]);

  const cls = [
    'cf-codeeditor',
    `cf-codeeditor--${size}`,
    showLineNumbers && 'cf-codeeditor--gutter',
    readOnly && 'is-readonly',
    wrap && 'is-wrap',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const onScroll = () => {
    if (gutterRef.current && textareaRef.current) {
      gutterRef.current.scrollTop = textareaRef.current.scrollTop;
    }
  };

  const onKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Tab' && tabSize > 0 && !readOnly) {
      e.preventDefault();
      const ta = e.currentTarget;
      const start = ta.selectionStart;
      const end = ta.selectionEnd;
      const indent = ' '.repeat(tabSize);
      const next = ta.value.slice(0, start) + indent + ta.value.slice(end);
      onChange(next);
      requestAnimationFrame(() => {
        ta.selectionStart = ta.selectionEnd = start + indent.length;
      });
    }
  };

  return (
    <div className={cls}>
      {showLineNumbers ? (
        <div ref={gutterRef} className="cf-codeeditor__gutter">
          {lines.map((n) => (
            <span key={n}>{n}</span>
          ))}
        </div>
      ) : null}
      <textarea
        ref={textareaRef}
        className="cf-codeeditor__input"
        value={value}
        placeholder={placeholder}
        readOnly={readOnly}
        rows={rows}
        spellCheck={false}
        data-language={language}
        autoComplete="off"
        autoCorrect="off"
        autoCapitalize="off"
        onChange={(e) => onChange(e.target.value)}
        onScroll={onScroll}
        onKeyDown={onKeyDown}
      />
    </div>
  );
}
