// packages/vue/src/masonry/Masonry.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { useResizeObserver } from '../composables/useResizeObserver';
import { computeColumns, type MasonryProps } from './variants';

const props = withDefaults(defineProps<MasonryProps>(), {
  minColumnWidth: 240,
  gap: 12,
});

const rootRef = ref<HTMLDivElement | null>(null);
const width = ref(0);

useResizeObserver(rootRef, (entries) => {
  width.value = entries[0]?.contentRect.width ?? 0;
});

const cols = computed(() => computeColumns(width.value || 800, { columns: props.columns, minColumnWidth: props.minColumnWidth }));

const containerStyle = computed(() => ({
  columnCount: String(cols.value),
  columnGap: `${props.gap}px`,
  '--cf-masonry-gap': `${props.gap}px`,
}));
</script>

<template>
  <div ref="rootRef" class="cf-masonry" :style="containerStyle">
    <slot />
  </div>
</template>

// packages/react/src/masonry/Masonry.tsx
import { useMemo, useRef, useState, type CSSProperties } from 'react';
import { useResizeObserver } from '../hooks/useResizeObserver';
import { computeColumns, type MasonryProps } from './variants';

export function Masonry(props: MasonryProps) {
  const { columns, minColumnWidth = 240, gap = 12, children } = props;
  const rootRef = useRef<HTMLDivElement | null>(null);
  const [width, setWidth] = useState(0);

  useResizeObserver(rootRef, (entries) => {
    setWidth(entries[0]?.contentRect.width ?? 0);
  });

  const cols = useMemo(
    () => computeColumns(width || 800, { columns, minColumnWidth }),
    [width, columns, minColumnWidth],
  );

  const style: CSSProperties & Record<string, string | number> = {
    columnCount: cols,
    columnGap: `${gap}px`,
    ['--cf-masonry-gap' as string]: `${gap}px`,
  };

  return (
    <div ref={rootRef} className="cf-masonry" style={style}>
      {children}
    </div>
  );
}
