// packages/maps-vue/src/terrain3d/Terrain3D.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, shallowRef, watch } from 'vue';
import {
  type Terrain3DProps,
  normalizeHeights,
  resolveColorScale,
} from './variants';

const props = withDefaults(
  defineProps<Terrain3DProps>(),
  {
    exaggeration: 1,
    colorScale: 'depth',
    wireframe: false,
    autoRotate: false,
    showGrid: false,
    background: 'oklch(13% 0.012 260)',
    rendererWidth: '100%',
    rendererHeight: 480,
  },
);

const emit = defineEmits<{
  (e: 'ready'): void;
  (e: 'pick', payload: { x: number; y: number; z: number; row: number; col: number }): void;
}>();

const container = ref<HTMLDivElement | null>(null);
const error = ref<string | null>(null);

const sceneState = shallowRef<{
  THREE: typeof import('three');
  renderer: import('three').WebGLRenderer;
  scene: import('three').Scene;
  camera: import('three').PerspectiveCamera;
  controls: { update: () => void; dispose: () => void; autoRotate: boolean; target: import('three').Vector3 } | null;
  mesh: import('three').Mesh | null;
  wireframe: import('three').LineSegments | null;
  geometry: import('three').PlaneGeometry | null;
  grid: import('three').GridHelper | null;
  raf: number | null;
  resizeObs: ResizeObserver | null;
  pickRaycaster: import('three').Raycaster;
  pickPointer: import('three').Vector2;
} | null>(null);

const style = computed(() => ({
  width: typeof props.rendererWidth === 'number' ? `${props.rendererWidth}px` : props.rendererWidth,
  height: typeof props.rendererHeight === 'number' ? `${props.rendererHeight}px` : props.rendererHeight,
  background: props.background,
}));

async function mount() {
  if (!container.value) return;
  let THREE: typeof import('three');
  let OrbitControlsCtor: typeof import('three/examples/jsm/controls/OrbitControls.js').OrbitControls;
  try {
    THREE = await import('three');
    const orbit = await import('three/examples/jsm/controls/OrbitControls.js');
    OrbitControlsCtor = orbit.OrbitControls;
  } catch (e) {
    error.value = "未检测到 three.js 依赖。请安装：pnpm add three";
    return;
  }

  const el = container.value;
  const rect = el.getBoundingClientRect();
  const w = Math.max(64, rect.width);
  const h = Math.max(64, rect.height);

  const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
  renderer.setPixelRatio(Math.min(2, window.devicePixelRatio || 1));
  renderer.setSize(w, h, false);
  renderer.domElement.style.display = 'block';
  renderer.domElement.style.width = '100%';
  renderer.domElement.style.height = '100%';
  el.appendChild(renderer.domElement);

  const scene = new THREE.Scene();
  const camera = new THREE.PerspectiveCamera(45, w / h, 0.1, 5000);
  const pitch = ((props.camera?.pitch ?? 60) * Math.PI) / 180;
  const yaw = ((props.camera?.yaw ?? 0) * Math.PI) / 180;
  const zoom = props.camera?.zoom ?? 1;
  const distance = 240 * zoom;
  camera.position.set(
    Math.sin(yaw) * distance * Math.cos(pitch),
    distance * Math.sin(pitch),
    Math.cos(yaw) * distance * Math.cos(pitch),
  );
  camera.lookAt(0, 0, 0);

  const hemi = new THREE.HemisphereLight(0xffffff, 0x223347, 0.7);
  scene.add(hemi);
  const dir = new THREE.DirectionalLight(0xffffff, 0.7);
  dir.position.set(200, 300, 120);
  scene.add(dir);

  const controls = new OrbitControlsCtor(camera, renderer.domElement);
  controls.enableDamping = true;
  controls.dampingFactor = 0.08;
  controls.target.set(0, 0, 0);
  controls.autoRotate = !!props.autoRotate;
  controls.autoRotateSpeed = 0.4;

  const pickRaycaster = new THREE.Raycaster();
  const pickPointer = new THREE.Vector2();

  sceneState.value = {
    THREE,
    renderer,
    scene,
    camera,
    controls,
    mesh: null,
    wireframe: null,
    geometry: null,
    grid: null,
    raf: null,
    resizeObs: null,
    pickRaycaster,
    pickPointer,
  };

  rebuildMesh();
  rebuildGrid();

  function tick() {
    const s = sceneState.value;
    if (!s) return;
    s.controls?.update();
    s.renderer.render(s.scene, s.camera);
    s.raf = requestAnimationFrame(tick);
  }
  sceneState.value.raf = requestAnimationFrame(tick);

  const ro = new ResizeObserver(() => {
    onResize();
  });
  ro.observe(el);
  sceneState.value.resizeObs = ro;

  renderer.domElement.addEventListener('click', onPickClick);

  emit('ready');
}

function onResize() {
  const s = sceneState.value;
  if (!s || !container.value) return;
  const rect = container.value.getBoundingClientRect();
  const w = Math.max(64, rect.width);
  const h = Math.max(64, rect.height);
  s.renderer.setSize(w, h, false);
  s.camera.aspect = w / h;
  s.camera.updateProjectionMatrix();
}

function onPickClick(ev: MouseEvent) {
  const s = sceneState.value;
  if (!s || !s.mesh || !container.value) return;
  const rect = s.renderer.domElement.getBoundingClientRect();
  s.pickPointer.x = ((ev.clientX - rect.left) / rect.width) * 2 - 1;
  s.pickPointer.y = -((ev.clientY - rect.top) / rect.height) * 2 + 1;
  s.pickRaycaster.setFromCamera(s.pickPointer, s.camera);
  const hits = s.pickRaycaster.intersectObject(s.mesh, false);
  if (hits.length === 0) return;
  const p = hits[0].point;
  const planeSize = 200;
  const u = (p.x + planeSize / 2) / planeSize;
  const v = (p.z + planeSize / 2) / planeSize;
  const col = Math.max(0, Math.min(props.width - 1, Math.floor(u * props.width)));
  const row = Math.max(0, Math.min(props.height - 1, Math.floor(v * props.height)));
  emit('pick', { x: p.x, y: p.y, z: p.z, row, col });
}

function rebuildMesh() {
  const s = sceneState.value;
  if (!s) return;
  const { THREE } = s;
  if (s.mesh) {
    s.scene.remove(s.mesh);
    s.geometry?.dispose();
    (s.mesh.material as import('three').Material).dispose();
    s.mesh = null;
    s.geometry = null;
  }
  if (s.wireframe) {
    s.scene.remove(s.wireframe);
    (s.wireframe.geometry as import('three').BufferGeometry).dispose();
    (s.wireframe.material as import('three').Material).dispose();
    s.wireframe = null;
  }

  const cols = props.width;
  const rows = props.height;
  if (cols < 2 || rows < 2 || props.heightData.length < cols * rows) return;

  const planeSize = 200;
  const geom = new THREE.PlaneGeometry(planeSize, planeSize, cols - 1, rows - 1);
  geom.rotateX(-Math.PI / 2);

  const { min, range } = normalizeHeights(props.heightData, props.minHeight, props.maxHeight);
  const colorFn = resolveColorScale(props.colorScale);
  const positions = geom.attributes.position as import('three').BufferAttribute;
  const colors = new Float32Array(positions.count * 3);
  const exaggeration = props.exaggeration;
  const vScale = (60 * exaggeration) / (range || 1);
  for (let i = 0; i < positions.count; i++) {
    const v = props.heightData[i] ?? min;
    const t = (v - min) / range;
    positions.setY(i, (v - min) * vScale - 30);
    const c = colorFn(t);
    colors[i * 3] = c.r;
    colors[i * 3 + 1] = c.g;
    colors[i * 3 + 2] = c.b;
  }
  positions.needsUpdate = true;
  geom.setAttribute('color', new THREE.BufferAttribute(colors, 3));
  geom.computeVertexNormals();

  const mat = new THREE.MeshStandardMaterial({
    vertexColors: true,
    roughness: 0.85,
    metalness: 0.05,
    flatShading: false,
    side: THREE.DoubleSide,
  });
  const mesh = new THREE.Mesh(geom, mat);
  s.scene.add(mesh);
  s.mesh = mesh;
  s.geometry = geom;

  if (props.wireframe) {
    const wg = new THREE.WireframeGeometry(geom);
    const wm = new THREE.LineBasicMaterial({ color: 0xffffff, opacity: 0.12, transparent: true });
    const wf = new THREE.LineSegments(wg, wm);
    s.scene.add(wf);
    s.wireframe = wf;
  }
}

function rebuildGrid() {
  const s = sceneState.value;
  if (!s) return;
  const { THREE } = s;
  if (s.grid) {
    s.scene.remove(s.grid);
    (s.grid.geometry as import('three').BufferGeometry).dispose();
    (s.grid.material as import('three').Material).dispose();
    s.grid = null;
  }
  if (props.showGrid) {
    const grid = new THREE.GridHelper(220, 22, 0x3a4a5e, 0x222a36);
    grid.position.y = -30.2;
    s.scene.add(grid);
    s.grid = grid;
  }
}

function dispose() {
  const s = sceneState.value;
  if (!s) return;
  if (s.raf != null) cancelAnimationFrame(s.raf);
  s.resizeObs?.disconnect();
  s.renderer.domElement.removeEventListener('click', onPickClick);
  s.controls?.dispose();
  if (s.mesh) {
    s.scene.remove(s.mesh);
    s.geometry?.dispose();
    (s.mesh.material as import('three').Material).dispose();
  }
  if (s.wireframe) {
    (s.wireframe.geometry as import('three').BufferGeometry).dispose();
    (s.wireframe.material as import('three').Material).dispose();
  }
  if (s.grid) {
    (s.grid.geometry as import('three').BufferGeometry).dispose();
    (s.grid.material as import('three').Material).dispose();
  }
  s.renderer.dispose();
  s.renderer.domElement.remove();
  sceneState.value = null;
}

onMounted(mount);
onBeforeUnmount(dispose);

watch(
  () => [
    props.heightData,
    props.width,
    props.height,
    props.exaggeration,
    props.colorScale,
    props.minHeight,
    props.maxHeight,
    props.wireframe,
  ],
  () => {
    if (sceneState.value) rebuildMesh();
  },
);
watch(
  () => props.showGrid,
  () => {
    if (sceneState.value) rebuildGrid();
  },
);
watch(
  () => props.autoRotate,
  (v) => {
    if (sceneState.value?.controls) sceneState.value.controls.autoRotate = !!v;
  },
);
</script>

<template>
  <div ref="container" class="cf-terrain3d" :style="style">
    <div v-if="error" class="cf-terrain3d__error">{{ error }}</div>
  </div>
</template>

// packages/maps-react/src/terrain3d/Terrain3D.tsx
import { useEffect, useRef, useState, type CSSProperties } from 'react';
import {
  type Terrain3DColorScale,
  type Terrain3DBounds,
  type Terrain3DCamera,
  normalizeHeights,
  resolveColorScale,
} from './variants';

export interface Terrain3DPickPayload {
  x: number;
  y: number;
  z: number;
  row: number;
  col: number;
}

export interface Terrain3DProps {
  heightData: number[] | Float32Array;
  width: number;
  height: number;
  bounds?: Terrain3DBounds;
  minHeight?: number;
  maxHeight?: number;
  exaggeration?: number;
  colorScale?: Terrain3DColorScale | ((t: number) => { r: number; g: number; b: number });
  wireframe?: boolean;
  camera?: Terrain3DCamera;
  autoRotate?: boolean;
  showGrid?: boolean;
  background?: string;
  rendererWidth?: number | string;
  rendererHeight?: number | string;
  className?: string;
  onReady?: () => void;
  onPick?: (payload: Terrain3DPickPayload) => void;
}

export function Terrain3D({
  heightData,
  width,
  height,
  minHeight,
  maxHeight,
  exaggeration = 1,
  colorScale = 'depth',
  wireframe = false,
  camera,
  autoRotate = false,
  showGrid = false,
  background = 'oklch(13% 0.012 260)',
  rendererWidth = '100%',
  rendererHeight = 480,
  className,
  onReady,
  onPick,
}: Terrain3DProps) {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const stateRef = useRef<any>(null);
  const [error, setError] = useState<string | null>(null);
  const propsRef = useRef({ heightData, width, height, minHeight, maxHeight, exaggeration, colorScale, wireframe, onPick });
  propsRef.current = { heightData, width, height, minHeight, maxHeight, exaggeration, colorScale, wireframe, onPick };

  useEffect(() => {
    let cancelled = false;
    const el = containerRef.current;
    if (!el) return;

    (async () => {
      let THREE: typeof import('three');
      let OrbitControlsCtor: typeof import('three/examples/jsm/controls/OrbitControls.js').OrbitControls;
      try {
        THREE = await import('three');
        const orbit = await import('three/examples/jsm/controls/OrbitControls.js');
        OrbitControlsCtor = orbit.OrbitControls;
      } catch {
        if (!cancelled) setError('未检测到 three.js 依赖。请安装：pnpm add three');
        return;
      }
      if (cancelled) return;

      const rect = el.getBoundingClientRect();
      const w = Math.max(64, rect.width);
      const h = Math.max(64, rect.height);

      const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
      renderer.setPixelRatio(Math.min(2, window.devicePixelRatio || 1));
      renderer.setSize(w, h, false);
      renderer.domElement.style.display = 'block';
      renderer.domElement.style.width = '100%';
      renderer.domElement.style.height = '100%';
      el.appendChild(renderer.domElement);

      const scene = new THREE.Scene();
      const cam = new THREE.PerspectiveCamera(45, w / h, 0.1, 5000);
      const pitch = ((camera?.pitch ?? 60) * Math.PI) / 180;
      const yaw = ((camera?.yaw ?? 0) * Math.PI) / 180;
      const zoom = camera?.zoom ?? 1;
      const distance = 240 * zoom;
      cam.position.set(
        Math.sin(yaw) * distance * Math.cos(pitch),
        distance * Math.sin(pitch),
        Math.cos(yaw) * distance * Math.cos(pitch),
      );
      cam.lookAt(0, 0, 0);

      scene.add(new THREE.HemisphereLight(0xffffff, 0x223347, 0.7));
      const dir = new THREE.DirectionalLight(0xffffff, 0.7);
      dir.position.set(200, 300, 120);
      scene.add(dir);

      const controls = new OrbitControlsCtor(cam, renderer.domElement);
      controls.enableDamping = true;
      controls.dampingFactor = 0.08;
      controls.target.set(0, 0, 0);
      controls.autoRotate = !!autoRotate;
      controls.autoRotateSpeed = 0.4;

      const pickRaycaster = new THREE.Raycaster();
      const pickPointer = new THREE.Vector2();

      const state: any = {
        THREE,
        renderer,
        scene,
        camera: cam,
        controls,
        mesh: null,
        wireframe: null,
        geometry: null,
        grid: null,
        raf: null,
        resizeObs: null,
        pickRaycaster,
        pickPointer,
      };
      stateRef.current = state;

      function rebuildMesh() {
        const p = propsRef.current;
        if (state.mesh) {
          state.scene.remove(state.mesh);
          state.geometry?.dispose();
          state.mesh.material.dispose();
          state.mesh = null;
          state.geometry = null;
        }
        if (state.wireframe) {
          state.scene.remove(state.wireframe);
          state.wireframe.geometry.dispose();
          state.wireframe.material.dispose();
          state.wireframe = null;
        }
        const cols = p.width;
        const rows = p.height;
        if (cols < 2 || rows < 2 || p.heightData.length < cols * rows) return;
        const planeSize = 200;
        const geom = new THREE.PlaneGeometry(planeSize, planeSize, cols - 1, rows - 1);
        geom.rotateX(-Math.PI / 2);
        const { min, range } = normalizeHeights(p.heightData, p.minHeight, p.maxHeight);
        const colorFn = resolveColorScale(p.colorScale);
        const positions = geom.attributes.position as import('three').BufferAttribute;
        const colors = new Float32Array(positions.count * 3);
        const vScale = (60 * p.exaggeration) / (range || 1);
        for (let i = 0; i < positions.count; i++) {
          const v = p.heightData[i] ?? min;
          const t = (v - min) / range;
          positions.setY(i, (v - min) * vScale - 30);
          const c = colorFn(t);
          colors[i * 3] = c.r;
          colors[i * 3 + 1] = c.g;
          colors[i * 3 + 2] = c.b;
        }
        positions.needsUpdate = true;
        geom.setAttribute('color', new THREE.BufferAttribute(colors, 3));
        geom.computeVertexNormals();
        const mat = new THREE.MeshStandardMaterial({
          vertexColors: true,
          roughness: 0.85,
          metalness: 0.05,
          flatShading: false,
          side: THREE.DoubleSide,
        });
        const mesh = new THREE.Mesh(geom, mat);
        state.scene.add(mesh);
        state.mesh = mesh;
        state.geometry = geom;
        if (p.wireframe) {
          const wg = new THREE.WireframeGeometry(geom);
          const wm = new THREE.LineBasicMaterial({ color: 0xffffff, opacity: 0.12, transparent: true });
          const wf = new THREE.LineSegments(wg, wm);
          state.scene.add(wf);
          state.wireframe = wf;
        }
      }

      function rebuildGrid() {
        if (state.grid) {
          state.scene.remove(state.grid);
          state.grid.geometry.dispose();
          state.grid.material.dispose();
          state.grid = null;
        }
        if (showGrid) {
          const grid = new THREE.GridHelper(220, 22, 0x3a4a5e, 0x222a36);
          grid.position.y = -30.2;
          state.scene.add(grid);
          state.grid = grid;
        }
      }

      state.rebuildMesh = rebuildMesh;
      state.rebuildGrid = rebuildGrid;
      rebuildMesh();
      rebuildGrid();

      function tick() {
        controls.update();
        renderer.render(scene, cam);
        state.raf = requestAnimationFrame(tick);
      }
      state.raf = requestAnimationFrame(tick);

      const ro = new ResizeObserver(() => {
        if (!el) return;
        const r = el.getBoundingClientRect();
        renderer.setSize(Math.max(64, r.width), Math.max(64, r.height), false);
        cam.aspect = Math.max(64, r.width) / Math.max(64, r.height);
        cam.updateProjectionMatrix();
      });
      ro.observe(el);
      state.resizeObs = ro;

      function onClick(ev: MouseEvent) {
        const p = propsRef.current;
        if (!state.mesh) return;
        const r = renderer.domElement.getBoundingClientRect();
        pickPointer.x = ((ev.clientX - r.left) / r.width) * 2 - 1;
        pickPointer.y = -((ev.clientY - r.top) / r.height) * 2 + 1;
        pickRaycaster.setFromCamera(pickPointer, cam);
        const hits = pickRaycaster.intersectObject(state.mesh, false);
        if (hits.length === 0) return;
        const pt = hits[0].point;
        const planeSize = 200;
        const u = (pt.x + planeSize / 2) / planeSize;
        const v = (pt.z + planeSize / 2) / planeSize;
        const col = Math.max(0, Math.min(p.width - 1, Math.floor(u * p.width)));
        const row = Math.max(0, Math.min(p.height - 1, Math.floor(v * p.height)));
        p.onPick?.({ x: pt.x, y: pt.y, z: pt.z, row, col });
      }
      renderer.domElement.addEventListener('click', onClick);
      state.onClick = onClick;

      onReady?.();
    })();

    return () => {
      cancelled = true;
      const state = stateRef.current;
      if (!state) return;
      if (state.raf != null) cancelAnimationFrame(state.raf);
      state.resizeObs?.disconnect();
      state.renderer.domElement.removeEventListener('click', state.onClick);
      state.controls?.dispose();
      if (state.mesh) {
        state.scene.remove(state.mesh);
        state.geometry?.dispose();
        state.mesh.material.dispose();
      }
      if (state.wireframe) {
        state.wireframe.geometry.dispose();
        state.wireframe.material.dispose();
      }
      if (state.grid) {
        state.grid.geometry.dispose();
        state.grid.material.dispose();
      }
      state.renderer.dispose();
      state.renderer.domElement.remove();
      stateRef.current = null;
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    const state = stateRef.current;
    if (state?.rebuildMesh) state.rebuildMesh();
  }, [heightData, width, height, exaggeration, colorScale, minHeight, maxHeight, wireframe]);

  useEffect(() => {
    const state = stateRef.current;
    if (state?.rebuildGrid) state.rebuildGrid();
  }, [showGrid]);

  useEffect(() => {
    const state = stateRef.current;
    if (state?.controls) state.controls.autoRotate = !!autoRotate;
  }, [autoRotate]);

  const style: CSSProperties = {
    width: typeof rendererWidth === 'number' ? `${rendererWidth}px` : rendererWidth,
    height: typeof rendererHeight === 'number' ? `${rendererHeight}px` : rendererHeight,
    background,
  };

  return (
    <div
      ref={containerRef}
      className={['cf-terrain3d', className].filter(Boolean).join(' ')}
      style={style}
    >
      {error && <div className="cf-terrain3d__error">{error}</div>}
    </div>
  );
}
