// packages/vue/src/stackedbar100/StackedBar100.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { StackedBar100Props } from './variants';

const props = withDefaults(defineProps<StackedBar100Props>(), {
  width: 480,
  height: 24,
  showLegend: true,
});

const layout = computed(() => {
  const segs = props.segments ?? [];
  const total = segs.reduce((s, x) => s + x.value, 0) || 1;
  let acc = 0;
  return segs.map((s, i) => {
    const start = (acc / total) * 100;
    acc += s.value;
    const end = (acc / total) * 100;
    return {
      ...s,
      colorIndex: s.colorIndex ?? i % 8,
      pct: end - start,
      start,
    };
  });
});
</script>

<template>
  <div class="cf-stacked100" role="img" :aria-label="ariaLabel ?? '占比柱'">
    <div
      class="cf-stacked100__bar"
      :style="{ height: typeof height === 'number' ? `${height}px` : height }"
    >
      <span
        v-for="(seg, i) in layout"
        :key="i"
        :class="[`cf-stacked100__seg`, `cf-chart__bar--${seg.colorIndex}`]"
        :style="{ width: `${seg.pct}%` }"
        :title="`${seg.name}: ${seg.value}`"
      />
    </div>
    <ul v-if="showLegend" class="cf-stacked100__legend">
      <li v-for="(seg, i) in layout" :key="i">
        <span :class="['cf-stacked100__dot', `cf-chart__bar--${seg.colorIndex}`]" />
        {{ seg.name }}
        <span class="cf-stacked100__pct">{{ seg.pct.toFixed(1) }}%</span>
      </li>
    </ul>
  </div>
</template>

// packages/react/src/stackedbar100/StackedBar100.tsx
import { useMemo } from 'react';
import type { StackedBar100Props } from './variants';

export function StackedBar100(props: StackedBar100Props) {
  const {
    segments,
    height = 24,
    showLegend = true,
    ariaLabel = '占比柱',
    className,
  } = props;

  const layout = useMemo(() => {
    const total = segments.reduce((s, x) => s + x.value, 0) || 1;
    let acc = 0;
    return segments.map((s, i) => {
      const start = (acc / total) * 100;
      acc += s.value;
      const end = (acc / total) * 100;
      return {
        ...s,
        colorIndex: s.colorIndex ?? i % 8,
        pct: end - start,
        start,
      };
    });
  }, [segments]);

  return (
    <div
      className={['cf-stacked100', className].filter(Boolean).join(' ')}
      role="img"
      aria-label={ariaLabel}
    >
      <div
        className="cf-stacked100__bar"
        style={{ height: typeof height === 'number' ? `${height}px` : height }}
      >
        {layout.map((seg, i) => (
          <span
            key={i}
            className={`cf-stacked100__seg cf-chart__bar--${seg.colorIndex}`}
            style={{ width: `${seg.pct}%` }}
            title={`${seg.name}: ${seg.value}`}
          />
        ))}
      </div>
      {showLegend ? (
        <ul className="cf-stacked100__legend">
          {layout.map((seg, i) => (
            <li key={i}>
              <span
                className={`cf-stacked100__dot cf-chart__bar--${seg.colorIndex}`}
              />
              {seg.name}
              <span className="cf-stacked100__pct">{seg.pct.toFixed(1)}%</span>
            </li>
          ))}
        </ul>
      ) : null}
    </div>
  );
}
