// packages/react/src/empty/Empty.tsx
import { type EmptyProps, emptyClass } from './variants';
import { StatusIllustration } from '../statusillustration/StatusIllustration';

export function Empty(props: EmptyProps) {
  const { title = '暂无数据', description, size = 'md', image, imageAlt = '', icon, action } = props;
  return (
    <div className={emptyClass({ size })} role="status">
      <div className="cf-empty__icon">
        {icon ?? (image ? <img className="cf-empty__image" src={image} alt={imageAlt} /> : <StatusIllustration variant="empty" />)}
      </div>
      <div className="cf-empty__title">{title}</div>
      {description != null && <div className="cf-empty__desc">{description}</div>}
      {action != null && <div className="cf-empty__action">{action}</div>}
    </div>
  );
}

// packages/vue/src/empty/Empty.vue
<script setup lang="ts">
import { computed } from 'vue';
import { type EmptyProps, emptyClass } from './variants';
import StatusIllustration from '../statusillustration/StatusIllustration.vue';

const props = withDefaults(defineProps<EmptyProps>(), {
  title: '暂无数据',
  size: 'md',
});

const rootClass = computed(() => emptyClass({ size: props.size! }));
</script>

<template>
  <div :class="rootClass" role="status">
    <div class="cf-empty__icon">
      <slot name="icon">
        <img v-if="image" class="cf-empty__image" :src="image" :alt="imageAlt ?? ''" />
        <StatusIllustration v-else variant="empty" />
      </slot>
    </div>
    <div class="cf-empty__title">
      <slot name="title">{{ title }}</slot>
    </div>
    <div v-if="description || $slots.description" class="cf-empty__desc">
      <slot name="description">{{ description }}</slot>
    </div>
    <div v-if="$slots.action" class="cf-empty__action">
      <slot name="action" />
    </div>
  </div>
</template>
