// packages/react/src/cascader/Cascader.tsx
import { useEffect, useRef, useState, type MouseEvent } from 'react';
import {
  cascaderClass,
  getLabelPath,
  type CascaderOption,
  type CascaderProps,
} from './variants';

export function Cascader(props: CascaderProps) {
  const {
    options,
    value,
    defaultValue = [],
    placeholder = '请选择',
    separator = ' / ',
    size = 'md',
    disabled = false,
    clearable = false,
    className,
    onChange,
  } = props;

  const isControlled = value !== undefined;
  const [internal, setInternal] = useState<string[]>(defaultValue);
  const current = isControlled ? (value as string[]) : internal;

  const [open, setOpen] = useState(false);
  const [trail, setTrail] = useState<string[]>(current);
  const rootRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    setTrail(current);
  }, [current]);

  useEffect(() => {
    function handle(e: PointerEvent) {
      if (!rootRef.current?.contains(e.target as Node)) setOpen(false);
    }
    if (open) {
      document.addEventListener('pointerdown', handle);
      return () => document.removeEventListener('pointerdown', handle);
    }
  }, [open]);

  function commit(next: string[]) {
    if (!isControlled) setInternal(next);
    onChange?.(next);
  }

  const columns: CascaderOption[][] = [options];
  let level = options;
  for (const v of trail) {
    const found = level.find((o) => o.value === v);
    if (!found || !found.children?.length) break;
    columns.push(found.children);
    level = found.children;
  }

  const labels = getLabelPath(options, current);
  const display = labels.join(separator);
  const showClear = clearable && current.length > 0;

  function pick(colIndex: number, opt: CascaderOption) {
    if (opt.disabled) return;
    const next = trail.slice(0, colIndex);
    next.push(opt.value);
    setTrail(next);
    if (!opt.children?.length) {
      commit(next);
      setOpen(false);
    }
  }

  function clearValue(e: MouseEvent) {
    e.stopPropagation();
    commit([]);
    setTrail([]);
  }

  return (
    <div ref={rootRef} className={cascaderClass({ size, disabled, className })}>
      <button
        type="button"
        className="cf-cascader__trigger"
        disabled={disabled}
        onClick={() => !disabled && setOpen((v) => !v)}
      >
        <span className={`cf-cascader__value${display ? '' : ' is-placeholder'}`}>
          {display || placeholder}
        </span>
        {showClear ? (
          <button
            type="button"
            className="cf-cascader__clear"
            aria-label="清除"
            onClick={clearValue}
          >
            ×
          </button>
        ) : null}
        <span className="cf-cascader__caret" aria-hidden>▾</span>
      </button>
      {open ? (
        <div className="cf-cascader__panel">
          {columns.map((col, ci) => (
            <div key={ci} className="cf-cascader__col">
              {col.map((opt) => {
                const itemCls = [
                  'cf-cascader__item',
                  opt.value === trail[ci] && 'is-active',
                  current[ci] === opt.value && 'is-selected',
                  opt.disabled && 'is-disabled',
                ]
                  .filter(Boolean)
                  .join(' ');
                return (
                  <button
                    key={opt.value}
                    type="button"
                    className={itemCls}
                    disabled={opt.disabled}
                    onMouseEnter={() => {
                      if (opt.disabled) return;
                      setTrail([...trail.slice(0, ci), opt.value]);
                    }}
                    onClick={() => pick(ci, opt)}
                  >
                    <span className="cf-cascader__label">{opt.label}</span>
                    {opt.children?.length ? (
                      <span className="cf-cascader__arrow" aria-hidden>›</span>
                    ) : null}
                  </button>
                );
              })}
            </div>
          ))}
        </div>
      ) : null}
    </div>
  );
}

// packages/vue/src/cascader/Cascader.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import {
  cascaderClass,
  getLabelPath,
  type CascaderOption,
  type CascaderProps,
} from './variants';

const props = withDefaults(defineProps<CascaderProps>(), {
  defaultValue: () => [],
  placeholder: '请选择',
  separator: ' / ',
  size: 'md',
  disabled: false,
  clearable: false,
});

const emit = defineEmits<{
  'update:modelValue': [value: string[]];
  change: [value: string[]];
}>();

const isControlled = computed(() => props.modelValue !== undefined);
const internal = ref<string[]>(props.defaultValue ?? []);
const value = computed<string[]>(() =>
  isControlled.value ? (props.modelValue as string[]) : internal.value,
);

const open = ref(false);
const activeTrail = ref<string[]>([]);

watch(
  value,
  (v) => {
    activeTrail.value = v.slice();
  },
  { immediate: true },
);

function commit(next: string[]) {
  if (!isControlled.value) internal.value = next;
  emit('update:modelValue', next);
  emit('change', next);
}

const columns = computed(() => {
  const cols: CascaderOption[][] = [props.options];
  let level: CascaderOption[] = props.options;
  for (const v of activeTrail.value) {
    const found = level.find((o) => o.value === v);
    if (!found || !found.children?.length) break;
    cols.push(found.children);
    level = found.children;
  }
  return cols;
});

const labels = computed(() => getLabelPath(props.options, value.value));
const display = computed(() => labels.value.join(props.separator));
const showClear = computed(() => props.clearable && value.value.length > 0);

function pick(colIndex: number, opt: CascaderOption) {
  if (opt.disabled) return;
  const trail = activeTrail.value.slice(0, colIndex);
  trail.push(opt.value);
  activeTrail.value = trail;
  if (!opt.children?.length) {
    commit(trail);
    open.value = false;
  }
}

function toggle() {
  if (props.disabled) return;
  open.value = !open.value;
}

function clearValue(e: MouseEvent) {
  e.stopPropagation();
  commit([]);
  activeTrail.value = [];
}

function onBlur(e: FocusEvent) {
  const root = (e.currentTarget as HTMLElement).closest('.cf-cascader');
  setTimeout(() => {
    if (!root?.contains(document.activeElement)) open.value = false;
  }, 0);
}

const cls = computed(() =>
  cascaderClass({ size: props.size, disabled: props.disabled, className: props.className }),
);
</script>

<template>
  <div :class="cls" @focusout="onBlur">
    <button
      type="button"
      class="cf-cascader__trigger"
      :disabled="disabled"
      @click="toggle"
    >
      <span :class="['cf-cascader__value', !display && 'is-placeholder']">
        {{ display || placeholder }}
      </span>
      <button
        v-if="showClear"
        type="button"
        class="cf-cascader__clear"
        aria-label="清除"
        @click="clearValue"
      >×</button>
      <span class="cf-cascader__caret" aria-hidden>▾</span>
    </button>
    <div v-if="open" class="cf-cascader__panel">
      <div
        v-for="(col, ci) in columns"
        :key="ci"
        class="cf-cascader__col"
      >
        <button
          v-for="opt in col"
          :key="opt.value"
          type="button"
          :class="[
            'cf-cascader__item',
            opt.value === activeTrail[ci] && 'is-active',
            value[ci] === opt.value && 'is-selected',
            opt.disabled && 'is-disabled',
          ]"
          :disabled="opt.disabled"
          @mouseenter="opt.disabled || (activeTrail = [...activeTrail.slice(0, ci), opt.value])"
          @click="pick(ci, opt)"
        >
          <span class="cf-cascader__label">{{ opt.label }}</span>
          <span v-if="opt.children?.length" class="cf-cascader__arrow" aria-hidden>›</span>
        </button>
      </div>
    </div>
  </div>
</template>
