// packages/react/src/flowmap/FlowMap.tsx
import { useMemo } from 'react';
import {
  computeExtent,
  curvedArc,
  pointBoundsExtent,
  polygonToFitPath,
  projectFit,
  valueToWidth,
  type FlowMapProps,
} from './variants';
import type { GeoJsonFeature } from '../mapminimap/variants';

export function FlowMap(props: FlowMapProps) {
  const {
    geojson,
    points,
    edges,
    extent: extentProp,
    width = 480,
    height = 280,
    widthRange,
    curvature = 0.22,
    showArrow = true,
    showNodes = true,
    showLabels = false,
  } = props;

  const extent = useMemo(
    () =>
      extentProp ??
      (geojson?.features?.length ? computeExtent(geojson.features) : pointBoundsExtent(points)),
    [extentProp, geojson, points],
  );

  const range: [number, number] = widthRange ?? [0.6, 3];

  const pointIndex = useMemo(() => {
    const m = new Map<string, { x: number; y: number; name: string }>();
    for (const p of points) {
      const { x, y } = projectFit(p.lng, p.lat, extent, width, height);
      m.set(String(p.id), { x, y, name: p.name ?? String(p.id) });
    }
    return m;
  }, [points, extent, width, height]);

  const valueRange = useMemo<[number, number]>(() => {
    let min = Infinity;
    let max = -Infinity;
    for (const e of edges) {
      if (e.value == null || !Number.isFinite(e.value)) continue;
      if (e.value < min) min = e.value;
      if (e.value > max) max = e.value;
    }
    if (!Number.isFinite(min)) return [0, 1];
    if (min === max) return [min, min + 1];
    return [min, max];
  }, [edges]);

  const basePaths = useMemo(() => {
    const features = geojson?.features ?? [];
    return features.map((f, i) => {
      const geom = (f as GeoJsonFeature).geometry;
      const multi = geom.type === 'MultiPolygon';
      return {
        id: i,
        d: polygonToFitPath(geom.coordinates as never, multi, extent, width, height),
      };
    });
  }, [geojson, extent, width, height]);

  const arcs = useMemo(() => {
    const out: { id: number; d: string; width: number; label?: string }[] = [];
    const [vmin, vmax] = valueRange;
    for (let i = 0; i < edges.length; i++) {
      const e = edges[i];
      const a = pointIndex.get(String(e.from));
      const b = pointIndex.get(String(e.to));
      if (!a || !b) continue;
      const w = valueToWidth(e.value, vmin, vmax, range);
      out.push({ id: i, d: curvedArc(a.x, a.y, b.x, b.y, curvature), width: w, label: e.label });
    }
    return out;
  }, [edges, pointIndex, valueRange, range, curvature]);

  const nodes = useMemo(
    () => Array.from(pointIndex.entries()).map(([id, p]) => ({ id, ...p })),
    [pointIndex],
  );

  return (
    <svg
      className="cf-flowmap"
      viewBox={`0 0 ${width} ${height}`}
      width={width}
      height={height}
      role="img"
      aria-label="迁徙地图"
    >
      <defs>
        {showArrow && (
          <marker
            id="cf-flowmap-arrow"
            viewBox="0 0 10 10"
            refX="9"
            refY="5"
            markerWidth="5"
            markerHeight="5"
            markerUnits="userSpaceOnUse"
            orient="auto-start-reverse"
          >
            <path className="cf-flowmap__arrow-head" d="M0,0 L10,5 L0,10 z" />
          </marker>
        )}
      </defs>
      <rect className="cf-flowmap__bg" x={0} y={0} width={width} height={height} />
      {basePaths.map((bp) => (
        <path key={`base-${bp.id}`} className="cf-flowmap__land" d={bp.d} />
      ))}
      <g className="cf-flowmap__arcs">
        {arcs.map((a) => (
          <path
            key={`arc-${a.id}`}
            className="cf-flowmap__arc"
            d={a.d}
            strokeWidth={a.width}
            markerEnd={showArrow ? 'url(#cf-flowmap-arrow)' : undefined}
          >
            {a.label && <title>{a.label}</title>}
          </path>
        ))}
      </g>
      {showNodes && (
        <g className="cf-flowmap__nodes">
          {nodes.map((n) => (
            <g key={`n-${n.id}`} className="cf-flowmap__node">
              <circle className="cf-flowmap__dot" cx={n.x} cy={n.y} r={2.6} />
              {showLabels && (
                <text className="cf-flowmap__label" x={n.x + 5} y={n.y - 5}>
                  {n.name}
                </text>
              )}
            </g>
          ))}
        </g>
      )}
    </svg>
  );
}

// packages/vue/src/flowmap/FlowMap.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  computeExtent,
  curvedArc,
  pointBoundsExtent,
  polygonToFitPath,
  projectFit,
  valueToWidth,
  type FlowMapProps,
} from './variants';
import type { GeoJsonFeature } from '../mapminimap/variants';

const props = withDefaults(defineProps<FlowMapProps>(), {
  width: 480,
  height: 280,
  curvature: 0.22,
  showArrow: true,
  showNodes: true,
  showLabels: false,
});

const extent = computed(() =>
  props.extent ??
  (props.geojson?.features?.length
    ? computeExtent(props.geojson.features)
    : pointBoundsExtent(props.points)),
);

const range = computed<[number, number]>(() => props.widthRange ?? [0.6, 3]);

const pointIndex = computed(() => {
  const m = new Map<string, { x: number; y: number; name: string }>();
  for (const p of props.points) {
    const { x, y } = projectFit(p.lng, p.lat, extent.value, props.width, props.height);
    m.set(String(p.id), { x, y, name: p.name ?? String(p.id) });
  }
  return m;
});

const valueRange = computed<[number, number]>(() => {
  let min = Infinity;
  let max = -Infinity;
  for (const e of props.edges) {
    if (e.value == null || !Number.isFinite(e.value)) continue;
    if (e.value < min) min = e.value;
    if (e.value > max) max = e.value;
  }
  if (!Number.isFinite(min)) return [0, 1];
  if (min === max) return [min, min + 1];
  return [min, max];
});

const basePaths = computed(() => {
  const features = props.geojson?.features ?? [];
  return features.map((f, i) => {
    const geom = (f as GeoJsonFeature).geometry;
    const multi = geom.type === 'MultiPolygon';
    return {
      id: i,
      d: polygonToFitPath(
        geom.coordinates as never,
        multi,
        extent.value,
        props.width,
        props.height,
      ),
    };
  });
});

const arcs = computed(() => {
  const out: { id: number; d: string; width: number; label?: string }[] = [];
  const [vmin, vmax] = valueRange.value;
  for (let i = 0; i < props.edges.length; i++) {
    const e = props.edges[i];
    const a = pointIndex.value.get(String(e.from));
    const b = pointIndex.value.get(String(e.to));
    if (!a || !b) continue;
    const w = valueToWidth(e.value, vmin, vmax, range.value);
    out.push({ id: i, d: curvedArc(a.x, a.y, b.x, b.y, props.curvature), width: w, label: e.label });
  }
  return out;
});

const nodes = computed(() => {
  return Array.from(pointIndex.value.entries()).map(([id, p]) => ({ id, ...p }));
});
</script>

<template>
  <svg
    class="cf-flowmap"
    :viewBox="`0 0 ${width} ${height}`"
    :width="width"
    :height="height"
    role="img"
    aria-label="迁徙地图"
  >
    <defs>
      <marker
        v-if="showArrow"
        id="cf-flowmap-arrow"
        viewBox="0 0 10 10"
        refX="9"
        refY="5"
        markerWidth="5"
        markerHeight="5"
        markerUnits="userSpaceOnUse"
        orient="auto-start-reverse"
      >
        <path class="cf-flowmap__arrow-head" d="M0,0 L10,5 L0,10 z" />
      </marker>
    </defs>
    <rect class="cf-flowmap__bg" x="0" y="0" :width="width" :height="height" />
    <path
      v-for="bp in basePaths"
      :key="`base-${bp.id}`"
      class="cf-flowmap__land"
      :d="bp.d"
    />
    <g class="cf-flowmap__arcs">
      <path
        v-for="a in arcs"
        :key="`arc-${a.id}`"
        class="cf-flowmap__arc"
        :d="a.d"
        :stroke-width="a.width"
        :marker-end="showArrow ? 'url(#cf-flowmap-arrow)' : undefined"
      >
        <title v-if="a.label">{{ a.label }}</title>
      </path>
    </g>
    <g v-if="showNodes" class="cf-flowmap__nodes">
      <g v-for="n in nodes" :key="`n-${n.id}`" class="cf-flowmap__node">
        <circle class="cf-flowmap__dot" :cx="n.x" :cy="n.y" r="2.6" />
        <text
          v-if="showLabels"
          class="cf-flowmap__label"
          :x="n.x + 5"
          :y="n.y - 5"
        >{{ n.name }}</text>
      </g>
    </g>
  </svg>
</template>
