// packages/react/src/fab/Fab.tsx
import { useEffect, useRef, useState, type MouseEvent } from 'react';
import type { FabProps } from './variants';

export function Fab(props: FabProps) {
  const {
    icon,
    label,
    extended,
    size = 'md',
    variant = 'primary',
    position = 'bottom-right',
    hideOnScroll = false,
    badge,
    disabled = false,
    ariaLabel,
    onClick,
    children,
  } = props;

  const isExtended = typeof extended === 'boolean' ? extended : Boolean(label);
  const [hidden, setHidden] = useState(false);
  const lastScrollRef = useRef(0);

  useEffect(() => {
    if (!hideOnScroll || typeof window === 'undefined') return;
    lastScrollRef.current = window.scrollY || 0;
    function onScroll() {
      const y = window.scrollY || document.documentElement.scrollTop || 0;
      const delta = y - lastScrollRef.current;
      if (Math.abs(delta) > 4) {
        setHidden(delta > 0 && y > 80);
        lastScrollRef.current = y;
      }
    }
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, [hideOnScroll]);

  function handleClick(e: MouseEvent<HTMLButtonElement>) {
    if (disabled) return;
    onClick?.(e);
  }

  const showBadge = badge !== undefined && badge !== '' && badge !== 0;

  return (
    <button
      type="button"
      className={[
        'cf-fab',
        `cf-fab--${size}`,
        `cf-fab--${variant}`,
        `cf-fab--${position}`,
        isExtended ? 'cf-fab--extended' : '',
        hidden ? 'is-hidden' : '',
      ]
        .filter(Boolean)
        .join(' ')}
      aria-label={ariaLabel || label}
      disabled={disabled}
      onClick={handleClick}
    >
      {(icon || children) && (
        <span className="cf-fab__icon">{icon ?? children}</span>
      )}
      {isExtended && label && <span className="cf-fab__label">{label}</span>}
      {showBadge && <span className="cf-fab__badge">{badge}</span>}
    </button>
  );
}

// packages/vue/src/fab/Fab.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, useSlots } from 'vue';
import type { FabProps } from './variants';

const props = withDefaults(defineProps<FabProps>(), {
  size: 'md',
  variant: 'primary',
  position: 'bottom-right',
  hideOnScroll: false,
  disabled: false,
});

const emit = defineEmits<{
  (e: 'click', ev: MouseEvent): void;
}>();

const slots = useSlots();

const isExtended = computed(() => {
  if (typeof props.extended === 'boolean') return props.extended;
  return Boolean(props.label);
});

const hidden = ref(false);
let lastScroll = 0;

function onScroll() {
  if (!props.hideOnScroll || typeof window === 'undefined') return;
  const y = window.scrollY || document.documentElement.scrollTop || 0;
  const delta = y - lastScroll;
  if (Math.abs(delta) > 4) {
    hidden.value = delta > 0 && y > 80;
    lastScroll = y;
  }
}

onMounted(() => {
  if (typeof window !== 'undefined') {
    lastScroll = window.scrollY || 0;
    window.addEventListener('scroll', onScroll, { passive: true });
  }
});
onBeforeUnmount(() => {
  if (typeof window !== 'undefined') window.removeEventListener('scroll', onScroll);
});

function handleClick(e: MouseEvent) {
  if (props.disabled) return;
  emit('click', e);
}

const showBadge = computed(() => props.badge !== undefined && props.badge !== '' && props.badge !== 0);
</script>

<template>
  <button
    type="button"
    :class="[
      'cf-fab',
      `cf-fab--${size}`,
      `cf-fab--${variant}`,
      `cf-fab--${position}`,
      isExtended && 'cf-fab--extended',
      hidden && 'is-hidden',
    ]"
    :aria-label="ariaLabel || label"
    :disabled="disabled"
    @click="handleClick"
  >
    <span v-if="slots.icon || $slots.default" class="cf-fab__icon">
      <slot name="icon">
        <slot />
      </slot>
    </span>
    <span v-if="isExtended && label" class="cf-fab__label">{{ label }}</span>
    <span v-if="showBadge" class="cf-fab__badge">{{ badge }}</span>
  </button>
</template>
