// packages/react/src/drawer/Drawer.tsx
import {
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type MouseEvent,
  type PointerEvent as ReactPointerEvent,
} from 'react';
import { createPortal } from 'react-dom';
import {
  lockBodyScroll,
  trapFocus,
  unlockBodyScroll,
  type FocusTrap,
} from '../modal/dom';
import { useDrag } from '../hooks/useDrag';
import {
  pushDrawer,
  topMostDrawerCloseFn,
  DRAWER_TONE_ICON_PATH,
  type DrawerProps as BaseDrawerProps,
} from './variants';

const ANIMATION_MS = 220;

export type DrawerProps = BaseDrawerProps;

export function Drawer(props: DrawerProps) {
  const {
    open,
    onOpenChange,
    title,
    description,
    placement = 'right',
    size = 'md',
    tone = 'default',
    closeOnOverlay = true,
    closeOnEsc = true,
    showClose = true,
    width,
    height,
    resizable = false,
    showGrabber,
    dismissible,
    mask = true,
    footerAlign = 'end',
    okText,
    cancelText,
    okVariant = 'primary',
    onBeforeOk,
    onOk,
    onCancel,
    container,
    header,
    footer,
    children,
    zIndex,
  } = props;

  const [mounted, setMounted] = useState(open);
  const [state, setState] = useState<'open' | 'closed'>(open ? 'open' : 'closed');
  const panelRef = useRef<HTMLDivElement | null>(null);
  const trapRef = useRef<FocusTrap | null>(null);
  const stackEntryRef = useRef<{ zIndex: number; release: () => void } | null>(null);
  const [computedZ, setComputedZ] = useState<number>(zIndex ?? 1500);
  const [sizeOverride, setSizeOverride] = useState<{ width?: number; height?: number }>({});
  const [okLoading, setOkLoading] = useState(false);

  function close() {
    if (okLoading) return;
    onOpenChange(false);
  }

  useLayoutEffect(() => {
    if (open) {
      setMounted(true);
      const id = requestAnimationFrame(() => setState('open'));
      return () => cancelAnimationFrame(id);
    }
    if (mounted) {
      setState('closed');
      const t = setTimeout(() => setMounted(false), ANIMATION_MS);
      return () => clearTimeout(t);
    }
    return undefined;
  }, [open, mounted]);

  useEffect(() => {
    if (!mounted || state !== 'open') return;
    setSizeOverride({});
    setOkLoading(false);
    stackEntryRef.current = pushDrawer(close);
    setComputedZ(zIndex ?? stackEntryRef.current.zIndex);
    return () => {
      stackEntryRef.current?.release();
      stackEntryRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mounted, state]);

  useEffect(() => {
    if (!mounted || state !== 'open') return;
    if (mask) lockBodyScroll();
    if (panelRef.current) trapRef.current = trapFocus(panelRef.current);
    const handler = (e: globalThis.KeyboardEvent) => {
      if (e.key === 'Escape' && closeOnEsc && topMostDrawerCloseFn() === close) {
        e.stopPropagation();
        if (!okLoading) onOpenChange(false);
      }
    };
    if (typeof window !== 'undefined') window.addEventListener('keydown', handler, true);
    return () => {
      trapRef.current?.release();
      trapRef.current = null;
      if (mask) unlockBodyScroll();
      if (typeof window !== 'undefined') window.removeEventListener('keydown', handler, true);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mounted, state, closeOnEsc, okLoading, mask]);

  async function doOk() {
    if (onBeforeOk) {
      setOkLoading(true);
      try {
        const r = await onBeforeOk();
        if (r === false) return;
      } catch {
        return;
      } finally {
        setOkLoading(false);
      }
    }
    onOk?.();
    onOpenChange(false);
  }
  function doCancel() {
    if (okLoading) return;
    onCancel?.();
    onOpenChange(false);
  }

  // resize from inner edge
  const resizeRef = useRef<{ startX: number; startY: number; w: number; h: number } | null>(null);
  const onResizePointerDown = (e: ReactPointerEvent) => {
    if (!resizable || !panelRef.current) return;
    e.preventDefault();
    e.stopPropagation();
    const rect = panelRef.current.getBoundingClientRect();
    resizeRef.current = { startX: e.clientX, startY: e.clientY, w: rect.width, h: rect.height };
    (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
  };
  const onResizePointerMove = (e: ReactPointerEvent) => {
    if (!resizeRef.current) return;
    const dx = e.clientX - resizeRef.current.startX;
    const dy = e.clientY - resizeRef.current.startY;
    if (placement === 'right') setSizeOverride({ width: Math.max(240, resizeRef.current.w - dx) });
    else if (placement === 'left') setSizeOverride({ width: Math.max(240, resizeRef.current.w + dx) });
    else if (placement === 'bottom') setSizeOverride({ height: Math.max(160, resizeRef.current.h - dy) });
    else setSizeOverride({ height: Math.max(160, resizeRef.current.h + dy) });
  };
  const onResizePointerEnd = () => {
    resizeRef.current = null;
  };

  const isBottom = placement === 'bottom';
  const effectiveGrabber = (showGrabber ?? isBottom) && isBottom;
  const effectiveDismissible = (dismissible ?? isBottom) && isBottom && !resizable;
  const grabberRef = useRef<HTMLDivElement | null>(null);
  const [dismissOffset, setDismissOffset] = useState(0);

  useDrag(grabberRef, {
    axis: 'y',
    bounds: { min: 0 },
    onMove(s) {
      if (!effectiveDismissible) return;
      setDismissOffset(s.dy);
    },
    onEnd(s) {
      if (!effectiveDismissible) return;
      const panelH = panelRef.current?.getBoundingClientRect().height ?? 200;
      const past = s.dy > panelH / 3;
      const fast = s.vy > 0.3;
      setDismissOffset(0);
      if (past || fast) close();
    },
  });

  const panelStyle = useMemo<CSSProperties>(() => {
    const out: CSSProperties = {};
    const isHoriz = placement === 'left' || placement === 'right';
    if (isHoriz) {
      if (width != null) {
        out.maxWidth = typeof width === 'number' ? `${width}px` : width;
        out.width = '100%';
      }
      if (sizeOverride.width) {
        out.maxWidth = `${sizeOverride.width}px`;
        out.width = '100%';
      }
    } else {
      if (height != null) {
        out.maxHeight = typeof height === 'number' ? `${height}px` : height;
        out.height = '100%';
      }
      if (sizeOverride.height) {
        out.maxHeight = `${sizeOverride.height}px`;
        out.height = '100%';
      }
    }
    if (!mask) out.pointerEvents = 'auto';
    if (effectiveDismissible && dismissOffset > 0) {
      out.transform = `translateY(${dismissOffset}px)`;
      out.transition = 'none';
    }
    return out;
  }, [placement, width, height, sizeOverride, mask, effectiveDismissible, dismissOffset]);

  const overlayStyle = useMemo<CSSProperties>(() => {
    const out: CSSProperties = { zIndex: computedZ };
    if (!mask) {
      out.background = 'transparent';
      out.pointerEvents = 'none';
    }
    return out;
  }, [computedZ, mask]);

  function onOverlayClick(e: MouseEvent<HTMLDivElement>) {
    if (!closeOnOverlay || okLoading) return;
    if (e.target === e.currentTarget) close();
  }

  if (!mounted) return null;
  if (typeof document === 'undefined') return null;

  const okBtnVariant = tone === 'error' ? 'danger' : okVariant;
  const showHeader = title || header || tone !== 'default';

  const node = (
    <div
      data-cf-drawer=""
      data-state={state}
      className={[
        'cf-drawer__overlay',
        `cf-drawer__overlay--${placement}`,
        tone !== 'default' ? `cf-drawer__overlay--tone-${tone}` : '',
        !mask ? 'cf-drawer__overlay--no-mask' : '',
      ]
        .filter(Boolean)
        .join(' ')}
      style={overlayStyle}
      role="presentation"
      onClick={onOverlayClick}
    >
      <div
        ref={panelRef}
        className={[
          'cf-drawer__panel',
          `cf-drawer__panel--${placement}`,
          `cf-drawer__panel--${size}`,
          resizable ? 'is-resizable' : '',
        ]
          .filter(Boolean)
          .join(' ')}
        style={panelStyle}
        role="dialog"
        aria-modal="true"
        aria-labelledby={title ? 'cf-drawer-title' : undefined}
        aria-describedby={description ? 'cf-drawer-desc' : undefined}
        tabIndex={-1}
      >
        {effectiveGrabber && (
          <div
            ref={grabberRef}
            className={['cf-drawer__grabber', effectiveDismissible ? 'is-dismissible' : '']
              .filter(Boolean)
              .join(' ')}
            aria-hidden
          >
            <span className="cf-drawer__grabber-bar" />
          </div>
        )}
        {showHeader && (
          <div className="cf-drawer__header">
            {tone !== 'default' && (
              <span className="cf-drawer__tone-icon" aria-hidden>
                <svg viewBox="0 0 24 24" width={20} height={20}>
                  <path
                    d={(DRAWER_TONE_ICON_PATH as Record<string, string>)[tone]}
                    fill="currentColor"
                  />
                </svg>
              </span>
            )}
            <div className="cf-drawer__title-block">
              {(title || !header) && (
                <h2 id="cf-drawer-title" className="cf-drawer__title">
                  {header ?? title}
                </h2>
              )}
              {description && (
                <p id="cf-drawer-desc" className="cf-drawer__desc">
                  {description}
                </p>
              )}
            </div>
          </div>
        )}
        {showClose && (
          <button
            type="button"
            className="cf-drawer__close"
            aria-label="Close"
            disabled={okLoading}
            onClick={close}
          >
            <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round">
              <path d="M4 4l8 8M12 4l-8 8" />
            </svg>
          </button>
        )}

        <div className="cf-drawer__body">{children}</div>

        {(footer || okText || cancelText) && (
          <div className="cf-drawer__footer" data-align={footerAlign}>
            {typeof footer === 'function' ? (
              footer({ ok: doOk, cancel: doCancel, loading: okLoading })
            ) : footer ? (
              footer
            ) : (
              <>
                {cancelText && (
                  <button
                    type="button"
                    className="cf-drawer__footer-btn cf-drawer__footer-btn--secondary"
                    disabled={okLoading}
                    onClick={doCancel}
                  >
                    {cancelText}
                  </button>
                )}
                {okText && (
                  <button
                    type="button"
                    className={[
                      'cf-drawer__footer-btn',
                      `cf-drawer__footer-btn--${okBtnVariant}`,
                      okLoading ? 'is-loading' : '',
                    ]
                      .filter(Boolean)
                      .join(' ')}
                    disabled={okLoading}
                    onClick={doOk}
                  >
                    {okLoading && <span className="cf-drawer__footer-spinner" />}
                    {okText}
                  </button>
                )}
              </>
            )}
          </div>
        )}

        {resizable && (
          <span
            className={`cf-drawer__resize-handle cf-drawer__resize-handle--${placement}`}
            onPointerDown={onResizePointerDown}
            onPointerMove={onResizePointerMove}
            onPointerUp={onResizePointerEnd}
            onPointerCancel={onResizePointerEnd}
          />
        )}
      </div>
    </div>
  );

  return createPortal(node, container ?? document.body);
}

// packages/vue/src/drawer/Drawer.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { useDrag } from '../composables/useDrag';
import {
  trapFocus,
  lockBodyScroll,
  unlockBodyScroll,
  type FocusTrap,
} from '../modal/dom';
import {
  pushDrawer,
  topMostDrawerCloseFn,
  toneClass,
  DRAWER_TONE_ICON_PATH,
  type DrawerProps,
  type DrawerTone,
} from './variants';

const props = withDefaults(defineProps<DrawerProps>(), {
  open: false,
  placement: 'right',
  size: 'md',
  tone: 'default',
  closeOnOverlay: true,
  closeOnEsc: true,
  showClose: true,
  resizable: false,
  mask: true,
  footerAlign: 'end',
  okVariant: 'primary',
  to: 'body',
});

const isBottom = computed(() => props.placement === 'bottom');
const effectiveGrabber = computed(() => (props.showGrabber ?? isBottom.value) && isBottom.value);
const effectiveDismissible = computed(
  () => (props.dismissible ?? isBottom.value) && isBottom.value && !props.resizable,
);
const dismissOffset = ref(0);
const grabberRef = ref<HTMLDivElement | null>(null);

const emit = defineEmits<{
  (e: 'update:open', value: boolean): void;
  (e: 'close'): void;
  (e: 'ok'): void;
  (e: 'cancel'): void;
}>();

const panelRef = ref<HTMLDivElement | null>(null);
let trap: FocusTrap | null = null;
let stackEntry: { zIndex: number; release: () => void } | null = null;

const computedZ = ref<number>(props.zIndex ?? 1500);
const canRender = ref(false);
const sizeOverride = ref<{ width?: number; height?: number }>({});
const okLoading = ref(false);

function close() {
  if (okLoading.value) return;
  emit('update:open', false);
  emit('close');
}

function onOverlayClick(e: MouseEvent) {
  if (!props.closeOnOverlay) return;
  if (okLoading.value) return;
  if (e.target === e.currentTarget) close();
}

function onKeyDown(e: KeyboardEvent) {
  if (e.key === 'Escape' && props.closeOnEsc) {
    if (topMostDrawerCloseFn() === close) {
      e.stopPropagation();
      close();
    }
  }
}

async function onOk() {
  if (props.onBeforeOk) {
    okLoading.value = true;
    try {
      const r = await props.onBeforeOk();
      if (r === false) return;
    } catch {
      return;
    } finally {
      okLoading.value = false;
    }
  }
  emit('ok');
  emit('update:open', false);
  emit('close');
}

function onCancel() {
  if (okLoading.value) return;
  emit('cancel');
  close();
}

onMounted(() => {
  canRender.value = true;
});

watch(
  [() => props.open, canRender],
  async ([open, ready]) => {
    if (open && ready) {
      if (props.mask) lockBodyScroll();
      stackEntry = pushDrawer(close);
      computedZ.value = props.zIndex ?? stackEntry.zIndex;
      sizeOverride.value = {};
      okLoading.value = false;
      await nextTick();
      if (panelRef.value) trap = trapFocus(panelRef.value);
      if (typeof window !== 'undefined') window.addEventListener('keydown', onKeyDown, true);
    } else if (!open) {
      trap?.release();
      trap = null;
      if (props.mask) unlockBodyScroll();
      stackEntry?.release();
      stackEntry = null;
      if (typeof window !== 'undefined') window.removeEventListener('keydown', onKeyDown, true);
    }
  },
);

onBeforeUnmount(() => {
  if (props.open) {
    trap?.release();
    if (props.mask) unlockBodyScroll();
    stackEntry?.release();
    if (typeof window !== 'undefined') window.removeEventListener('keydown', onKeyDown, true);
  }
});

/* resize from inner edge */
interface ResizeState { startX: number; startY: number; w: number; h: number; }
const resize = ref<ResizeState | null>(null);

function onResizePointerDown(e: PointerEvent) {
  if (!props.resizable || !panelRef.value) return;
  e.preventDefault();
  e.stopPropagation();
  const rect = panelRef.value.getBoundingClientRect();
  resize.value = { startX: e.clientX, startY: e.clientY, w: rect.width, h: rect.height };
  (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
}
function onResizePointerMove(e: PointerEvent) {
  if (!resize.value) return;
  const dx = e.clientX - resize.value.startX;
  const dy = e.clientY - resize.value.startY;
  if (props.placement === 'right') {
    sizeOverride.value = { width: Math.max(240, resize.value.w - dx) };
  } else if (props.placement === 'left') {
    sizeOverride.value = { width: Math.max(240, resize.value.w + dx) };
  } else if (props.placement === 'bottom') {
    sizeOverride.value = { height: Math.max(160, resize.value.h - dy) };
  } else {
    sizeOverride.value = { height: Math.max(160, resize.value.h + dy) };
  }
}
function onResizePointerEnd() {
  resize.value = null;
}

/* dismissible swipe-down on grabber (placement='bottom' only) */
useDrag(grabberRef, {
  axis: 'y',
  bounds: { min: 0 },
  onMove(s) {
    if (!effectiveDismissible.value) return;
    dismissOffset.value = s.dy;
  },
  onEnd(s) {
    if (!effectiveDismissible.value) return;
    const panelH = panelRef.value?.getBoundingClientRect().height ?? 200;
    const past = s.dy > panelH / 3;
    const fast = s.vy > 0.3;
    if (past || fast) {
      dismissOffset.value = 0;
      close();
    } else {
      dismissOffset.value = 0;
    }
  },
});

/* panel style */
const panelStyle = computed(() => {
  const out: Record<string, string | undefined> = {};
  if (props.placement === 'left' || props.placement === 'right') {
    if (props.width != null) {
      out.maxWidth = typeof props.width === 'number' ? `${props.width}px` : props.width;
      out.width = '100%';
    }
    if (sizeOverride.value.width) {
      out.maxWidth = `${sizeOverride.value.width}px`;
      out.width = '100%';
    }
  } else {
    if (props.height != null) {
      out.maxHeight = typeof props.height === 'number' ? `${props.height}px` : props.height;
      out.height = '100%';
    }
    if (sizeOverride.value.height) {
      out.maxHeight = `${sizeOverride.value.height}px`;
      out.height = '100%';
    }
  }
  if (effectiveDismissible.value && dismissOffset.value > 0) {
    out.transform = `translateY(${dismissOffset.value}px)`;
    out.transition = 'none';
  }
  return out;
});

const overlayStyle = computed<Record<string, string | undefined>>(() => {
  const out: Record<string, string | undefined> = { zIndex: String(computedZ.value) };
  if (!props.mask) {
    out.background = 'transparent';
    out.pointerEvents = 'none';
  }
  return out;
});

const panelPointer = computed<Record<string, string>>(() => {
  const out: Record<string, string> = {};
  if (!props.mask) out.pointerEvents = 'auto';
  return out;
});

function toneIconPath(t: DrawerTone): string {
  return t === 'default' ? '' : (DRAWER_TONE_ICON_PATH as Record<string, string>)[t];
}

defineExpose({ close, ok: onOk });
</script>

<template>
  <Teleport v-if="canRender" :to="to">
    <Transition :name="`cf-drawer-${placement}`" appear>
      <div
        v-if="open"
        :class="['cf-drawer__overlay', `cf-drawer__overlay--${placement}`, toneClass(tone), !mask && 'cf-drawer__overlay--no-mask']"
        :style="overlayStyle"
        role="presentation"
        @click="onOverlayClick"
      >
        <div
          ref="panelRef"
          :class="[
            'cf-drawer__panel',
            `cf-drawer__panel--${placement}`,
            `cf-drawer__panel--${size}`,
            resizable && 'is-resizable',
          ]"
          :style="{ ...panelStyle, ...(panelPointer || {}) }"
          role="dialog"
          aria-modal="true"
          :aria-labelledby="title ? 'cf-drawer-title' : undefined"
          :aria-describedby="description ? 'cf-drawer-desc' : undefined"
          tabindex="-1"
        >
          <div
            v-if="effectiveGrabber"
            ref="grabberRef"
            class="cf-drawer__grabber"
            :class="effectiveDismissible && 'is-dismissible'"
            aria-hidden="true"
          >
            <span class="cf-drawer__grabber-bar" />
          </div>
          <div
            v-if="title || $slots.header || tone !== 'default'"
            class="cf-drawer__header"
          >
            <span v-if="tone !== 'default'" class="cf-drawer__tone-icon" aria-hidden="true">
              <svg viewBox="0 0 24 24" width="20" height="20"><path :d="toneIconPath(tone)" fill="currentColor" /></svg>
            </span>
            <div class="cf-drawer__title-block">
              <h2 v-if="title || !$slots.header" id="cf-drawer-title" class="cf-drawer__title">
                <slot name="header">{{ title }}</slot>
              </h2>
              <p v-if="description" id="cf-drawer-desc" class="cf-drawer__desc">{{ description }}</p>
            </div>
          </div>
          <button
            v-if="showClose"
            type="button"
            class="cf-drawer__close"
            aria-label="关闭"
            :disabled="okLoading"
            @click="close"
          >
            <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round">
              <path d="M4 4l8 8M12 4l-8 8" />
            </svg>
          </button>
          <div class="cf-drawer__body">
            <slot />
          </div>
          <div
            v-if="$slots.footer || okText || cancelText"
            class="cf-drawer__footer"
            :data-align="footerAlign"
          >
            <slot name="footer" :ok="onOk" :cancel="onCancel" :loading="okLoading">
              <button
                v-if="cancelText"
                type="button"
                class="cf-drawer__footer-btn cf-drawer__footer-btn--secondary"
                :disabled="okLoading"
                @click="onCancel"
              >
                {{ cancelText }}
              </button>
              <button
                v-if="okText"
                type="button"
                :class="['cf-drawer__footer-btn', `cf-drawer__footer-btn--${tone === 'error' ? 'danger' : okVariant}`, okLoading && 'is-loading']"
                :disabled="okLoading"
                @click="onOk"
              >
                <span v-if="okLoading" class="cf-drawer__footer-spinner" />
                {{ okText }}
              </button>
            </slot>
          </div>
          <span
            v-if="resizable"
            :class="['cf-drawer__resize-handle', `cf-drawer__resize-handle--${placement}`]"
            @pointerdown="onResizePointerDown"
            @pointermove="onResizePointerMove"
            @pointerup="onResizePointerEnd"
            @pointercancel="onResizePointerEnd"
          />
        </div>
      </div>
    </Transition>
  </Teleport>
</template>
