// packages/react/src/result/Result.tsx
import { StatusIllustration } from '../statusillustration/StatusIllustration';
import type { StatusIllustrationVariant } from '../statusillustration/variants';
import { resultClass, resultDefaultTitle, type ResultProps, type ResultStatus } from './variants';

function statusToIllustration(status: ResultStatus): StatusIllustrationVariant {
  switch (status) {
    case 'success': return 'success';
    case 'warning': return 'warning';
    case 'error': return 'error';
    case '404': return 'not-found';
    case '403': return 'forbidden';
    case '500': return 'server-error';
    case 'info':
    default:
      return 'info';
  }
}

export function Result(props: ResultProps) {
  const {
    status = 'info',
    title,
    description,
    image,
    imageAlt = '',
    icon,
    extra,
    size = 'md',
    className,
    children,
  } = props;
  const finalTitle = title ?? resultDefaultTitle(status);
  const visual = icon ?? (
    image
      ? <img className="cf-result__image" src={image} alt={imageAlt} />
      : <StatusIllustration variant={statusToIllustration(status)} size={size} />
  );

  return (
    <div className={resultClass({ status, size, className })}>
      <div className="cf-result__icon">
        {visual}
      </div>
      <div className="cf-result__title">{finalTitle}</div>
      {description ? <div className="cf-result__description">{description}</div> : null}
      {extra ? <div className="cf-result__extra">{extra}</div> : null}
      {children}
    </div>
  );
}

// packages/vue/src/result/Result.vue
<script setup lang="ts">
import { computed } from 'vue';
import { resultClass, resultDefaultTitle, type ResultProps } from './variants';
import StatusIllustration from '../statusillustration/StatusIllustration.vue';
import type { StatusIllustrationVariant } from '../statusillustration/variants';

const props = withDefaults(defineProps<ResultProps>(), {
  status: 'info',
  imageAlt: '',
  size: 'md',
});

const cls = computed(() =>
  resultClass({ status: props.status, size: props.size, className: props.className }),
);
const finalTitle = computed(() => props.title ?? resultDefaultTitle(props.status));

const illustrationVariant = computed<StatusIllustrationVariant>(() => {
  switch (props.status) {
    case 'success': return 'success';
    case 'warning': return 'warning';
    case 'error': return 'error';
    case '404': return 'not-found';
    case '403': return 'forbidden';
    case '500': return 'server-error';
    case 'info':
    default:
      return 'info';
  }
});
</script>

<template>
  <div :class="cls">
    <div class="cf-result__icon">
      <slot name="icon">
        <img v-if="image" class="cf-result__image" :src="image" :alt="imageAlt" />
        <StatusIllustration v-else :variant="illustrationVariant" :size="size" />
      </slot>
    </div>
    <div class="cf-result__title">
      <slot name="title">{{ finalTitle }}</slot>
    </div>
    <div v-if="$slots.description || description" class="cf-result__description">
      <slot name="description">{{ description }}</slot>
    </div>
    <div v-if="$slots.extra" class="cf-result__extra">
      <slot name="extra" />
    </div>
  </div>
</template>
