// packages/vue/src/switch/Switch.vue
<script setup lang="ts">
import { computed } from 'vue';
import { switchClass, type SwitchProps } from './variants';

const props = withDefaults(defineProps<SwitchProps>(), {
  modelValue: false,
  size: 'md',
  disabled: false,
  loading: false,
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void;
  (e: 'change', value: boolean): void;
}>();

const cls = computed(() =>
  switchClass({
    size: props.size,
    disabled: props.disabled,
    loading: props.loading,
  }),
);

const isInactive = computed(() => props.disabled || props.loading);

function onChange(e: Event) {
  if (isInactive.value) return;
  const v = (e.target as HTMLInputElement).checked;
  emit('update:modelValue', v);
  emit('change', v);
}
</script>

<template>
  <label :class="cls">
    <input
      class="ck-switch__input"
      type="checkbox"
      :checked="modelValue"
      :disabled="isInactive"
      :name="name"
      :id="id"
      role="switch"
      :aria-checked="modelValue"
      @change="onChange"
    />
    <span class="ck-switch__track">
      <span class="ck-switch__thumb" />
    </span>
    <span v-if="$slots.default"><slot /></span>
  </label>
</template>

// packages/react/src/switch/Switch.tsx
import { forwardRef, useState, type ChangeEvent } from 'react';
import { switchClass, type SwitchProps } from './variants';

export const Switch = forwardRef<HTMLInputElement, SwitchProps>(function Switch(
  props,
  ref,
) {
  const {
    size = 'md',
    loading = false,
    disabled = false,
    checked,
    defaultChecked,
    onChange,
    onCheckedChange,
    className,
    children,
    ...rest
  } = props;

  const isControlled = checked !== undefined;
  const [internal, setInternal] = useState<boolean>(!!defaultChecked);
  const current = isControlled ? !!checked : internal;
  const isInactive = disabled || loading;

  function handleChange(e: ChangeEvent<HTMLInputElement>) {
    if (isInactive) return;
    if (!isControlled) setInternal(e.target.checked);
    onCheckedChange?.(e.target.checked, {
      event: e,
      checked: e.target.checked,
      name: e.target.name || undefined,
    });
    onChange?.(e);
  }

  return (
    <label className={switchClass({ size, disabled, loading, className })}>
      <input
        ref={ref}
        type="checkbox"
        className="cf-switch__input"
        checked={current}
        disabled={isInactive}
        role="switch"
        aria-checked={current}
        onChange={handleChange}
        {...rest}
      />
      <span className="cf-switch__track">
        <span className="cf-switch__thumb" />
      </span>
      {children ? <span>{children}</span> : null}
    </label>
  );
});
