// packages/react/src/radio/RadioGroup.tsx
import { createContext, useState } from 'react';
import {
  radioGroupClass,
  type RadioChangeMeta,
  type RadioGroupProps,
  type RadioSize,
  type RadioValue,
} from './variants';

export interface RadioGroupContextValue {
  value: RadioValue;
  name?: string;
  size: RadioSize;
  disabled: boolean;
  select(v: RadioValue, meta: RadioChangeMeta): void;
}

export const RadioGroupContext = createContext<RadioGroupContextValue | null>(null);

export function RadioGroup(props: RadioGroupProps) {
  const {
    value,
    defaultValue = null,
    name,
    size = 'md',
    disabled = false,
    direction = 'row',
    onChange,
    children,
    className,
  } = props;

  const isControlled = value !== undefined;
  const [internal, setInternal] = useState<RadioValue>(defaultValue);
  const current = isControlled ? (value as RadioValue) : internal;

  function select(v: RadioValue, meta: RadioChangeMeta) {
    if (!isControlled) setInternal(v);
    onChange?.(v, meta);
  }

  return (
    <div
      role="radiogroup"
      className={radioGroupClass({ direction, className })}
    >
      <RadioGroupContext.Provider
        value={{ value: current, name, size, disabled, select }}
      >
        {children}
      </RadioGroupContext.Provider>
    </div>
  );
}

// packages/vue/src/radio/RadioGroup.vue
<script setup lang="ts">
import { computed, provide, reactive } from 'vue';
import {
  radioGroupClass,
  radioGroupKey,
  type RadioChangeMeta,
  type RadioGroupProps,
  type RadioValue,
} from './variants';

const props = withDefaults(defineProps<RadioGroupProps>(), {
  modelValue: null,
  size: 'md',
  disabled: false,
  direction: 'row',
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: RadioValue): void;
  (e: 'change', value: RadioValue, meta: RadioChangeMeta): void;
}>();

const cls = computed(() => radioGroupClass({ direction: props.direction }));

const ctxValue = reactive({
  get current(): RadioValue {
    return props.modelValue;
  },
});

provide(radioGroupKey, {
  value: ctxValue,
  name: props.name,
  size: props.size,
  disabled: props.disabled,
  select(v: RadioValue, meta: RadioChangeMeta) {
    emit('update:modelValue', v);
    emit('change', v, meta);
  },
});
</script>

<template>
  <div :class="cls" role="radiogroup">
    <slot />
  </div>
</template>
