// packages/vue/src/countdown/CountDown.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import {
  countDownClass,
  formatRemaining,
  targetMs,
  type CountDownProps,
} from './variants';

const props = withDefaults(defineProps<CountDownProps>(), {
  format: 'HH:mm:ss',
  interval: 1000,
  size: 'md',
});

const emit = defineEmits<{ finish: []; change: [remaining: number] }>();

const remaining = ref(0);
let timer: ReturnType<typeof setInterval> | null = null;

function clear() {
  if (timer) clearInterval(timer);
  timer = null;
}

function start() {
  clear();
  if (typeof window === 'undefined') return;
  const tms = targetMs(props.target);
  if (!tms) return;
  function tick() {
    const r = tms - Date.now();
    if (r <= 0) {
      remaining.value = 0;
      emit('change', 0);
      emit('finish');
      clear();
    } else {
      remaining.value = r;
      emit('change', r);
    }
  }
  tick();
  timer = setInterval(tick, props.interval);
}

watch(() => [props.target, props.interval], start, { immediate: true });
onBeforeUnmount(clear);

const cls = computed(() => countDownClass({ size: props.size, className: props.className }));
const text = computed(() => formatRemaining(remaining.value, props.format));
</script>

<template>
  <span :class="cls">{{ text }}</span>
</template>

// packages/react/src/countdown/CountDown.tsx
import { useEffect, useState } from 'react';
import {
  countDownClass,
  formatRemaining,
  targetMs,
  type CountDownProps,
} from './variants';

export function CountDown({
  target,
  format = 'HH:mm:ss',
  interval = 1000,
  size = 'md',
  className,
  onFinish,
  onChange,
}: CountDownProps) {
  const [remaining, setRemaining] = useState(0);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    const tms = targetMs(target);
    if (!tms) return;
    let timer: ReturnType<typeof setInterval> | null = null;
    const tick = () => {
      const r = tms - Date.now();
      if (r <= 0) {
        setRemaining(0);
        onChange?.(0);
        onFinish?.();
        if (timer) clearInterval(timer);
      } else {
        setRemaining(r);
        onChange?.(r);
      }
    };
    tick();
    timer = setInterval(tick, interval);
    return () => {
      if (timer) clearInterval(timer);
    };
  }, [target, interval, onChange, onFinish]);

  const cls = countDownClass({ size, className });
  return <span className={cls}>{formatRemaining(remaining, format)}</span>;
}
