// packages/react/src/phoneinput/PhoneInput.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import {
  defaultCountries,
  type CountryCode,
  type PhoneInputProps,
} from './variants';

export function PhoneInput(props: PhoneInputProps) {
  const {
    value,
    onChange,
    country = 'CN',
    onCountryChange,
    countries,
    size = 'md',
    placeholder = '请输入手机号',
    disabled = false,
    error = false,
  } = props;

  const list = countries ?? defaultCountries;
  const current = list.find((c) => c.code === country) ?? list[0];

  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState('');
  const rootRef = useRef<HTMLDivElement | null>(null);

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return list;
    return list.filter(
      (c) =>
        c.label.toLowerCase().includes(q) ||
        c.code.toLowerCase().includes(q) ||
        c.dial.includes(q),
    );
  }, [list, search]);

  useEffect(() => {
    if (!open) return;
    const onDoc = (e: globalThis.MouseEvent) => {
      if (!rootRef.current) return;
      if (!rootRef.current.contains(e.target as Node)) {
        setOpen(false);
        setSearch('');
      }
    };
    document.addEventListener('mousedown', onDoc);
    return () => document.removeEventListener('mousedown', onDoc);
  }, [open]);

  const cls = [
    'cf-phoneinput',
    `cf-phoneinput--${size}`,
    open && 'is-open',
    disabled && 'is-disabled',
    error && 'is-error',
  ]
    .filter(Boolean)
    .join(' ');

  const pickCountry = (c: CountryCode) => {
    onCountryChange?.(c.code);
    setOpen(false);
    setSearch('');
  };

  return (
    <div ref={rootRef} className={cls}>
      <button
        type="button"
        className="cf-phoneinput__cc"
        disabled={disabled}
        aria-haspopup="listbox"
        aria-expanded={open}
        onClick={() => !disabled && setOpen((v) => !v)}
      >
        <span className="cf-phoneinput__cc-code">+{current.dial}</span>
        <svg
          viewBox="0 0 16 16"
          aria-hidden="true"
          className="cf-phoneinput__caret"
        >
          <path
            d="M4 6l4 4 4-4"
            stroke="currentColor"
            strokeWidth={1.6}
            fill="none"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </svg>
      </button>
      <input
        type="tel"
        className="cf-phoneinput__input"
        value={value}
        placeholder={placeholder}
        disabled={disabled}
        onChange={(e) => onChange(e.target.value)}
      />
      {open ? (
        <div className="cf-phoneinput__menu">
          <div className="cf-phoneinput__search">
            <input
              type="text"
              placeholder="搜索国家 / 区号…"
              value={search}
              autoFocus
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>
          <ul className="cf-phoneinput__list" role="listbox">
            {filtered.map((c) => (
              <li
                key={c.code}
                role="option"
                aria-selected={c.code === current.code}
                className={[
                  'cf-phoneinput__opt',
                  c.code === current.code && 'is-selected',
                ]
                  .filter(Boolean)
                  .join(' ')}
                onMouseDown={(e) => {
                  e.preventDefault();
                  pickCountry(c);
                }}
              >
                <span className="cf-phoneinput__opt-label">{c.label}</span>
                <span className="cf-phoneinput__opt-dial">+{c.dial}</span>
              </li>
            ))}
            {filtered.length === 0 ? (
              <li className="cf-phoneinput__empty">无匹配国家</li>
            ) : null}
          </ul>
        </div>
      ) : null}
    </div>
  );
}

// packages/vue/src/phoneinput/PhoneInput.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue';
import {
  defaultCountries,
  type CountryCode,
  type PhoneInputProps,
} from './variants';

const props = withDefaults(defineProps<PhoneInputProps>(), {
  modelValue: '',
  country: 'CN',
  size: 'md',
  placeholder: '请输入手机号',
  disabled: false,
  error: false,
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void;
  (e: 'update:country', value: string): void;
}>();

const open = ref(false);
const search = ref('');
const rootRef = ref<HTMLDivElement | null>(null);

const countries = computed<CountryCode[]>(
  () => props.countries ?? defaultCountries,
);
const current = computed<CountryCode>(
  () =>
    countries.value.find((c) => c.code === props.country) ?? countries.value[0],
);

const filtered = computed(() => {
  const q = search.value.trim().toLowerCase();
  if (!q) return countries.value;
  return countries.value.filter(
    (c) =>
      c.label.toLowerCase().includes(q) ||
      c.code.toLowerCase().includes(q) ||
      c.dial.includes(q),
  );
});

const cls = computed(() => [
  'cf-phoneinput',
  `cf-phoneinput--${props.size}`,
  open.value && 'is-open',
  props.disabled && 'is-disabled',
  props.error && 'is-error',
]);

function toggleMenu() {
  if (props.disabled) return;
  open.value = !open.value;
  if (open.value) document.addEventListener('mousedown', onDocClick);
  else closeMenu();
}

function closeMenu() {
  open.value = false;
  search.value = '';
  document.removeEventListener('mousedown', onDocClick);
}

function onDocClick(e: MouseEvent) {
  if (!rootRef.value) return;
  if (!rootRef.value.contains(e.target as Node)) closeMenu();
}

function pickCountry(c: CountryCode) {
  emit('update:country', c.code);
  closeMenu();
}

function onInput(e: Event) {
  emit('update:modelValue', (e.target as HTMLInputElement).value);
}

onBeforeUnmount(() =>
  document.removeEventListener('mousedown', onDocClick),
);
</script>

<template>
  <div ref="rootRef" :class="cls">
    <button
      type="button"
      class="cf-phoneinput__cc"
      :disabled="disabled"
      :aria-haspopup="'listbox'"
      :aria-expanded="open"
      @click="toggleMenu"
    >
      <span class="cf-phoneinput__cc-code">+{{ current.dial }}</span>
      <svg viewBox="0 0 16 16" aria-hidden="true" class="cf-phoneinput__caret">
        <path
          d="M4 6l4 4 4-4"
          stroke="currentColor"
          stroke-width="1.6"
          fill="none"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </button>
    <input
      type="tel"
      class="cf-phoneinput__input"
      :value="modelValue"
      :placeholder="placeholder"
      :disabled="disabled"
      @input="onInput"
    />
    <div v-if="open" class="cf-phoneinput__menu">
      <div class="cf-phoneinput__search">
        <input
          v-model="search"
          type="text"
          placeholder="搜索国家 / 区号…"
          autofocus
        />
      </div>
      <ul class="cf-phoneinput__list" role="listbox">
        <li
          v-for="c in filtered"
          :key="c.code"
          class="cf-phoneinput__opt"
          :class="{ 'is-selected': c.code === current.code }"
          role="option"
          :aria-selected="c.code === current.code"
          @mousedown.prevent="pickCountry(c)"
        >
          <span class="cf-phoneinput__opt-label">{{ c.label }}</span>
          <span class="cf-phoneinput__opt-dial">+{{ c.dial }}</span>
        </li>
        <li v-if="!filtered.length" class="cf-phoneinput__empty">
          无匹配国家
        </li>
      </ul>
    </div>
  </div>
</template>
