// packages/react/src/affix/Affix.tsx
import { useEffect, useLayoutEffect, useRef, useState, type CSSProperties } from 'react';
import { affixClass, type AffixProps } from './variants';

export function Affix(props: AffixProps) {
  const { offsetTop, offsetBottom, target, zIndex = 100, className, onChange, children } = props;
  const [fixed, setFixed] = useState(false);
  const [innerStyle, setInnerStyle] = useState<CSSProperties>({});
  const [placeholderStyle, setPlaceholderStyle] = useState<CSSProperties | undefined>(undefined);
  const placeholderRef = useRef<HTMLDivElement | null>(null);
  const scopeRef = useRef<Window | Element>(window);

  const update = () => {
    const placeholder = placeholderRef.current;
    if (!placeholder) return;
    const rect = placeholder.getBoundingClientRect();
    const scope = scopeRef.current;

    const viewportTop = scope instanceof Window ? 0 : (scope as Element).getBoundingClientRect().top;
    const viewportBottom =
      scope instanceof Window ? window.innerHeight : (scope as Element).getBoundingClientRect().bottom;

    if (offsetTop !== undefined) {
      const shouldFix = rect.top < viewportTop + offsetTop;
      setFixed((prev) => {
        if (prev !== shouldFix) onChange?.(shouldFix);
        return shouldFix;
      });
      if (shouldFix) {
        setInnerStyle({
          position: 'fixed',
          top: viewportTop + offsetTop,
          left: rect.left,
          width: rect.width,
          zIndex,
        });
        setPlaceholderStyle({ width: rect.width, height: rect.height });
      } else {
        setInnerStyle({});
        setPlaceholderStyle(undefined);
      }
      return;
    }
    if (offsetBottom !== undefined) {
      const shouldFix = rect.bottom > viewportBottom - offsetBottom;
      setFixed((prev) => {
        if (prev !== shouldFix) onChange?.(shouldFix);
        return shouldFix;
      });
      if (shouldFix) {
        setInnerStyle({
          position: 'fixed',
          bottom:
            (scope instanceof Window ? 0 : window.innerHeight - viewportBottom) + offsetBottom,
          left: rect.left,
          width: rect.width,
          zIndex,
        });
        setPlaceholderStyle({ width: rect.width, height: rect.height });
      } else {
        setInnerStyle({});
        setPlaceholderStyle(undefined);
      }
    }
  };

  useLayoutEffect(() => {
    let scope: Window | Element = window;
    if (target) {
      const el = document.querySelector(target);
      if (el) scope = el;
    }
    scopeRef.current = scope;
    scope.addEventListener('scroll', update, { passive: true });
    window.addEventListener('resize', update);
    update();
    return () => {
      scope.removeEventListener('scroll', update);
      window.removeEventListener('resize', update);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [target, offsetTop, offsetBottom, zIndex]);

  return (
    <div
      ref={placeholderRef}
      className={affixClass({ fixed, className })}
      style={placeholderStyle}
    >
      <div style={innerStyle}>{children}</div>
    </div>
  );
}

// packages/vue/src/affix/Affix.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { affixClass, type AffixProps } from './variants';

const props = defineProps<AffixProps>();
const emit = defineEmits<{ change: [fixed: boolean] }>();

const fixed = ref(false);
const placeholder = ref<HTMLDivElement | null>(null);
const inner = ref<HTMLDivElement | null>(null);
const innerStyle = ref<Record<string, string>>({});
let scope: Window | Element | null = null;

function getViewportTop() {
  if (!scope || scope instanceof Window) return 0;
  const rect = (scope as Element).getBoundingClientRect();
  return rect.top;
}

function getViewportBottom() {
  if (!scope || scope instanceof Window) return typeof window !== 'undefined' ? window.innerHeight : 0;
  const rect = (scope as Element).getBoundingClientRect();
  return rect.bottom;
}

function update() {
  if (!placeholder.value || !inner.value) return;
  const rect = placeholder.value.getBoundingClientRect();
  const viewportTop = getViewportTop();
  const viewportBottom = getViewportBottom();

  if (props.offsetTop !== undefined) {
    const shouldFix = rect.top < viewportTop + props.offsetTop;
    if (shouldFix !== fixed.value) emit('change', shouldFix);
    fixed.value = shouldFix;
    if (shouldFix) {
      const left = scope instanceof Window ? rect.left : rect.left;
      innerStyle.value = {
        position: 'fixed',
        top: `${viewportTop + props.offsetTop}px`,
        left: `${left}px`,
        width: `${rect.width}px`,
        zIndex: String(props.zIndex ?? 100),
      };
    } else {
      innerStyle.value = {};
    }
    return;
  }

  if (props.offsetBottom !== undefined) {
    const shouldFix = rect.bottom > viewportBottom - props.offsetBottom;
    if (shouldFix !== fixed.value) emit('change', shouldFix);
    fixed.value = shouldFix;
    if (shouldFix) {
      const left = rect.left;
      innerStyle.value = {
        position: 'fixed',
        bottom: `${(scope instanceof Window ? 0 : window.innerHeight - viewportBottom) + props.offsetBottom}px`,
        left: `${left}px`,
        width: `${rect.width}px`,
        zIndex: String(props.zIndex ?? 100),
      };
    } else {
      innerStyle.value = {};
    }
  }
}

onMounted(() => {
  scope = window;
  if (props.target) {
    const el = document.querySelector(props.target);
    if (el) scope = el;
  }
  scope.addEventListener('scroll', update, { passive: true });
  window.addEventListener('resize', update);
  update();
});

onBeforeUnmount(() => {
  if (scope) scope.removeEventListener('scroll', update);
  if (typeof window !== 'undefined') window.removeEventListener('resize', update);
});

const cls = computed(() => affixClass({ fixed: fixed.value, className: props.className }));
const placeholderStyle = computed(() => {
  if (!fixed.value || !placeholder.value) return undefined;
  const rect = placeholder.value.getBoundingClientRect();
  return { width: `${rect.width}px`, height: `${rect.height}px` } as Record<string, string>;
});
</script>

<template>
  <div ref="placeholder" :class="cls" :style="placeholderStyle">
    <div ref="inner" :style="innerStyle">
      <slot />
    </div>
  </div>
</template>
