// packages/vue/src/tearofftab/TearOffTabs.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import type { TearOffTabItem, TearOffTabsProps } from './variants';

const props = withDefaults(defineProps<TearOffTabsProps>(), {
  modelValue: undefined,
  tearThreshold: 60,
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void;
  (e: 'tear-off', id: string, item: TearOffTabItem, x: number, y: number): void;
  (e: 'close', id: string, item: TearOffTabItem): void;
}>();

const activeId = computed(() =>
  props.modelValue ?? props.tabs[0]?.id ?? null,
);

const dragId = ref<string | null>(null);
const dragOffsetY = ref(0);

function setActive(id: string) {
  emit('update:modelValue', id);
}

function close(item: TearOffTabItem) {
  emit('close', item.id, item);
}

function onPointerDown(item: TearOffTabItem, e: PointerEvent) {
  dragId.value = item.id;
  dragOffsetY.value = e.clientY;
  (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
}

function onPointerMove(item: TearOffTabItem, e: PointerEvent) {
  if (dragId.value !== item.id) return;
  if (Math.abs(e.clientY - dragOffsetY.value) > props.tearThreshold) {
    emit('tear-off', item.id, item, e.clientX, e.clientY);
    dragId.value = null;
    (e.currentTarget as HTMLElement).releasePointerCapture(e.pointerId);
  }
}

function onPointerUp(e: PointerEvent) {
  dragId.value = null;
  (e.currentTarget as HTMLElement).releasePointerCapture(e.pointerId);
}
</script>

<template>
  <div class="cf-tearoff">
    <div class="cf-tearoff__bar" role="tablist">
      <div
        v-for="t in tabs"
        :key="t.id"
        :class="['cf-tearoff__tab', t.id === activeId && 'is-active']"
        role="tab"
        :aria-selected="t.id === activeId"
        :draggable="false"
        @click="setActive(t.id)"
        @pointerdown="(e) => onPointerDown(t, e)"
        @pointermove="(e) => onPointerMove(t, e)"
        @pointerup="onPointerUp"
        @pointercancel="onPointerUp"
      >
        <span class="cf-tearoff__title">{{ t.title }}</span>
        <span v-if="t.modified" class="cf-tearoff__dirty" aria-label="未保存">●</span>
        <button
          v-if="t.closable"
          type="button"
          class="cf-tearoff__close"
          aria-label="关闭"
          @click.stop="close(t)"
        >×</button>
      </div>
    </div>
    <div class="cf-tearoff__body">
      <template v-for="t in tabs" :key="t.id">
        <div v-if="t.id === activeId" class="cf-tearoff__panel">
          <slot :name="`content-${t.contentKey ?? t.id}`" />
        </div>
      </template>
    </div>
  </div>
</template>

// packages/react/src/tearofftab/TearOffTabs.tsx
import {
  Fragment,
  useRef,
  useState,
  type PointerEvent as RPointerEvent,
} from 'react';
import type { TearOffTabItem, TearOffTabsProps } from './variants';

export function TearOffTabs(props: TearOffTabsProps) {
  const {
    tabs,
    value,
    onChange,
    tearThreshold = 60,
    onTearOff,
    onClose,
    slots = {},
    className,
  } = props;

  const [localActive, setLocalActive] = useState<string | null>(
    tabs[0]?.id ?? null,
  );
  const activeId = value ?? localActive;

  const dragRef = useRef<{ id: string | null; startY: number }>({
    id: null,
    startY: 0,
  });

  const setActive = (id: string) => {
    setLocalActive(id);
    onChange?.(id);
  };

  const onPointerDown =
    (item: TearOffTabItem) => (e: RPointerEvent<HTMLDivElement>) => {
      dragRef.current = { id: item.id, startY: e.clientY };
      e.currentTarget.setPointerCapture(e.pointerId);
    };

  const onPointerMove =
    (item: TearOffTabItem) => (e: RPointerEvent<HTMLDivElement>) => {
      if (dragRef.current.id !== item.id) return;
      if (Math.abs(e.clientY - dragRef.current.startY) > tearThreshold) {
        onTearOff?.(item.id, item, e.clientX, e.clientY);
        dragRef.current.id = null;
        e.currentTarget.releasePointerCapture(e.pointerId);
      }
    };

  const onPointerUp = (e: RPointerEvent<HTMLDivElement>) => {
    dragRef.current.id = null;
    e.currentTarget.releasePointerCapture(e.pointerId);
  };

  return (
    <div className={['cf-tearoff', className].filter(Boolean).join(' ')}>
      <div className="cf-tearoff__bar" role="tablist">
        {tabs.map((t) => (
          <div
            key={t.id}
            className={[
              'cf-tearoff__tab',
              t.id === activeId && 'is-active',
            ]
              .filter(Boolean)
              .join(' ')}
            role="tab"
            aria-selected={t.id === activeId}
            onClick={() => setActive(t.id)}
            onPointerDown={onPointerDown(t)}
            onPointerMove={onPointerMove(t)}
            onPointerUp={onPointerUp}
            onPointerCancel={onPointerUp}
          >
            <span className="cf-tearoff__title">{t.title}</span>
            {t.modified ? (
              <span className="cf-tearoff__dirty" aria-label="未保存">
                ●
              </span>
            ) : null}
            {t.closable ? (
              <button
                type="button"
                className="cf-tearoff__close"
                aria-label="关闭"
                onClick={(e) => {
                  e.stopPropagation();
                  onClose?.(t.id, t);
                }}
              >
                ×
              </button>
            ) : null}
          </div>
        ))}
      </div>
      <div className="cf-tearoff__body">
        {tabs.map((t) =>
          t.id === activeId ? (
            <Fragment key={t.id}>
              <div className="cf-tearoff__panel">
                {slots[`content-${t.contentKey ?? t.id}`] ?? null}
              </div>
            </Fragment>
          ) : null,
        )}
      </div>
    </div>
  );
}
