// packages/vue/src/tabs/Tabs.vue
<script setup lang="ts">
import { computed, ref, watch, useSlots } from 'vue';
import {
  type TabsItem,
  type TabsProps,
  tabsClass,
} from './variants';

const props = withDefaults(defineProps<TabsProps>(), {
  variant: 'line',
  size: 'md',
  align: 'start',
});
const emit = defineEmits<{
  (e: 'update:modelValue', v: string): void;
  (e: 'change', v: string): void;
}>();

const slots = useSlots();

/* derive tab list from items prop OR from <Tab> child slot vnodes  */
const fallback = computed<TabsItem[]>(() => {
  if (props.items && props.items.length) return props.items;
  const nodes = slots.default?.() ?? [];
  return nodes
    .filter((n: any) => n.props && n.props.value != null)
    .map((n: any) => ({
      value: String(n.props.value),
      label: n.props.label ?? String(n.props.value),
      disabled: !!n.props.disabled,
    }));
});

const inner = ref<string>(
  props.modelValue ?? fallback.value[0]?.value ?? ''
);
watch(
  () => props.modelValue,
  (v) => {
    if (v != null) inner.value = v;
  }
);
watch(fallback, (list) => {
  if (!list.find((i) => i.value === inner.value)) {
    inner.value = list[0]?.value ?? '';
  }
});

function pick(v: string, disabled?: boolean) {
  if (disabled) return;
  inner.value = v;
  emit('update:modelValue', v);
  emit('change', v);
}

const rootClass = computed(() =>
  tabsClass({
    variant: props.variant!,
    size: props.size!,
    align: props.align!,
  })
);
</script>

<template>
  <div :class="rootClass">
    <div class="cf-tabs__list" role="tablist">
      <button
        v-for="t in fallback"
        :key="t.value"
        type="button"
        role="tab"
        class="cf-tabs__tab"
        :class="{ 'is-active': inner === t.value, 'is-disabled': t.disabled }"
        :aria-selected="inner === t.value"
        :disabled="t.disabled || undefined"
        @click="pick(t.value, t.disabled)"
      >
        {{ t.label }}
      </button>
    </div>
    <div class="cf-tabs__panels">
      <slot :active="inner" />
    </div>
  </div>
</template>

// packages/react/src/tabs/Tabs.tsx
import { useState } from 'react';
import { type TabsProps, tabsClass } from './variants';

export function Tabs(props: TabsProps) {
  const {
    value,
    defaultValue,
    items = [],
    variant = 'line',
    size = 'md',
    align = 'start',
    onChange,
    children,
  } = props;

  const controlled = value != null;
  const [inner, setInner] = useState<string>(
    defaultValue ?? items[0]?.value ?? ''
  );
  const active = controlled ? (value as string) : inner;

  function pick(v: string, disabled?: boolean) {
    if (disabled) return;
    if (!controlled) setInner(v);
    onChange?.(v);
  }

  return (
    <div className={tabsClass({ variant, size, align })}>
      <div className="ck-tabs__list" role="tablist">
        {items.map((t) => (
          <button
            key={t.value}
            type="button"
            role="tab"
            className={[
              'ck-tabs__tab',
              active === t.value ? 'is-active' : '',
              t.disabled ? 'is-disabled' : '',
            ]
              .filter(Boolean)
              .join(' ')}
            aria-selected={active === t.value}
            disabled={t.disabled || undefined}
            onClick={() => pick(t.value, t.disabled)}
          >
            {t.label}
          </button>
        ))}
      </div>
      <div className="ck-tabs__panels">
        {typeof children === 'function'
          ? (children as (a: { active: string }) => React.ReactNode)({ active })
          : children}
      </div>
    </div>
  );
}

export function TabPanel({
  value,
  active,
  children,
}: {
  value: string;
  active: string;
  children?: React.ReactNode;
}) {
  if (value !== active) return null;
  return (
    <div className="ck-tabs__panel" role="tabpanel">
      {children}
    </div>
  );
}
