// packages/react/src/statistic/Statistic.tsx
import { useEffect, useRef, useState } from 'react';
import {
  formatCountdown,
  formatNumber,
  statisticClass,
  type StatisticProps,
} from './variants';

export function Statistic(props: StatisticProps) {
  const {
    value,
    precision = 0,
    prefix,
    suffix,
    separator = ',',
    decimal = '.',
    duration = 800,
    countdown,
    format = 'HH:mm:ss',
    size = 'md',
    loading = false,
    label,
    className,
    onFinish,
  } = props;

  const [display, setDisplay] = useState(0);
  const rafRef = useRef<number | null>(null);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  function clearAnim() {
    if (rafRef.current) cancelAnimationFrame(rafRef.current);
    rafRef.current = null;
    if (timerRef.current) clearInterval(timerRef.current);
    timerRef.current = null;
  }

  useEffect(() => {
    clearAnim();
    if (countdown != null) {
      const targetMs = countdown instanceof Date ? countdown.getTime() : countdown;
      const update = () => {
        const remaining = targetMs - Date.now();
        if (remaining <= 0) {
          setDisplay(0);
          onFinish?.();
          if (timerRef.current) clearInterval(timerRef.current);
          timerRef.current = null;
          return;
        }
        setDisplay(remaining);
      };
      update();
      timerRef.current = setInterval(update, 1000);
    } else if (value != null) {
      if (duration <= 0) {
        setDisplay(value);
      } else {
        const start = display || 0;
        const change = value - start;
        const startTime = performance.now();
        const step = (now: number) => {
          const t = Math.min(1, (now - startTime) / duration);
          const eased = 1 - Math.pow(1 - t, 3);
          setDisplay(start + change * eased);
          if (t < 1) rafRef.current = requestAnimationFrame(step);
        };
        rafRef.current = requestAnimationFrame(step);
      }
    }
    return clearAnim;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value, countdown, duration]);

  const text = loading
    ? '—'
    : countdown != null
      ? formatCountdown(display, format)
      : formatNumber(display, precision, separator, decimal);

  return (
    <div className={statisticClass({ size, className })}>
      {label ? <div className="cf-statistic__label">{label}</div> : null}
      <div className="cf-statistic__value">
        {prefix ? <span className="cf-statistic__prefix">{prefix}</span> : null}
        <span className="cf-statistic__number">{text}</span>
        {suffix ? <span className="cf-statistic__suffix">{suffix}</span> : null}
      </div>
    </div>
  );
}

// packages/vue/src/statistic/Statistic.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import {
  formatCountdown,
  formatNumber,
  statisticClass,
  type StatisticProps,
} from './variants';

const props = withDefaults(defineProps<StatisticProps>(), {
  precision: 0,
  separator: ',',
  decimal: '.',
  duration: 800,
  size: 'md',
  loading: false,
  format: 'HH:mm:ss',
});

const emit = defineEmits<{ finish: [] }>();

const display = ref(0);
let raf: number | null = null;
let timer: ReturnType<typeof setInterval> | null = null;

function clearAnim() {
  if (raf) cancelAnimationFrame(raf);
  raf = null;
  if (timer) clearInterval(timer);
  timer = null;
}

function animateTo(target: number) {
  clearAnim();
  if (props.duration <= 0 || typeof window === 'undefined') {
    display.value = target;
    return;
  }
  const start = display.value || 0;
  const change = target - start;
  const startTime = performance.now();
  function step(now: number) {
    const t = Math.min(1, (now - startTime) / props.duration);
    const eased = 1 - Math.pow(1 - t, 3);
    display.value = start + change * eased;
    if (t < 1) raf = requestAnimationFrame(step);
  }
  raf = requestAnimationFrame(step);
}

function startCountdown() {
  clearAnim();
  if (props.countdown == null || typeof window === 'undefined') return;
  const targetMs = props.countdown instanceof Date ? props.countdown.getTime() : props.countdown;
  function update() {
    const remaining = targetMs - Date.now();
    if (remaining <= 0) {
      display.value = 0;
      emit('finish');
      if (timer) clearInterval(timer);
      timer = null;
      return;
    }
    display.value = remaining;
  }
  update();
  timer = setInterval(update, 1000);
}

watch(
  () => [props.value, props.countdown],
  () => {
    if (props.countdown != null) startCountdown();
    else if (props.value != null) animateTo(props.value);
  },
  { immediate: true },
);

onBeforeUnmount(clearAnim);

const text = computed(() => {
  if (props.loading) return '—';
  if (props.countdown != null) return formatCountdown(display.value, props.format);
  return formatNumber(display.value, props.precision, props.separator, props.decimal);
});

const cls = computed(() => statisticClass({ size: props.size, className: props.className }));
</script>

<template>
  <div :class="cls">
    <div v-if="label" class="cf-statistic__label">{{ label }}</div>
    <div class="cf-statistic__value">
      <span v-if="prefix" class="cf-statistic__prefix">{{ prefix }}</span>
      <span class="cf-statistic__number">{{ text }}</span>
      <span v-if="suffix" class="cf-statistic__suffix">{{ suffix }}</span>
    </div>
  </div>
</template>
