// packages/react/src/tag/Tag.tsx
import { forwardRef } from 'react';
import { tagClass, type TagProps } from './variants';

export const Tag = forwardRef<HTMLSpanElement, TagProps>(function Tag(props, ref) {
  const {
    variant = 'soft',
    size = 'md',
    tone = 'neutral',
    closable = false,
    rounded = false,
    leading,
    onClose,
    children,
    className,
    ...rest
  } = props;

  return (
    <span
      ref={ref}
      className={tagClass({ variant, size, tone, rounded, className })}
      {...rest}
    >
      {leading ? <span className="ck-tag__leading">{leading}</span> : null}
      {children}
      {closable ? (
        <button
          type="button"
          className="ck-tag__close"
          aria-label="关闭"
          onClick={onClose}
        >
          ×
        </button>
      ) : null}
    </span>
  );
});

// packages/vue/src/tag/Tag.vue
<script setup lang="ts">
import { computed } from 'vue';
import { tagClass, type TagProps } from './variants';

const props = withDefaults(defineProps<TagProps>(), {
  variant: 'soft',
  size: 'md',
  tone: 'neutral',
  closable: false,
  rounded: false,
});

const emit = defineEmits<{
  (e: 'close', ev: MouseEvent): void;
}>();

const cls = computed(() =>
  tagClass({
    variant: props.variant,
    size: props.size,
    tone: props.tone,
    rounded: props.rounded,
  }),
);
</script>

<template>
  <span :class="cls">
    <span v-if="$slots.leading" class="cf-tag__leading"><slot name="leading" /></span>
    <slot />
    <button
      v-if="closable"
      type="button"
      class="cf-tag__close"
      aria-label="关闭"
      @click="(e) => emit('close', e)"
    >×</button>
  </span>
</template>
