// packages/react/src/avatar/AvatarGroup.tsx
import type { CSSProperties } from 'react';
import type { AvatarGroupProps } from './variants';

export function AvatarGroup(props: AvatarGroupProps) {
  const { spacing = -8, children, className, style } = props;
  const groupStyle: CSSProperties = {
    ...style,
    ['--cf-LEGACY-avatar-spacing' as any]: `${spacing}px`,
  };
  const cls = ['cf-avatar-group', className].filter(Boolean).join(' ');

  return (
    <span className={cls} style={groupStyle}>
      {children}
    </span>
  );
}

// packages/vue/src/avatar/AvatarGroup.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { AvatarGroupProps } from './variants';

const props = withDefaults(defineProps<AvatarGroupProps>(), {
  size: 'md',
  shape: 'circle',
  max: 0,
  spacing: -8,
});

const groupStyle = computed(() => ({
  '--cf-LEGACY-avatar-spacing': `${props.spacing}px`,
}));
</script>

<template>
  <span class="cf-avatar-group" :style="groupStyle">
    <slot />
  </span>
</template>
