// packages/react/src/avatar/Avatar.tsx
import { useEffect, useState } from 'react';
import {
  avatarClass,
  initialsFromName,
  type AvatarProps,
} from './variants';

export function Avatar(props: AvatarProps) {
  const {
    src,
    alt,
    name,
    size = 'md',
    shape = 'circle',
    fallback,
    children,
    className,
    style,
  } = props;

  const [failed, setFailed] = useState(false);

  useEffect(() => {
    setFailed(false);
  }, [src]);

  const showImage = !!src && !failed;
  const initials = initialsFromName(name, fallback);

  return (
    <span
      className={avatarClass({ size, shape, className })}
      role="img"
      aria-label={alt || name}
      style={style}
    >
      {showImage ? (
        <img
          className="ck-avatar__img"
          src={src}
          alt={alt || name || ''}
          onError={() => setFailed(true)}
        />
      ) : children ? (
        <span className="ck-avatar__icon">{children}</span>
      ) : (
        <span className="ck-avatar__initials">{initials}</span>
      )}
    </span>
  );
}

// packages/vue/src/avatar/Avatar.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import {
  avatarClass,
  initialsFromName,
  type AvatarProps,
} from './variants';

const props = withDefaults(defineProps<AvatarProps>(), {
  size: 'md',
  shape: 'circle',
});

const failed = ref(false);

watch(
  () => props.src,
  () => {
    failed.value = false;
  },
);

const cls = computed(() => avatarClass({ size: props.size, shape: props.shape }));
const showImage = computed(() => !!props.src && !failed.value);
const initials = computed(() => initialsFromName(props.name, props.fallback));
</script>

<template>
  <span :class="cls" role="img" :aria-label="alt || name">
    <img
      v-if="showImage"
      class="cf-avatar__img"
      :src="src"
      :alt="alt || name || ''"
      @error="failed = true"
    />
    <span v-else-if="$slots.default" class="cf-avatar__icon"><slot /></span>
    <span v-else class="cf-avatar__initials">{{ initials }}</span>
  </span>
</template>
