// packages/react/src/datagrid/DataGrid.tsx
import {
  useEffect,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type KeyboardEvent,
  type PointerEvent as ReactPointerEvent,
} from 'react';
import {
  compareCells,
  getCellValue,
  getRowKey,
  nextSortDirection,
  type TableSort,
} from '../table/variants';
import type {
  DataGridColumn,
  DataGridProps,
} from './variants';

export function DataGrid<T extends Record<string, unknown> = Record<string, unknown>>(
  props: DataGridProps<T>,
) {
  const {
    columns,
    rows,
    rowKey,
    size = 'md',
    hoverable = true,
    emptyText = '暂无数据',
    loading = false,
    selectable,
    value,
    defaultValue,
    maxHeight,
    className,
    onChange,
    onCellEdit,
    onColumnResize,
  } = props;

  const [widths, setWidths] = useState<Record<string, number>>(
    Object.fromEntries(
      columns
        .filter((c) => typeof c.width === 'number')
        .map((c) => [c.key, c.width as number]),
    ),
  );
  const [sort, setSort] = useState<TableSort | null>(null);
  const [editingKey, setEditingKey] = useState<string | null>(null);
  const [draftValue, setDraftValue] = useState('');

  const isControlled = value !== undefined;
  const [internal, setInternal] = useState<string | string[] | null>(
    defaultValue ?? (selectable === 'multiple' ? [] : null),
  );
  const current = isControlled ? value : internal;

  const sortedRows = useMemo(() => {
    if (!sort || !sort.direction) return rows;
    const col = columns.find((c) => c.key === sort.key);
    if (!col?.sortable) return rows;
    const sign = sort.direction === 'asc' ? 1 : -1;
    return [...rows].sort(
      (a, b) => sign * compareCells(getCellValue(a, col), getCellValue(b, col)),
    );
  }, [rows, columns, sort]);

  function handleSort(col: DataGridColumn<T>) {
    if (!col.sortable) return;
    if (sort?.key === col.key) {
      const dir = nextSortDirection(sort.direction);
      setSort(dir ? { key: col.key, direction: dir } : null);
    } else {
      setSort({ key: col.key, direction: 'asc' });
    }
  }

  const selectedSet = useMemo(() => {
    if (selectable === 'multiple') {
      return new Set(Array.isArray(current) ? current : []);
    }
    if (selectable === 'single') {
      return new Set(current ? [current as string] : []);
    }
    return new Set<string>();
  }, [current, selectable]);

  function commit(next: string | string[] | null) {
    if (!isControlled) setInternal(next);
    onChange?.(next);
  }

  function toggleRow(key: string) {
    if (selectable === 'single') {
      commit(key);
      return;
    }
    if (selectable !== 'multiple') return;
    const next = new Set(selectedSet);
    if (next.has(key)) next.delete(key);
    else next.add(key);
    commit(Array.from(next));
  }

  function colWidthStyle(col: DataGridColumn<T>): CSSProperties | undefined {
    const w = widths[col.key] ?? col.width;
    if (w == null) return undefined;
    return { width: typeof w === 'number' ? `${w}px` : w };
  }

  function startResize(col: DataGridColumn<T>, e: ReactPointerEvent<HTMLSpanElement>) {
    if (!col.resizable) return;
    e.preventDefault();
    e.stopPropagation();
    const target = e.currentTarget;
    const startX = e.clientX;
    const th = target.parentElement as HTMLElement;
    const startWidth = th.getBoundingClientRect().width;
    target.setPointerCapture(e.pointerId);

    function onMove(ev: globalThis.PointerEvent) {
      const next = Math.max(col.minWidth ?? 60, startWidth + ev.clientX - startX);
      setWidths((w) => ({ ...w, [col.key]: next }));
    }
    function onUp(ev: globalThis.PointerEvent) {
      target.releasePointerCapture(ev.pointerId);
      target.removeEventListener('pointermove', onMove);
      target.removeEventListener('pointerup', onUp);
      target.removeEventListener('pointercancel', onUp);
      onColumnResize?.(col, widths[col.key]);
    }
    target.addEventListener('pointermove', onMove);
    target.addEventListener('pointerup', onUp);
    target.addEventListener('pointercancel', onUp);
  }

  function cellId(rk: string, ck: string) {
    return `${rk}::${ck}`;
  }

  function startEdit(row: T, rowIndex: number, col: DataGridColumn<T>) {
    if (!col.editable) return;
    const rk = getRowKey(row, rowIndex, rowKey);
    setEditingKey(cellId(rk, col.key));
    setDraftValue(String(getCellValue(row, col) ?? ''));
  }

  function commitEdit(row: T, rowIndex: number, col: DataGridColumn<T>) {
    if (!editingKey) return;
    onCellEdit?.({
      row,
      rowIndex,
      column: col,
      value: draftValue,
      previous: getCellValue(row, col),
    });
    setEditingKey(null);
    setDraftValue('');
  }

  function cancelEdit() {
    setEditingKey(null);
    setDraftValue('');
  }

  function onCellKeydown(
    e: KeyboardEvent<HTMLInputElement>,
    row: T,
    rowIndex: number,
    col: DataGridColumn<T>,
  ) {
    if (e.key === 'Enter') {
      e.preventDefault();
      commitEdit(row, rowIndex, col);
    } else if (e.key === 'Escape') {
      e.preventDefault();
      cancelEdit();
    }
  }

  const editInputRef = useRef<HTMLInputElement | null>(null);
  useEffect(() => {
    if (editingKey && editInputRef.current) editInputRef.current.focus();
  }, [editingKey]);

  const cls = [
    'cf-datagrid',
    `cf-datagrid--${size}`,
    hoverable && 'is-hoverable',
    loading && 'is-loading',
    className,
  ].filter(Boolean).join(' ');

  const scrollStyle: CSSProperties | undefined =
    maxHeight != null
      ? { maxHeight: typeof maxHeight === 'number' ? `${maxHeight}px` : maxHeight }
      : undefined;

  return (
    <div className={cls}>
      <div className="cf-datagrid__scroll" style={scrollStyle}>
        <table className="cf-datagrid__table">
          <colgroup>
            {selectable === 'multiple' ? <col style={{ width: 36 }} /> : null}
            {columns.map((col) => (
              <col key={col.key} style={colWidthStyle(col)} />
            ))}
          </colgroup>
          <thead className="cf-datagrid__head">
            <tr>
              {selectable === 'multiple' ? (
                <th className="cf-datagrid__cell cf-datagrid__cell--th cf-datagrid__cell--check" />
              ) : null}
              {columns.map((col) => {
                const dir = sort?.key === col.key ? sort.direction : null;
                const thCls = [
                  'cf-datagrid__cell',
                  'cf-datagrid__cell--th',
                  col.align && `cf-datagrid__cell--${col.align}`,
                  col.sortable && 'is-sortable',
                  sort?.key === col.key && 'is-sorted',
                ].filter(Boolean).join(' ');
                return (
                  <th
                    key={col.key}
                    className={thCls}
                    onClick={() => handleSort(col)}
                  >
                    <span className="cf-datagrid__th-label">
                      {col.title}
                      {col.sortable ? (
                        <svg
                          className={`cf-datagrid__sort is-${dir ?? 'idle'}`}
                          viewBox="0 0 12 12"
                          aria-hidden="true"
                        >
                          <path d="M6 2l3 3H3z" fill="currentColor" />
                          <path d="M6 10L3 7h6z" fill="currentColor" />
                        </svg>
                      ) : null}
                    </span>
                    {col.resizable ? (
                      <span
                        className="cf-datagrid__resize"
                        onPointerDown={(e) => startResize(col, e)}
                        onClick={(e) => e.stopPropagation()}
                      />
                    ) : null}
                  </th>
                );
              })}
            </tr>
          </thead>
          <tbody className="cf-datagrid__body">
            {!sortedRows.length ? (
              <tr className="cf-datagrid__row cf-datagrid__row--empty">
                <td
                  className="cf-datagrid__cell"
                  colSpan={columns.length + (selectable === 'multiple' ? 1 : 0)}
                >
                  {emptyText}
                </td>
              </tr>
            ) : (
              sortedRows.map((row, i) => {
                const rk = getRowKey(row, i, rowKey);
                const sel = selectedSet.has(rk);
                const trCls = [
                  'cf-datagrid__row',
                  sel && 'is-selected',
                  selectable && 'is-clickable',
                ].filter(Boolean).join(' ');
                return (
                  <tr
                    key={rk}
                    className={trCls}
                    onClick={() => selectable && toggleRow(rk)}
                  >
                    {selectable === 'multiple' ? (
                      <td className="cf-datagrid__cell cf-datagrid__cell--check">
                        <input
                          type="checkbox"
                          checked={sel}
                          onClick={(e) => e.stopPropagation()}
                          onChange={() => toggleRow(rk)}
                        />
                      </td>
                    ) : null}
                    {columns.map((col) => {
                      const editing = editingKey === cellId(rk, col.key);
                      const tdCls = [
                        'cf-datagrid__cell',
                        col.align && `cf-datagrid__cell--${col.align}`,
                        col.editable && 'is-editable',
                      ].filter(Boolean).join(' ');
                      const v = getCellValue(row, col);
                      const display = col.render
                        ? col.render(v, row, i)
                        : col.format
                          ? col.format(v, row, i)
                          : (v as React.ReactNode);
                      return (
                        <td
                          key={col.key}
                          className={tdCls}
                          onDoubleClick={() => startEdit(row, i, col)}
                        >
                          {editing ? (
                            <input
                              ref={editInputRef}
                              className="cf-datagrid__edit"
                              value={draftValue}
                              onChange={(e) => setDraftValue(e.target.value)}
                              onBlur={() => commitEdit(row, i, col)}
                              onKeyDown={(e) => onCellKeydown(e, row, i, col)}
                              onClick={(e) => e.stopPropagation()}
                            />
                          ) : (
                            (display as React.ReactNode)
                          )}
                        </td>
                      );
                    })}
                  </tr>
                );
              })
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// packages/vue/src/datagrid/DataGrid.vue
<script setup lang="ts" generic="T extends Record<string, unknown>">
import { computed, ref, watch } from 'vue';
import {
  compareCells,
  getCellValue,
  getRowKey,
  nextSortDirection,
  type TableSort,
} from '../table/variants';
import type {
  DataGridColumn,
  DataGridProps,
  DataGridCellEdit,
} from './variants';

const props = withDefaults(defineProps<DataGridProps<T>>(), {
  size: 'md',
  hoverable: true,
  emptyText: '暂无数据',
  loading: false,
  modelValue: null,
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: string | string[] | null): void;
  (e: 'cellEdit', edit: DataGridCellEdit<T>): void;
  (e: 'columnResize', col: DataGridColumn<T>, width: number): void;
}>();

const widths = ref<Record<string, number>>(
  Object.fromEntries(
    props.columns
      .filter((c) => typeof c.width === 'number')
      .map((c) => [c.key, c.width as number]),
  ),
);

const sort = ref<TableSort | null>(null);
const editingKey = ref<string | null>(null);
const draftValue = ref('');

const sortedRows = computed(() => {
  if (!sort.value || !sort.value.direction) return props.rows;
  const col = props.columns.find((c) => c.key === sort.value!.key);
  if (!col?.sortable) return props.rows;
  const sign = sort.value.direction === 'asc' ? 1 : -1;
  return [...props.rows].sort(
    (a, b) => sign * compareCells(getCellValue(a, col), getCellValue(b, col)),
  );
});

function onSort(col: DataGridColumn<T>) {
  if (!col.sortable) return;
  if (sort.value?.key === col.key) {
    const dir = nextSortDirection(sort.value.direction);
    sort.value = dir ? { key: col.key, direction: dir } : null;
  } else {
    sort.value = { key: col.key, direction: 'asc' };
  }
}

const selectedSet = computed(() => {
  if (props.selectable === 'multiple') {
    const arr = Array.isArray(props.modelValue) ? props.modelValue : [];
    return new Set(arr);
  }
  if (props.selectable === 'single') {
    return new Set(props.modelValue ? [props.modelValue as string] : []);
  }
  return new Set<string>();
});

function toggleRow(key: string) {
  if (props.selectable === 'single') {
    emit('update:modelValue', key);
    return;
  }
  if (props.selectable !== 'multiple') return;
  const next = new Set(selectedSet.value);
  if (next.has(key)) next.delete(key);
  else next.add(key);
  emit('update:modelValue', Array.from(next));
}

function colWidthStyle(col: DataGridColumn<T>) {
  const w = widths.value[col.key] ?? col.width;
  if (w == null) return undefined;
  return { width: typeof w === 'number' ? `${w}px` : w };
}

function startResize(col: DataGridColumn<T>, e: PointerEvent) {
  if (!col.resizable) return;
  e.preventDefault();
  e.stopPropagation();
  const target = e.currentTarget as HTMLElement;
  const startX = e.clientX;
  const th = target.parentElement as HTMLElement;
  const startWidth = th.getBoundingClientRect().width;
  target.setPointerCapture(e.pointerId);

  function onMove(ev: PointerEvent) {
    const next = Math.max(col.minWidth ?? 60, startWidth + ev.clientX - startX);
    widths.value = { ...widths.value, [col.key]: next };
  }
  function onUp(ev: PointerEvent) {
    target.releasePointerCapture(ev.pointerId);
    target.removeEventListener('pointermove', onMove);
    target.removeEventListener('pointerup', onUp);
    target.removeEventListener('pointercancel', onUp);
    emit('columnResize', col, widths.value[col.key]);
  }
  target.addEventListener('pointermove', onMove);
  target.addEventListener('pointerup', onUp);
  target.addEventListener('pointercancel', onUp);
}

function cellId(rowKey: string, colKey: string) {
  return `${rowKey}::${colKey}`;
}

function startEdit(row: T, rowIndex: number, col: DataGridColumn<T>) {
  if (!col.editable) return;
  const rk = getRowKey(row, rowIndex, props.rowKey);
  editingKey.value = cellId(rk, col.key);
  draftValue.value = String(getCellValue(row, col) ?? '');
}

function commitEdit(row: T, rowIndex: number, col: DataGridColumn<T>) {
  if (!editingKey.value) return;
  const previous = getCellValue(row, col);
  emit('cellEdit', {
    row,
    rowIndex,
    column: col,
    value: draftValue.value,
    previous,
  });
  editingKey.value = null;
  draftValue.value = '';
}

function cancelEdit() {
  editingKey.value = null;
  draftValue.value = '';
}

function onCellKeydown(e: KeyboardEvent, row: T, rowIndex: number, col: DataGridColumn<T>) {
  if (e.key === 'Enter') {
    e.preventDefault();
    commitEdit(row, rowIndex, col);
  } else if (e.key === 'Escape') {
    e.preventDefault();
    cancelEdit();
  }
}

const rootStyle = computed(() => {
  if (props.maxHeight == null) return undefined;
  return {
    maxHeight:
      typeof props.maxHeight === 'number' ? `${props.maxHeight}px` : props.maxHeight,
  };
});
</script>

<template>
  <div
    class="cf-datagrid"
    :class="[
      `cf-datagrid--${size}`,
      hoverable && 'is-hoverable',
      loading && 'is-loading',
    ]"
  >
    <div class="cf-datagrid__scroll" :style="rootStyle">
      <table class="cf-datagrid__table">
        <colgroup>
          <col v-if="selectable === 'multiple'" style="width: 36px;" />
          <col
            v-for="col in columns"
            :key="col.key"
            :style="colWidthStyle(col)"
          />
        </colgroup>
        <thead class="cf-datagrid__head">
          <tr>
            <th
              v-if="selectable === 'multiple'"
              class="cf-datagrid__cell cf-datagrid__cell--th cf-datagrid__cell--check"
            />
            <th
              v-for="col in columns"
              :key="col.key"
              class="cf-datagrid__cell cf-datagrid__cell--th"
              :class="[
                col.align && `cf-datagrid__cell--${col.align}`,
                col.sortable && 'is-sortable',
                sort?.key === col.key && 'is-sorted',
              ]"
              @click="onSort(col)"
            >
              <span class="cf-datagrid__th-label">
                {{ col.title }}
                <svg
                  v-if="col.sortable"
                  class="cf-datagrid__sort"
                  :class="`is-${sort?.key === col.key ? sort.direction : 'idle'}`"
                  viewBox="0 0 12 12"
                  aria-hidden="true"
                >
                  <path d="M6 2l3 3H3z" fill="currentColor" />
                  <path d="M6 10L3 7h6z" fill="currentColor" />
                </svg>
              </span>
              <span
                v-if="col.resizable"
                class="cf-datagrid__resize"
                @pointerdown="startResize(col, $event)"
                @click.stop
              />
            </th>
          </tr>
        </thead>
        <tbody class="cf-datagrid__body">
          <tr v-if="!sortedRows.length" class="cf-datagrid__row cf-datagrid__row--empty">
            <td
              class="cf-datagrid__cell"
              :colspan="columns.length + (selectable === 'multiple' ? 1 : 0)"
            >
              {{ emptyText }}
            </td>
          </tr>
          <tr
            v-for="(row, i) in sortedRows"
            :key="getRowKey(row, i, rowKey)"
            class="cf-datagrid__row"
            :class="[
              selectedSet.has(getRowKey(row, i, rowKey)) && 'is-selected',
              selectable && 'is-clickable',
            ]"
            @click="selectable && toggleRow(getRowKey(row, i, rowKey))"
          >
            <td
              v-if="selectable === 'multiple'"
              class="cf-datagrid__cell cf-datagrid__cell--check"
            >
              <input
                type="checkbox"
                :checked="selectedSet.has(getRowKey(row, i, rowKey))"
                @click.stop
                @change="toggleRow(getRowKey(row, i, rowKey))"
              />
            </td>
            <td
              v-for="col in columns"
              :key="col.key"
              class="cf-datagrid__cell"
              :class="[
                col.align && `cf-datagrid__cell--${col.align}`,
                col.editable && 'is-editable',
              ]"
              @dblclick="startEdit(row, i, col)"
            >
              <input
                v-if="editingKey === cellId(getRowKey(row, i, rowKey), col.key)"
                v-model="draftValue"
                class="cf-datagrid__edit"
                autofocus
                @keydown="onCellKeydown($event, row, i, col)"
                @blur="commitEdit(row, i, col)"
                @click.stop
              />
              <template v-else>
                <template v-if="col.format">
                  {{ col.format(getCellValue(row, col), row, i) }}
                </template>
                <template v-else>
                  {{ getCellValue(row, col) }}
                </template>
              </template>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
