// packages/react/src/jsondiff/JsonDiff.tsx
import { diffJson, jsonDiffClass, type DiffOp, type JsonDiffProps } from './variants';

function sigil(op: DiffOp): string {
  return op === 'add' ? '+' : op === 'del' ? '-' : ' ';
}

export function JsonDiff(props: JsonDiffProps) {
  const {
    left,
    right,
    size = 'md',
    bordered = true,
    lineNumbers = true,
    className,
  } = props;

  const lines = diffJson(left, right);
  const cls = jsonDiffClass({ size, bordered, lineNumbers, className });

  return (
    <pre className={cls}>
      {lines.map((line, i) => (
        <span key={i} className={`cf-jdiff__line cf-jdiff__line--${line.op}`}>
          {lineNumbers ? <span className="cf-jdiff__num">{i + 1}</span> : null}
          <span className="cf-jdiff__sigil">{sigil(line.op)}</span>
          <span className="cf-jdiff__text">{line.text}</span>
          {'\n'}
        </span>
      ))}
    </pre>
  );
}

// packages/vue/src/jsondiff/JsonDiff.vue
<script setup lang="ts">
import { computed } from 'vue';
import { diffJson, jsonDiffClass, type JsonDiffProps } from './variants';

const props = withDefaults(defineProps<JsonDiffProps>(), {
  size: 'md',
  bordered: true,
  lineNumbers: true,
});

const lines = computed(() => diffJson(props.left, props.right));
const cls = computed(() =>
  jsonDiffClass({
    size: props.size,
    bordered: props.bordered,
    lineNumbers: props.lineNumbers,
    className: props.className,
  }),
);

function sigil(op: 'eq' | 'add' | 'del') {
  return op === 'add' ? '+' : op === 'del' ? '-' : ' ';
}
</script>

<template>
  <pre :class="cls">
<span
  v-for="(line, i) in lines"
  :key="i"
  :class="['cf-jdiff__line', `cf-jdiff__line--${line.op}`]"
><span v-if="lineNumbers" class="cf-jdiff__num">{{ i + 1 }}</span><span class="cf-jdiff__sigil">{{ sigil(line.op) }}</span><span class="cf-jdiff__text">{{ line.text }}</span>
</span></pre>
</template>
