// packages/vue/src/typography/Paragraph.vue
<script setup lang="ts">
import { computed } from 'vue';
import { paragraphClass, type ParagraphProps } from './variants';

const props = withDefaults(defineProps<ParagraphProps>(), {
  size: 'md',
  lineClamp: 0,
});

const cls = computed(() => paragraphClass(props));
const clampStyle = computed(() =>
  props.lineClamp && props.lineClamp > 0
    ? {
        display: '-webkit-box',
        WebkitBoxOrient: 'vertical' as const,
        WebkitLineClamp: String(props.lineClamp),
        overflow: 'hidden',
      }
    : undefined,
);
</script>

<template>
  <p :class="cls" :style="clampStyle">
    <slot />
  </p>
</template>

// packages/react/src/typography/Paragraph.tsx
import type { CSSProperties } from 'react';
import { paragraphClass, type ParagraphProps } from './variants';

export function Paragraph(props: ParagraphProps) {
  const { children, className, lineClamp } = props;
  const cls = [paragraphClass(props), className].filter(Boolean).join(' ');
  const style: CSSProperties | undefined =
    lineClamp && lineClamp > 0
      ? {
          display: '-webkit-box',
          WebkitBoxOrient: 'vertical',
          WebkitLineClamp: lineClamp,
          overflow: 'hidden',
        }
      : undefined;
  return (
    <p className={cls} style={style}>
      {children}
    </p>
  );
}
