// packages/vue/src/donutchart/DonutChart.vue
<script setup lang="ts">
import { computed } from 'vue';
import { arcPath } from '../_charts/scale';
import type { DonutChartProps } from './variants';

const props = withDefaults(defineProps<DonutChartProps>(), {
  size: 180,
  thickness: 24,
  showLegend: true,
});

const layout = computed(() => {
  const segs = props.segments ?? [];
  const total = segs.reduce((s, x) => s + x.value, 0) || 1;
  const cx = props.size / 2;
  const cy = props.size / 2;
  const rOuter = props.size / 2 - 2;
  const rInner = rOuter - props.thickness;
  let acc = 0;
  return segs.map((s, i) => {
    const start = (acc / total) * 360;
    acc += s.value;
    const end = (acc / total) * 360;
    return {
      ...s,
      colorIndex: s.colorIndex ?? i % 8,
      d: arcPath(cx, cy, rOuter, rInner, start, end),
      pct: ((end - start) / 360) * 100,
    };
  });
});
</script>

<template>
  <div class="cf-donut" role="img" :aria-label="ariaLabel ?? '环形图'">
    <svg
      class="cf-chart"
      :viewBox="`0 0 ${size} ${size}`"
      :width="size"
      :height="size"
    >
      <path
        v-for="(s, i) in layout"
        :key="i"
        :class="`cf-chart__bar--${s.colorIndex}`"
        :d="s.d"
      />
      <text
        v-if="centerValue != null"
        :x="size / 2"
        :y="size / 2 - 4"
        text-anchor="middle"
        class="cf-donut__value"
      >{{ centerValue }}</text>
      <text
        v-if="centerLabel"
        :x="size / 2"
        :y="size / 2 + 14"
        text-anchor="middle"
        class="cf-donut__label"
      >{{ centerLabel }}</text>
    </svg>
    <ul v-if="showLegend" class="cf-donut__legend">
      <li v-for="(s, i) in layout" :key="i">
        <span :class="['cf-donut__dot', `cf-chart__bar--${s.colorIndex}`]" />
        {{ s.name }}
        <span class="cf-donut__pct">{{ s.pct.toFixed(1) }}%</span>
      </li>
    </ul>
  </div>
</template>

// packages/react/src/donutchart/DonutChart.tsx
import { useMemo } from 'react';
import { arcPath } from '../_charts/scale';
import type { DonutChartProps } from './variants';

export function DonutChart(props: DonutChartProps) {
  const {
    segments,
    size = 180,
    thickness = 24,
    showLegend = true,
    centerLabel,
    centerValue,
    ariaLabel = '环形图',
    className,
  } = props;

  const layout = useMemo(() => {
    const total = segments.reduce((s, x) => s + x.value, 0) || 1;
    const cx = size / 2;
    const cy = size / 2;
    const rOuter = size / 2 - 2;
    const rInner = rOuter - thickness;
    let acc = 0;
    return segments.map((s, i) => {
      const start = (acc / total) * 360;
      acc += s.value;
      const end = (acc / total) * 360;
      return {
        ...s,
        colorIndex: s.colorIndex ?? i % 8,
        d: arcPath(cx, cy, rOuter, rInner, start, end),
        pct: ((end - start) / 360) * 100,
      };
    });
  }, [segments, size, thickness]);

  return (
    <div
      className={['cf-donut', className].filter(Boolean).join(' ')}
      role="img"
      aria-label={ariaLabel}
    >
      <svg
        className="cf-chart"
        viewBox={`0 0 ${size} ${size}`}
        width={size}
        height={size}
      >
        {layout.map((s, i) => (
          <path
            key={i}
            className={`cf-chart__bar--${s.colorIndex}`}
            d={s.d}
          />
        ))}
        {centerValue != null ? (
          <text
            x={size / 2}
            y={size / 2 - 4}
            textAnchor="middle"
            className="cf-donut__value"
          >
            {centerValue}
          </text>
        ) : null}
        {centerLabel ? (
          <text
            x={size / 2}
            y={size / 2 + 14}
            textAnchor="middle"
            className="cf-donut__label"
          >
            {centerLabel}
          </text>
        ) : null}
      </svg>
      {showLegend ? (
        <ul className="cf-donut__legend">
          {layout.map((s, i) => (
            <li key={i}>
              <span className={`cf-donut__dot cf-chart__bar--${s.colorIndex}`} />
              {s.name}
              <span className="cf-donut__pct">{s.pct.toFixed(1)}%</span>
            </li>
          ))}
        </ul>
      ) : null}
    </div>
  );
}
