// packages/vue/src/textarea/Textarea.vue
<script setup lang="ts">
import { computed, nextTick, ref, watch, onMounted } from 'vue';
import { textareaClass, type TextareaProps } from './variants';

const props = withDefaults(defineProps<TextareaProps>(), {
  modelValue: '',
  variant: 'outline',
  size: 'md',
  rows: 3,
  disabled: false,
  readonly: false,
  error: false,
  resize: 'vertical',
  autoResize: false,
  showCount: false,
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void;
  (e: 'change', value: string): void;
  (e: 'focus', ev: FocusEvent): void;
  (e: 'blur', ev: FocusEvent): void;
}>();

const focused = ref(false);
const taRef = ref<HTMLTextAreaElement | null>(null);

const cls = computed(() =>
  textareaClass({
    variant: props.variant,
    size: props.size,
    focused: focused.value,
    disabled: props.disabled,
    error: props.error,
  }),
);

const resizeStyle = computed(() => ({
  resize: props.autoResize ? 'none' : props.resize,
}));

function autoSize() {
  if (!props.autoResize || !taRef.value) return;
  const el = taRef.value;
  el.style.height = 'auto';
  el.style.height = `${el.scrollHeight}px`;
}

onMounted(() => {
  nextTick(autoSize);
});
watch(() => props.modelValue, () => nextTick(autoSize));

function onInput(e: Event) {
  const v = (e.target as HTMLTextAreaElement).value;
  emit('update:modelValue', v);
  if (props.autoResize) nextTick(autoSize);
}

function onChange(e: Event) {
  emit('change', (e.target as HTMLTextAreaElement).value);
}

const count = computed(() => (props.modelValue ?? '').length);
const overLimit = computed(() =>
  props.maxlength != null && count.value > props.maxlength,
);
</script>

<template>
  <div :class="cls">
    <textarea
      ref="taRef"
      class="cf-textarea__el"
      :value="modelValue"
      :rows="rows"
      :placeholder="placeholder"
      :disabled="disabled"
      :readonly="readonly"
      :maxlength="maxlength"
      :name="name"
      :id="id"
      :style="resizeStyle"
      @input="onInput"
      @change="onChange"
      @focus="(ev) => { focused = true; emit('focus', ev); }"
      @blur="(ev) => { focused = false; emit('blur', ev); }"
    />
    <div v-if="showCount" class="cf-textarea__count" :class="{ 'is-over': overLimit }">
      {{ count }}<template v-if="maxlength != null"> / {{ maxlength }}</template>
    </div>
  </div>
</template>

// packages/react/src/textarea/Textarea.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
  type ChangeEvent,
  type CSSProperties,
  type FocusEvent,
} from 'react';
import { textareaClass, type TextareaProps } from './variants';

export const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(
  function Textarea(props, ref) {
    const {
      variant = 'outline',
      size = 'md',
      rows = 3,
      disabled = false,
      error = false,
      resize = 'vertical',
      autoResize = false,
      showCount = false,
      maxLength,
      value,
      defaultValue,
      onChange,
      onFocus,
      onBlur,
      className,
      style,
      ...rest
    } = props;

    const taRef = useRef<HTMLTextAreaElement | null>(null);
    useImperativeHandle(ref, () => taRef.current as HTMLTextAreaElement);

    const [focused, setFocused] = useState(false);
    const [internal, setInternal] = useState<string>(
      typeof defaultValue === 'string' ? defaultValue : '',
    );
    const isControlled = value !== undefined;
    const current = isControlled ? String(value) : internal;

    function autoSize() {
      const el = taRef.current;
      if (!el || !autoResize) return;
      el.style.height = 'auto';
      el.style.height = `${el.scrollHeight}px`;
    }

    useEffect(() => {
      if (autoResize) autoSize();
    });

    function handleChange(e: ChangeEvent<HTMLTextAreaElement>) {
      if (!isControlled) setInternal(e.target.value);
      onChange?.(e);
    }

    function handleFocus(e: FocusEvent<HTMLTextAreaElement>) {
      setFocused(true);
      onFocus?.(e);
    }

    function handleBlur(e: FocusEvent<HTMLTextAreaElement>) {
      setFocused(false);
      onBlur?.(e);
    }

    const taStyle: CSSProperties = {
      ...style,
      resize: autoResize ? 'none' : resize,
    };

    const overLimit = maxLength != null && current.length > maxLength;

    return (
      <div
        className={textareaClass({
          variant,
          size,
          focused,
          disabled,
          error,
          className,
        })}
      >
        <textarea
          ref={taRef}
          className="ck-textarea__el"
          rows={rows}
          disabled={disabled}
          maxLength={maxLength}
          value={current}
          style={taStyle}
          onChange={handleChange}
          onFocus={handleFocus}
          onBlur={handleBlur}
          {...rest}
        />
        {showCount ? (
          <div
            className={
              'ck-textarea__count' + (overLimit ? ' is-over' : '')
            }
          >
            {current.length}
            {maxLength != null ? ` / ${maxLength}` : null}
          </div>
        ) : null}
      </div>
    );
  },
);
