// packages/vue/src/highlight/Highlight.vue
<script setup lang="ts">
import { computed } from 'vue';
import { highlightClass, splitByMatch, type HighlightProps } from './variants';

const props = withDefaults(defineProps<HighlightProps>(), {
  caseSensitive: false,
});

const cls = computed(() => highlightClass({ className: props.className }));
const segments = computed(() =>
  splitByMatch(props.text, props.match, props.caseSensitive),
);
</script>

<template>
  <span :class="cls">
    <template v-for="(seg, i) in segments" :key="i">
      <mark v-if="seg.hit" class="cf-highlight__hit">{{ seg.text }}</mark>
      <template v-else>{{ seg.text }}</template>
    </template>
  </span>
</template>

// packages/react/src/highlight/Highlight.tsx
import { highlightClass, splitByMatch, type HighlightProps } from './variants';

export function Highlight({
  text,
  match,
  caseSensitive = false,
  className,
}: HighlightProps) {
  const cls = highlightClass({ className });
  const segments = splitByMatch(text, match, caseSensitive);
  return (
    <span className={cls}>
      {segments.map((seg, i) =>
        seg.hit ? (
          <mark key={i} className="cf-highlight__hit">{seg.text}</mark>
        ) : (
          <span key={i}>{seg.text}</span>
        ),
      )}
    </span>
  );
}
