// packages/vue/src/tooltip/Tooltip.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref } from 'vue';
import {
  computeTooltipPosition,
  type TooltipPlacement,
  type TooltipProps,
} from './variants';

const props = withDefaults(defineProps<TooltipProps>(), {
  content: '',
  placement: 'top',
  delay: 100,
  hideDelay: 80,
  disabled: false,
  offset: 8,
});

const triggerRef = ref<HTMLSpanElement | null>(null);
const tipRef = ref<HTMLDivElement | null>(null);
const visible = ref(false);
const pos = ref({ top: 0, left: 0, placement: props.placement as TooltipPlacement });

let openTimer: ReturnType<typeof setTimeout> | null = null;
let closeTimer: ReturnType<typeof setTimeout> | null = null;

function clearTimers() {
  if (openTimer) clearTimeout(openTimer);
  if (closeTimer) clearTimeout(closeTimer);
  openTimer = null;
  closeTimer = null;
}

async function reposition() {
  if (!triggerRef.value || !tipRef.value) return;
  const tRect = triggerRef.value.getBoundingClientRect();
  const tw = tipRef.value.offsetWidth;
  const th = tipRef.value.offsetHeight;
  pos.value = computeTooltipPosition(tRect, tw, th, props.placement, props.offset);
}

function show() {
  if (props.disabled || !props.content) return;
  clearTimers();
  openTimer = setTimeout(async () => {
    visible.value = true;
    await nextTick();
    reposition();
  }, props.delay);
}

function hide() {
  clearTimers();
  closeTimer = setTimeout(() => {
    visible.value = false;
  }, props.hideDelay);
}

const tipStyle = computed(() => ({
  top: `${pos.value.top}px`,
  left: `${pos.value.left}px`,
  maxWidth:
    typeof props.maxWidth === 'number' ? `${props.maxWidth}px` : props.maxWidth,
}));

const tipClass = computed(
  () => `cf-tooltip cf-tooltip--${pos.value.placement}`,
);

onBeforeUnmount(clearTimers);
</script>

<template>
  <span
    ref="triggerRef"
    class="cf-tooltip-trigger"
    @mouseenter="show"
    @mouseleave="hide"
    @focusin="show"
    @focusout="hide"
  >
    <slot />
  </span>
  <Teleport to="body">
    <Transition name="cf-tooltip-fade">
      <div
        v-if="visible"
        ref="tipRef"
        :class="tipClass"
        role="tooltip"
        :style="tipStyle"
      >
        <slot name="content">{{ content }}</slot>
        <span class="cf-tooltip__arrow" />
      </div>
    </Transition>
  </Teleport>
</template>

// packages/react/src/tooltip/Tooltip.tsx
import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type CSSProperties,
} from 'react';
import { createPortal } from 'react-dom';
import {
  computeTooltipPosition,
  type TooltipPlacement,
  type TooltipProps,
} from './variants';

export function Tooltip(props: TooltipProps) {
  const {
    content,
    placement = 'top',
    delay = 100,
    hideDelay = 80,
    disabled = false,
    offset = 8,
    maxWidth,
    children,
  } = props;

  const triggerRef = useRef<HTMLSpanElement | null>(null);
  const tipRef = useRef<HTMLDivElement | null>(null);
  const openTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const closeTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const [open, setOpen] = useState(false);
  const [mounted, setMounted] = useState(false);
  const [pos, setPos] = useState<{
    top: number;
    left: number;
    placement: TooltipPlacement;
  }>({ top: 0, left: 0, placement });

  const clearTimers = useCallback(() => {
    if (openTimer.current) clearTimeout(openTimer.current);
    if (closeTimer.current) clearTimeout(closeTimer.current);
    openTimer.current = null;
    closeTimer.current = null;
  }, []);

  const show = useCallback(() => {
    if (disabled || !content) return;
    clearTimers();
    openTimer.current = setTimeout(() => {
      setMounted(true);
      setOpen(true);
    }, delay);
  }, [disabled, content, delay, clearTimers]);

  const hide = useCallback(() => {
    clearTimers();
    closeTimer.current = setTimeout(() => {
      setOpen(false);
      setTimeout(() => setMounted(false), 120);
    }, hideDelay);
  }, [hideDelay, clearTimers]);

  useLayoutEffect(() => {
    if (!open || !mounted) return;
    if (!triggerRef.current || !tipRef.current) return;
    const tRect = triggerRef.current.getBoundingClientRect();
    const tw = tipRef.current.offsetWidth;
    const th = tipRef.current.offsetHeight;
    setPos(computeTooltipPosition(tRect, tw, th, placement, offset));
  }, [open, mounted, placement, offset, content]);

  useEffect(() => () => clearTimers(), [clearTimers]);

  const tipStyle: CSSProperties = {
    top: pos.top,
    left: pos.left,
    maxWidth: typeof maxWidth === 'number' ? `${maxWidth}px` : maxWidth,
  };

  return (
    <>
      <span
        ref={triggerRef}
        className="ck-tooltip-trigger"
        onMouseEnter={show}
        onMouseLeave={hide}
        onFocus={show}
        onBlur={hide}
      >
        {children}
      </span>
      {mounted && typeof document !== 'undefined'
        ? createPortal(
            <div
              ref={tipRef}
              className={`ck-tooltip ck-tooltip--${pos.placement}`}
              data-state={open ? 'open' : 'closed'}
              role="tooltip"
              style={tipStyle}
            >
              {content}
              <span className="ck-tooltip__arrow" />
            </div>,
            document.body,
          )
        : null}
    </>
  );
}
